### ISSUE TITLE
Composer does not work when PHP_XDEBUG_REMOTE_HOST is set

### ISSUE THREAD

**Issue by dmurphy1** [wodby/docker4drupal#113]
Hi - thanks for all your work on this project! I'm having an issue where I can't run Composer commands such as `docker-compose exec --user 82 php composer update`. When I run Composer commands nothing happens and the command hangs. Same for drush commands, such as `docker-compose exec --user 82 php drush --version`.

Debugging locally, it seems this issue is caused by the Xdebug `PHP_XDEBUG_REMOTE_HOST` environmental variable.

To reproduce:

- Place the Docker4Drupal `docker-compose.yml` in a clean directory
- Uncomment all of the PHP Xdebug settings except `PHP_XDEBUG_REMOTE_HOST: "10.254.254.254"`, so your environment variables should look like:

```
    environment:
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
      PHP_XDEBUG: 1
      PHP_XDEBUG_DEFAULT_ENABLE: 1
      PHP_XDEBUG_REMOTE_CONNECT_BACK: 0         # This is needed to respect remote.host setting bellow
      # PHP_XDEBUG_REMOTE_HOST: "10.254.254.254"  # You will also need to 'sudo ifconfig lo0 alias 10.254.254.254'
```

- Run `docker-compose up -d`
- Run `docker-compose exec --user 82 php composer -V` and you should see `Composer version 1.3.3`.
- Run `docker-compose down -v`
- Edit the `docker-compose.yml`, uncommenting `PHP_XDEBUG_REMOTE_HOST: "10.254.254.254"`, so your environment variables should look like:

```
    environment:
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
      PHP_XDEBUG: 1
      PHP_XDEBUG_DEFAULT_ENABLE: 1
      PHP_XDEBUG_REMOTE_CONNECT_BACK: 0         # This is needed to respect remote.host setting bellow
      PHP_XDEBUG_REMOTE_HOST: "10.254.254.254"  # You will also need to 'sudo ifconfig lo0 alias 10.254.254.254'
```

- Run `docker-compose exec --user 82 php composer -V` and nothing is outputted, the command hangs.

I'm running OS X, and I ran `sudo ifconfig lo0 alias 10.254.254.254`

**Comment by PavelPrischepa** [comment]
The following configuration works for me in any cases:

```
PHP_XDEBUG=1
PHP_XDEBUG_DEFAULT_ENABLE=1
PHP_XDEBUG_REMOTE_HOST=<Docker0 IP address>
PHP_IDE_CONFIG=serverName=<Server name in IDE>
PHP_XDEBUG_REMOTE_CONNECT_BACK=0
```

Where `<Docker0 IP address>` is IP address of the `docker0` interface (172.17.0.1 for me).

You can read more about `<Server name in IDE>` [here](https://confluence.jetbrains.com/display/PhpStorm/Debugging+PHP+CLI+scripts+with+PhpStorm).

My configuration is: ![image](https://cloud.githubusercontent.com/assets/1525104/24130330/70a3ea86-0e1a-11e7-9c9f-ab4728e12422.png).

Also you may increase the number of simultaneous debug connections: ![image](https://cloud.githubusercontent.com/assets/1525104/24130403/d7d3a002-0e1a-11e7-95b1-df3e1387bd10.png)

**Comment by dmurphy1** [comment]
Hi @PavelPrischepa - thanks for taking the time to respond, I appreciate it! As it turns out, restarting PHPStorm fixed the problem. Now all is working with the original `docker-compose.yml` settings:

```
    environment:
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
      PHP_XDEBUG: 1
      PHP_XDEBUG_DEFAULT_ENABLE: 1
      PHP_XDEBUG_REMOTE_CONNECT_BACK: 0         # This is needed to respect remote.host setting bellow
      PHP_XDEBUG_REMOTE_HOST: "10.254.254.254"  # You will also need to 'sudo ifconfig lo0 alias 10.254.254.254'
```

When closing PHPStorm I recieved the message

```
Process 'composer' is Running
Do you want to disconnect from the process 'composer'?
```

I suspect that was the culprit. Thanks again, I'm going to close this issue!
