### ISSUE TITLE
MariaDB fails to start

### ISSUE THREAD

**Issue by davidlukac** [Wodby/docker4drupal#12]
Hi,

after running `docker-compose up` I see following errors related to MariaDB:

```
mariadb_1    | 2016-08-05  8:23:54 139727823449128 [Note] mysqld (mysqld 10.1.14-MariaDB) starting as process 1 ...
mariadb_1    | 2016-08-05  8:23:54 139727823449128 [Warning] Setting lower_case_table_names=2 because file system for /var/lib/mysql/ is case insensitive
mariadb_1    | 2016-08-05  8:23:55 139727823449128 [Note] InnoDB: Using mutexes to ref count buffer pool pages
mariadb_1    | 2016-08-05  8:23:55 139727823449128 [Note] InnoDB: The InnoDB memory heap is disabled
mariadb_1    | 2016-08-05  8:23:55 139727823449128 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
mariadb_1    | 2016-08-05  8:23:55 139727823449128 [Note] InnoDB: Memory barrier is not used
mariadb_1    | 2016-08-05  8:23:55 139727823449128 [Note] InnoDB: Compressed tables use zlib 1.2.8
mariadb_1    | 2016-08-05  8:23:55 139727823449128 [Note] InnoDB: Using Linux native AIO
mariadb_1    | 2016-08-05  8:23:55 139727823449128 [Note] InnoDB: Using SSE crc32 instructions
mariadb_1    | 2016-08-05  8:23:55 139727823449128 [Note] InnoDB: Initializing buffer pool, size = 1.0G
mariadb_1    | 2016-08-05  8:23:55 139727823449128 [Note] InnoDB: Completed initialization of buffer pool
mariadb_1    | 2016-08-05  8:23:55 139727823449128 [Note] InnoDB: The first specified data file ./ibdata1 did not exist: a new database to be created!
mariadb_1    | 2016-08-05  8:23:55 139727823449128 [Note] InnoDB: Setting file ./ibdata1 size to 12 MB
mariadb_1    | 2016-08-05  8:23:55 139727823449128 [Note] InnoDB: Database physically writes the file full: wait...
mariadb_1    | 2016-08-05  8:23:56 139727823449128 [Note] InnoDB: Setting log file ./ib_logfile101 size to 32 MB
mariadb_1    | 2016-08-05  8:23:57 139727823449128 [Note] InnoDB: Setting log file ./ib_logfile1 size to 32 MB
mariadb_1    | 2016-08-05  8:23:58 139727823449128 [Note] InnoDB: Renaming log file ./ib_logfile101 to ./ib_logfile0
mariadb_1    | 2016-08-05  8:23:58 139727823449128 [Warning] InnoDB: New log files created, LSN=45883
mariadb_1    | 2016-08-05  8:23:58 139727823449128 [Note] InnoDB: Doublewrite buffer not found: creating new
mariadb_1    | 2016-08-05  8:23:58 139727823449128 [Note] InnoDB: Doublewrite buffer created
mariadb_1    | 2016-08-05  8:23:58 139727823449128 [Note] InnoDB: 128 rollback segment(s) are active.
mariadb_1    | 2016-08-05  8:23:58 139727823449128 [Warning] InnoDB: Creating foreign key constraint system tables.
mariadb_1    | 2016-08-05  8:23:58 139727823449128 [Note] InnoDB: Foreign key constraint system tables created
mariadb_1    | 2016-08-05  8:23:58 139727823449128 [Note] InnoDB: Creating tablespace and datafile system tables.
mariadb_1    | 2016-08-05  8:23:58 139727823449128 [Note] InnoDB: Tablespace and datafile system tables created.
mariadb_1    | 2016-08-05  8:23:58 139727823449128 [Note] InnoDB: Waiting for purge to start
mariadb_1    | 2016-08-05  8:23:58 139727823449128 [Note] InnoDB:  Percona XtraDB (http://www.percona.com) 5.6.29-76.2 started; log sequence number 0
mariadb_1    | 2016-08-05  8:23:58 139726577355440 [Note] InnoDB: Dumping buffer pool(s) not yet started
mariadb_1    | 2016-08-05  8:23:58 139727823449128 [Note] Plugin 'FEEDBACK' is disabled.
mariadb_1    | 2016-08-05  8:23:58 139727823449128 [ERROR] Could not open mysql.plugin table. Some plugins may be not loaded
mariadb_1    | 2016-08-05  8:23:58 139727823449128 [ERROR] Can't open and lock privilege tables: Table 'mysql.servers' doesn't exist
mariadb_1    | 2016-08-05  8:23:58 139727823449128 [Note] Server socket created on IP: '0.0.0.0'.
mariadb_1    | 2016-08-05  8:23:58 139727823449128 [ERROR] Fatal error: Can't open and lock privilege tables: Table 'mysql.user' doesn't exist
virgin_mariadb_1 exited with code 1
```

My `docker-compose` file is:
```
version: "2"

services:
  mariadb:
    image: wodby/drupal-mariadb
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
    volumes:
      - ./docker-runtime/mariadb:/var/lib/mysql
#      - ./docker-runtime/mariadb-init:/docker-entrypoint-initdb.d # Place init .sql file(s) here.

  php:
    image: wodby/drupal-php:5.6 # Allowed: 7.0, 5.6.
    environment:
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
      PHP_XDEBUG_ENABLED: 0 # Set 1 to enable.
    volumes:
      - ./:/var/www/html

  nginx:
    image: wodby/drupal-nginx
    environment:
      NGINX_UPSTREAM_NAME: php
      NGINX_DOCROOT: docroot # Relative path inside the /var/www/html/ directory.
      DRUPAL_VERSION: 7 # Allowed: 7, 8.
    volumes_from:
      - php
    ports:
      - "8000:80"

  pma:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      PMA_HOST: mariadb
      PMA_USER: drupal
      PMA_PASSWORD: drupal
      PHP_UPLOAD_MAX_FILESIZE: 1G
      PHP_MAX_INPUT_VARS: 1G
    ports:
     - "8001:80"

  mailhog:
    image: mailhog/mailhog
    ports:
      - "8002:8025"

  memcached:
    image: memcached:1.4-alpine

  solr:
    image: solr:5.5-alpine
    volumes:
      - ./docker-runtime/solr:/opt/solr/server/solr/mycores
    ports:
      - "8003:8983"
```
