### ISSUE TITLE
404 but both nginx and php list correct files

### ISSUE THREAD

**Issue by magick93** [wodby/docker4drupal#121]
When I browse to http://localhost:8000/ or http://drupal.docker.localhost:8000/ I just get `404 page not found`.

**Php**
```
$ docker-compose exec php ls -lah /var/www/html/
total 80
drwxr-xr-x    7 www-data www-data    4.0K Apr  1 18:52 .
drwxr-xr-x    4 www-data www-data    4.0K Mar  8 11:06 ..
-rw-r--r--    1 www-data www-data     948 Apr  1 18:51 .csslintrc
-rw-r--r--    1 www-data www-data     350 Apr  1 18:51 .editorconfig
-rw-r--r--    1 www-data www-data     185 Apr  1 18:51 .eslintignore
-rw-r--r--    1 www-data www-data      36 Apr  1 18:51 .eslintrc
-rw-r--r--    1 www-data www-data    3.6K Apr  1 18:51 .gitattributes
-rw-r--r--    1 www-data www-data    7.7K Apr  1 18:52 .htaccess
-rw-rw-rw-    1 www-data www-data     385 Apr  1 18:52 autoload.php
drwxr-xr-x   12 www-data www-data    4.0K Apr  1 18:51 core
-rw-r--r--    1 www-data www-data     549 Apr  1 18:52 index.php
drwxr-xr-x    3 www-data www-data    4.0K Apr  1 18:51 modules
drwxr-xr-x    3 www-data www-data    4.0K Apr  1 18:51 profiles
-rw-r--r--    1 www-data www-data    1.6K Apr  1 18:52 robots.txt
drwxr-xr-x    3 www-data www-data    4.0K Apr  1 18:51 sites
drwxr-xr-x    3 www-data www-data    4.0K Apr  1 18:51 themes
-rw-r--r--    1 www-data www-data     848 Apr  1 18:52 update.php
-rw-r--r--    1 www-data www-data    4.4K Apr  1 18:52 web.config
```

**Nginx**
```
$ docker-compose exec nginx ls -lah /var/www/html/
total 80
drwxr-xr-x    7 www-data www-data    4.0K Apr  1 18:52 .
drwxr-xr-x    3 root     root        4.0K Mar  8 11:22 ..
-rw-r--r--    1 www-data www-data     948 Apr  1 18:51 .csslintrc
-rw-r--r--    1 www-data www-data     350 Apr  1 18:51 .editorconfig
-rw-r--r--    1 www-data www-data     185 Apr  1 18:51 .eslintignore
-rw-r--r--    1 www-data www-data      36 Apr  1 18:51 .eslintrc
-rw-r--r--    1 www-data www-data    3.6K Apr  1 18:51 .gitattributes
-rw-r--r--    1 www-data www-data    7.7K Apr  1 18:52 .htaccess
-rw-rw-rw-    1 www-data www-data     385 Apr  1 18:52 autoload.php
drwxr-xr-x   12 www-data www-data    4.0K Apr  1 18:51 core
-rw-r--r--    1 www-data www-data     549 Apr  1 18:52 index.php
drwxr-xr-x    3 www-data www-data    4.0K Apr  1 18:51 modules
drwxr-xr-x    3 www-data www-data    4.0K Apr  1 18:51 profiles
-rw-r--r--    1 www-data www-data    1.6K Apr  1 18:52 robots.txt
drwxr-xr-x    3 www-data www-data    4.0K Apr  1 18:51 sites
drwxr-xr-x    3 www-data www-data    4.0K Apr  1 18:51 themes
-rw-r--r--    1 www-data www-data     848 Apr  1 18:52 update.php
-rw-r--r--    1 www-data www-data    4.4K Apr  1 18:52 web.config
```

**docker-compose file**
```
version: "2"

services:
  mariadb:
    image: wodby/mariadb:10.1-2.0.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
#    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci # The simple way to override the mariadb config.
    volumes:
#      - ./mariadb-init:/docker-entrypoint-initdb.d # Place init .sql file(s) here.
      - ./data:/var/lib/mysql # I want to manage volumes manually.

  php:
    image: wodby/drupal-php:7.0-2.0.0
#    image: wodby/drupal-php:7.1-2.0.0
#    image: wodby/drupal-php:5.6-2.0.0
#    image: wodby/drupal-php:5.3-2.0.0
    environment:
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
      # PHP_XDEBUG: 1
      # PHP_XDEBUG_DEFAULT_ENABLE: 1
      # PHP_XDEBUG_REMOTE_CONNECT_BACK: 0         # This is needed to respect remote.host setting bellow
      # PHP_XDEBUG_REMOTE_HOST: "10.254.254.254"  # You will also need to 'sudo ifconfig lo0 alias 10.254.254.254'
    volumes:
      - ./html:/var/www/html
#      - d4d-unison-sync:/var/www/html:rw # Replace volume to this to use docker-sync for macOS users

  nginx:
    image: wodby/drupal-nginx:8-1.10-2.0.0
#    image: wodby/drupal-nginx:7-1.10-2.0.0
#    image: wodby/drupal-nginx:6-1.10-2.0.0
    restart: unless-stopped
    depends_on:
      - php
    environment:
      NGINX_BACKEND_HOST: php
      NGINX_SERVER_ROOT: /var/www/html/
    volumes:
      - ./html:/var/www/html
#    labels:
#      - 'traefik.backend=nginx'
#      - 'traefik.port=80'
#      - 'traefik.frontend.rule=Host:drupal.docker.localhost'

#  varnish:
#    image: wodby/drupal-varnish:4.1-2.0.0
#    depends_on:
#      - nginx
#    environment:
#      VARNISH_SECRET: secret
#      VARNISH_BACKEND_HOST: nginx
#      VARNISH_BACKEND_PORT: 80
#    labels:
#      - 'traefik.backend=varnish'
#      - 'traefik.port=6081'
#      - 'traefik.frontend.rule=Host:varnish.drupal.docker.localhost'

#  redis:
#    image: wodby/redis:3.2-2.0.1

  pma:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mariadb
      PMA_USER: drupal
      PMA_PASSWORD: drupal
      PHP_UPLOAD_MAX_FILESIZE: 1G
      PHP_MAX_INPUT_VARS: 1G
    labels:
      - 'traefik.backend=pma'
      - 'traefik.port=80'
      - 'traefik.frontend.rule=Host:pma.drupal.docker.localhost'

#  solr:
#    image: wodby/drupal-solr:8-6.4-2.0.0
#    image: wodby/drupal-solr:8-6.3-2.0.0
#    image: wodby/drupal-solr:7-5.5-2.0.0
#    environment:
#      SOLR_HEAP: 1024m
#    labels:
#      - 'traefik.backend=solr'
#      - 'traefik.port=8983'
#      - 'traefik.frontend.rule=Host:solr.drupal.docker.localhost'

  mailhog:
    image: mailhog/mailhog
    labels:
      - 'traefik.backend=mailhog'
      - 'traefik.port=8025'
      - 'traefik.frontend.rule=Host:mailhog.drupal.docker.localhost'

#  node:
#    image: node:7-alpine
#    working_dir: /app
#    labels:
#      - 'traefik.backend=node'
#      - 'traefik.port=3000'
#      - 'traefik.frontend.rule=Host:front.drupal.docker.localhost'
#    expose:
#      - "3000"
#    volumes:
#      - ./path/to/your/single-page-app:/app
#    command: sh -c 'npm install && npm run start'

#  memcached:
#    image: memcached:1.4-alpine

#  traefik:
#    image: traefik
#    restart: unless-stopped
#    command: -c /dev/null --web --docker --logLevel=INFO
#    ports:
#      - '8000:80'
#      - '8080:8080'
#    volumes:
#      - /var/run/docker.sock:/var/run/docker.sock

# Docker-sync for macOS users
#volumes:
#  d4d-unison-sync:
#    external: true
```

Interesting, when I run `docker-compose ps` shows that traefik is running, even though it is commented out in the docker-compose file. 
```
$ docker-compose ps
        Name                      Command               State                      Ports                     
------------------------------------------------------------------------------------------------------------
opensocial_mailhog_1   MailHog                          Up      1025/tcp, 8025/tcp                           
opensocial_mariadb_1   docker-entrypoint.sh mysqld      Up      3306/tcp                                     
opensocial_nginx_1     /docker-entrypoint-drupal. ...   Up      80/tcp                                       
opensocial_php_1       /docker-entrypoint.sh php-fpm    Up      9000/tcp                                     
opensocial_pma_1       /run.sh phpmyadmin               Up      80/tcp                                       
opensocial_traefik_1   /traefik -c /dev/null --we ...   Up      0.0.0.0:8000->80/tcp, 0.0.0.0:8080->8080/tcp 
```
