### ISSUE TITLE
Failed installation to mounted codebase

### ISSUE THREAD

**Issue by johnreytanquinco** [wodby/docker4drupal#151]
UPDATED

- **Codebase: built-in vanilla Drupal or mounted codebase?**: mounted codebase
- **Drupal version**: 8.3.2
- **PHP service image with tag**: image: wodby/drupal-php:7.1-2.1.0
- **Host OS**: Ubuntu 17.04
- **Docker version**: 1.8.0

# **GOAL**
I am trying to use Drupal [OpenSocial template ](https://github.com/goalgorilla/open_social)on docker4drupal. I actually was able to successfully install OpenSocial in my localhost.

I followed each instruction and I have docker compose running in my machine.
```
        Name                      Command               State          Ports         
------------------------------------------------------------------------------------
opensocial_mailhog_1   MailHog                          Up      1025/tcp, 8025/tcp   
opensocial_mariadb_1   /docker-entrypoint.sh mysqld     Up      3306/tcp             
opensocial_nginx_1     /docker-entrypoint.sh nginx      Up      80/tcp               
opensocial_php_1       /docker-entrypoint.sh php-fpm    Up      9000/tcp             
opensocial_traefik_1   /traefik -c /dev/null --we ...   Up      0.0.0.0:8000->80/tcp
```

This is my docker-compose.yml file
```

version: "2"

services:
  mariadb:
    image: wodby/mariadb:10.1-2.1.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal

  php:
    image: wodby/drupal-php:7.1-2.1.0
    environment:
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
      DB_HOST: mariadb
      DB_USER: drupal
      DB_PASSWORD: drupal
      DB_NAME: drupal
      DB_DRIVER: mysql
    volumes:
      - ./:/var/www/html

  nginx:
    image: wodby/drupal-nginx:8-1.10-2.1.0
    depends_on:
      - php
    environment:
      NGINX_STATIC_CONTENT_OPEN_FILE_CACHE: "off"
      NGINX_ERROR_LOG_LEVEL: debug
      NGINX_BACKEND_HOST: php
      NGINX_SERVER_ROOT: /var/www/html
    volumes:
      - ./:/var/www/html
    labels:
      - 'traefik.backend=nginx'
      - 'traefik.port=80'
      - 'traefik.frontend.rule=Host:drupal.docker.localhost'

  mailhog:
    image: mailhog/mailhog
    labels:
      - 'traefik.backend=mailhog'
      - 'traefik.port=8025'
      - 'traefik.frontend.rule=Host:mailhog.drupal.docker.localhost'

  traefik:
    image: traefik
    command: -c /dev/null --web --docker --logLevel=INFO
    ports:
      - '8000:80'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  codebase:
```

### FIRST ATTEMPT (Using DRUSH as recommended and easiest way)
After I connect it to database using drush, I am getting this error message:
` Failed to create database: ERROR 2005 (HY000): Unknown MySQL server host 'mariadb' (11)       [error]`
This is my drush command:
`drush -v -y site-install social --db-url=mysql://drupal:drupal@mariadb/drupal --site-name=OpenSocial`

### SECOND ATTEMPT (Following step-by-step setup in the browser)
I did go through with the browser set up and I was actually able to connect to the database using the same credential and I am stuck with this error in installing the modules:
```
An AJAX HTTP error occurred.
HTTP Result Code: 200
Debugging information follows.
Path: /core/install.php?profile=social&langcode=en&id=2&op=do_nojs&op=do
StatusText: OK
ResponseText: Drupal\Component\Serialization\Exception\InvalidDataTypeException: yaml_parse(): end of stream reached without finding document 0 in Drupal\Component\Serialization\YamlPecl::errorHandler() (line 63 of /var/www/html/core/lib/Drupal/Component/Serialization/YamlPecl.php).
```
I opened up the error page link provided and this is what I am getting:
```
Additional uncaught exception thrown while handling exception.

Original

Drupal\Component\Serialization\Exception\InvalidDataTypeException: yaml_parse(): end of stream reached without finding document 0 in Drupal\Component\Serialization\YamlPecl::errorHandler() (line 63 of /var/www/html/core/lib/Drupal/Component/Serialization/YamlPecl.php).

Drupal\Component\Serialization\YamlPecl::errorHandler(2, 'yaml_parse(): end of stream reached without finding document 0', '/var/www/html/core/lib/Drupal/Component/Serialization/YamlPecl.php', 45, Array)
yaml_parse('#services:
#  grolesync.synchronizer:
#    class: 'Drupal\grolesync\GroupRoleSynchronizer'
#    arguments: ['@entity_type.manager']
', 0, 0, Array) (Line: 45)
Drupal\Component\Serialization\YamlPecl::decode('#services:
#  grolesync.synchronizer:
#    class: 'Drupal\grolesync\GroupRoleSynchronizer'
#    arguments: ['@entity_type.manager']
') (Line: 35)
Drupal\Component\Serialization\Yaml::decode('#services:
#  grolesync.synchronizer:
#    class: 'Drupal\grolesync\GroupRoleSynchronizer'
#    arguments: ['@entity_type.manager']
') (Line: 343)
Drupal\Core\DependencyInjection\YamlFileLoader->loadFile('modules/group/modules/grolesync/grolesync.services.yml') (Line: 63)
Drupal\Core\DependencyInjection\YamlFileLoader->load('modules/group/modules/grolesync/grolesync.services.yml') (Line: 1254)
Drupal\Core\DrupalKernel->compileContainer() (Line: 873)
Drupal\Core\DrupalKernel->initializeContainer() (Line: 18)
Drupal\Core\Installer\InstallerKernel->initializeContainer() (Line: 465)
Drupal\Core\DrupalKernel->boot() (Line: 414)
install_begin_request(Object, Array) (Line: 114)
install_drupal(Object) (Line: 44)
Additional

Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: You have requested a non-existent service "theme.manager". in Symfony\Component\DependencyInjection\ContainerBuilder->getDefinition() (line 824 of /var/www/html/vendor/symfony/dependency-injection/ContainerBuilder.php).

Symfony\Component\DependencyInjection\ContainerBuilder->getDefinition('theme.manager') (Line: 464)
Symfony\Component\DependencyInjection\ContainerBuilder->get('theme.manager') (Line: 674)
Drupal::theme() (Line: 22)
_drupal_maintenance_theme() (Line: 710)
drupal_maintenance_theme() (Line: 967)
install_display_output(Array, Array, Array) (Line: 264)
_drupal_log_error(Array, 1) (Line: 570)
```

I posted related issue in [Drupal community](https://www.drupal.org/node/2881371).

I really appreciate if someone can help me with this. TIA!
