### ISSUE TITLE
 failed to open stream: No such file or directory in /var/www/html/autoload.php

### ISSUE THREAD

**Issue by magick93** [wodby/docker4drupal#152]
Im trying to run OpenSocial, a Drupal profile.

**Stack**:

When viewing http://drupal.docker.localhost:8000/  then I see
```


Warning: require(/var/www/html/../vendor/autoload.php): failed to open stream: No such file or directory in /var/www/html/autoload.php on line 17

Fatal error: require(): Failed opening required '/var/www/html/../vendor/autoload.php' (include_path='.:/usr/local/lib/php') in /var/www/html/autoload.php on line 17
```

- **Codebase: built-in vanilla Drupal or mounted codebase?**:  Mounted codebase
- **Drupal version**:  8.3x
- **PHP service image with tag**: 
- **Host OS**: Ubuntu 17.4
- **Docker version**: Docker version 17.04.0-ce, build 4845c56

```
version: "2"

services:
  mariadb:
    image: wodby/mariadb:10.1-2.1.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal


  php:

    image: wodby/drupal-php:7.1-2.1.0

    environment:
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
      DB_HOST: mariadb
      DB_USER: drupal
      DB_PASSWORD: drupal
      DB_NAME: drupal
      DB_DRIVER: mysql
    volumes:
      - ./opensocial/html:/var/www/html

  nginx:
    image: wodby/drupal-nginx:8-1.10-2.1.0
    depends_on:
      - php
    environment:
      NGINX_STATIC_CONTENT_OPEN_FILE_CACHE: "off"
      NGINX_ERROR_LOG_LEVEL: debug
      NGINX_BACKEND_HOST: php
      NGINX_SERVER_ROOT: /var/www/html
    volumes:
      - ./opensocial/html:/var/www/html
    labels:
      - 'traefik.backend=nginx'
      - 'traefik.port=80'
      - 'traefik.frontend.rule=Host:drupal.docker.localhost'



  mailhog:
    image: mailhog/mailhog
    labels:
      - 'traefik.backend=mailhog'
      - 'traefik.port=8025'
      - 'traefik.frontend.rule=Host:mailhog.drupal.docker.localhost'



  traefik:
    image: traefik
    command: -c /dev/null --web --docker --logLevel=INFO
    ports:
      - '8000:80'
#      - '8080:8080' # Dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock


volumes:
  codebase:

```
