### ISSUE TITLE
Stuck at docker-sync start on Mac OSX

### ISSUE THREAD

**Issue by jgardezi** [wodby/docker4drupal#153]
**Stack**: 
Cloned the repository on macOS Sierra and followed the following instructions on the page http://docs.docker4drupal.org/en/latest/macos/. Installed `gem install docker-sync` and version its is installed `docker-sync -v`: `0.4.6`. Issued the following command

`
docker-sync start --daemon

Please do no longer use "dest" in your docker-sync.yml configuration - also see https://github.com/EugenMayer/docker-sync/wiki/1.2-Upgrade-Guide#dest-has-been-removed!
`

- **Codebase: built-in vanilla Drupal or mounted codebase?**: 
- **Drupal version**: 8.x
- **PHP service image with tag**: wodby/drupal:8-7.1-2.1.2
- **Host OS**: macOS Sierra
- **Docker version**: Version 1.13.1
- **Logs output**: 

`Please do no longer use "dest" in your docker-sync.yml configuration - also see https://github.com/EugenMayer/docker-sync/wiki/1.2-Upgrade-Guide#dest-has-been-removed!` 

I have little experience with  `docker-sync` it seems like there is an issue with it and little documents to work with it.

Kind regards,
Javed Gardezi

**Comment by artemboyko43** [comment]
I am not sure about this, but I fixed it by this

https://github.com/wodby/docker4drupal/pull/155/commits/95188c9a4a45b7f25de43d413cccc826ded88e13

**Comment by jgardezi** [comment]
@artemboyko43 I will give it a go and post my feedback here.

**Comment by jgardezi** [comment]
Hi, 

I was able to solve the problem of `docker-sync start -d`. When I did `docker-sync log` the log showed me was
`
          ok  Starting native_osx for sync docker-sync-unison
          ok  docker-sync-unison container still running, restarting unison in container
     success  Sync container started
     success  Showing unison logs from your sync container: docker-sync-unison
`

However, I am running into another problem when I issue the command `docker-compose up -d`, the following error shows up
`
ERROR: Named volume "docker-sync-unison:/var/www/html:rw" is used in service "php" but no declaration was found in the volumes section.
`

My Docker `docker-compose.yml` looks like 

```
version: "2"

services:
  mariadb:
    image: wodby/mariadb:10.1-2.1.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal

  php:
    image: wodby/drupal-php:5.6-2.1.0
    environment:
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
      DB_HOST: mariadb
      DB_USER: drupal
      DB_PASSWORD: drupal
      DB_NAME: drupal
      DB_DRIVER: mysql
      # PHP_XDEBUG: 1
      # PHP_XDEBUG_DEFAULT_ENABLE: 1
      # PHP_XDEBUG_REMOTE_CONNECT_BACK: 0         # This is needed to respect remote.host setting bellow
      # PHP_XDEBUG_REMOTE_HOST: "10.254.254.254"  # You will also need to 'sudo ifconfig lo0 alias 10.254.254.254'
    volumes:
      - docker-sync-unison:/var/www/html # Docker-sync for macOS users

  nginx:
    image: wodby/drupal-nginx:7-1.10-2.1.0]
    depends_on:
      - php
    environment:
      NGINX_STATIC_CONTENT_OPEN_FILE_CACHE: "off"
      NGINX_ERROR_LOG_LEVEL: debug
      NGINX_BACKEND_HOST: php
      NGINX_SERVER_ROOT: /var/www/html/web
    volumes:
      - docker-sync-unison:/var/www/html # Docker-sync for macOS users
    labels:
      - 'traefik.backend=nginx'
      - 'traefik.port=80'
      - 'traefik.frontend.rule=Host:anrows.docker.localhost'

  varnish:
    image: wodby/drupal-varnish:4.1-2.1.0
    depends_on:
      - nginx
    environment:
      VARNISH_SECRET: secret
      VARNISH_BACKEND_HOST: nginx
      VARNISH_BACKEND_PORT: 80
    labels:
      - 'traefik.backend=varnish'
      - 'traefik.port=6081'
      - 'traefik.frontend.rule=Host:varnish.anrows.docker.localhost'

  redis:
    image: wodby/redis:3.2-2.1.0

  pma:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mariadb
      PMA_USER: drupal
      PMA_PASSWORD: drupal
      PHP_UPLOAD_MAX_FILESIZE: 1G
      PHP_MAX_INPUT_VARS: 1G
    labels:
      - 'traefik.backend=pma'
      - 'traefik.port=80'
      - 'traefik.frontend.rule=Host:pma.drupal.docker.localhost'

  mailhog:
    image: mailhog/mailhog
    labels:
      - 'traefik.backend=mailhog'
      - 'traefik.port=8025'
      - 'traefik.frontend.rule=Host:mailhog.drupal.docker.localhost'

  traefik:
    image: traefik
    command: -c /dev/null --web --docker --logLevel=INFO
    ports:
      - '8000:80'
#      - '8080:8080' # Dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

# Docker-sync for macOS users
volumes:
  docker-sync-unison:
    external: true

volumes:
  codebase:

```

I have no idea why this is happening.

**Comment by csandanov** [comment]
You have two global declarations of volumes, so the last one overrides the previous with docker-sync-unison definition. 

So it seems docker-sync now uses new strategy native_osx, we should update the naming. And we should remove deprecated dest.

**Comment by csandanov** [comment]
I've cleaned up docker-sync related stuff https://github.com/wodby/docker4drupal/commit/47ead8cc24c8c6e252af096e43e0174447b81649

**Comment by broniusfatv** [comment]
For anyone seeing this for the first time, the fix for me was to uncomment the commented-by-default, global `volumes` declaration at the bottom:
```
volumes:
# Docker-sync for macOS users
  docker-sync:
    external: true
# For Xdebug profiler
  files:
```
The whole block was commented out.  Once uncommented it worked great! :)
- n00b
