### ISSUE TITLE
One docroot, multiple domains - is this possible?

### ISSUE THREAD

**Issue by johnennewdeeson** [wodby/docker4drupal#157]
Hello,

Is it possible to add additional traefik rules to allow several Host domains to be routed to the same project? 

I want to be able to setup site1.docker.localhost and site2.docker.localhost and for both to use the same codebase and same database.

Looking at how nginx image works, it would work as long both domains were routed to the same nginx container. 

I guess I can do it by setting up a separate traefik.yml file and running two docker commands, but it would be nice if I could something like this in the docker-compose.yml file:

```
  nginx:
    image: wodby/drupal-nginx:7-1.10-2.1.0
    depends_on:
      - php
    environment:
      NGINX_STATIC_CONTENT_OPEN_FILE_CACHE: "off"
      NGINX_ERROR_LOG_LEVEL: debug
      NGINX_BACKEND_HOST: php
      NGINX_SERVER_ROOT: /var/www/html/docroot
    volumes:
       - .:/var/www/html
    labels:
      - 'traefik.backend=nginx'
      - 'traefik.port=80'
      - 'traefik.frontend.rule=site1.docker.localhost'
      - 'traefik.frontend.rule=site2.docker.localhost' # specifying additional traefik rules to allow multiple hosts
```

**Comment by johnennewdeeson** [comment]
Ah, apparently you can with HostRegexp in the frontend rule like this...

```
nginx:
    image: wodby/drupal-nginx:7-1.10-2.1.0
    depends_on:
      - php
    environment:
      NGINX_STATIC_CONTENT_OPEN_FILE_CACHE: "off"
      NGINX_ERROR_LOG_LEVEL: debug
      NGINX_BACKEND_HOST: php
      NGINX_SERVER_ROOT: /var/www/html/docroot
    volumes:
       - .:/var/www/html
    labels:
      - 'traefik.backend=nginx'
      - 'traefik.port=80'
      - 'traefik.frontend.rule=HostRegexp:{subdomain:[A-Za-z0-9-]+}.docker.localhost'
```

Ref: https://docs.traefik.io/basics/
