### ISSUE TITLE
Private files don't work

### ISSUE THREAD

**Issue by karens** [wodby/docker4drupal#161]
I have been trying to use Docker4Drupal for a Drupal 8 site that uses private files. Everything else works fine but I can find no way that the private files are visible in the browser. 

The files are created and exist in the file directory. They are visible in the terminal window when doing `ls -la`. They are not visible in the browser when viewing or editing the article.

It is probably permissions, but I followed the instructions at http://docs.docker4drupal.org/en/latest/permissions/ before building these containers.

I started by trying to set up an existing codebase, then dropped back to just trying to create a vanilla Drupal 8 installation and configure it to use private files, and no matter what I tried the private files were not visible in the browser. I even tried again leaving out docker-sync with a vanilla install to see what happened. Without docker-sync running the vanilla site was created with no private file path at all. I added the private file path in the terminal, cleared the cache, and tried to create private files, and it behaved the same way as all my other attempts.

Most basic steps to reproduce:
- Create an empty directory just populated with docker-compose.yml and docker-sync.yml straight out of docker4drupal (docker-composer is replicated below)
- Run `docker-sync start` and then `docker-compose up` and wait for the build
- Enter the php container and create a site using `drush si`
- Go to `http://drupal.docker.localhost:8000` in the browser, log in as admin.
- Go to config/media/file-system and select the option for the default file download method to be private
- In the image fields on articles configuration page change the file storage method to private
- Create a new article and try to add an image to it.

Drupal: 8
Browser: Tried both Safari and Firefox
Docker for Mac version: 17.03.1
docker-compose file:

```
version: "2"

services:
  mariadb:
    image: wodby/mariadb:10.1-2.1.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
  php:
    image: wodby/drupal:8-7.1-2.1.2
    environment:
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
      DB_HOST: mariadb
      DB_USER: drupal
      DB_PASSWORD: drupal
      DB_NAME: drupal
      DB_DRIVER: mysql
    volumes:
      - docker-sync:/var/www/html # Docker-sync for macOS users
  nginx:
    image: wodby/drupal-nginx:8-1.10-2.1.0
    depends_on:
      - php
    environment:
      NGINX_STATIC_CONTENT_OPEN_FILE_CACHE: "off"
      NGINX_ERROR_LOG_LEVEL: debug
      NGINX_BACKEND_HOST: php
      NGINX_SERVER_ROOT: /var/www/html/web
    volumes:
      - docker-sync:/var/www/html # Docker-sync for macOS users
    labels:
      - 'traefik.backend=nginx'
      - 'traefik.port=80'
      - 'traefik.frontend.rule=Host:drupal.docker.localhost'
  mailhog:
    image: mailhog/mailhog
    labels:
      - 'traefik.backend=mailhog'
      - 'traefik.port=8025'
      - 'traefik.frontend.rule=Host:mailhog.drupal.docker.localhost'
  traefik:
    image: traefik
    command: -c /dev/null --web --docker --logLevel=INFO
    ports:
      - '8000:80'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
volumes:
  codebase:
## Docker-sync for macOS users
  docker-sync:
    external: true
```
