### ISSUE TITLE
Adding private key to authenticate to git, bitbucket, etc.

### ISSUE THREAD

**Issue by Vacilando** [wodby/docker4drupal#162]
Added my private key to the php container (see below) so as to be able to authenticate to git (github, bitbucket) and other systems.

```
  php:
    image: wodby/drupal-php:5.6-2.1.0
    environment:
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
      DB_HOST: mariadb
      DB_USER: drupal
      DB_PASSWORD: drupal
      DB_NAME: drupal
      DB_DRIVER: mysql
      SSH_PRIVATE_KEY: |-
        -----BEGIN RSA PRIVATE KEY-----
        MYPRIVATEKEY
        -----END RSA PRIVATE KEY-----
    volumes:
      - ./:/var/www/html
```

However, I am constantly getting the permission denied (publickey):
```
2bf27599a3c6:/var/www/html/tmp$ git clone git@bitbucket.org:mygroup/myrepo.git
Cloning into 'myrepo'...
Permission denied (publickey).
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
```

That was a test via the php container itself (drupal-compose exec ...)

When I add the private key to the sshd container and log in via ssh I get the same response.

The public key on the remote site is definitely OK and the repository does exist (tried with bitbucket as well as with github).
