### ISSUE TITLE
Limit RAM on containers

### ISSUE THREAD

**Issue by arrubiu** [wodby/docker4drupal#163]
I'm using docker-compose 1.8.1 on a ubuntu host.
I'v only 8 giga of RAM on my pc.
Is there a way to limit ram for containers?

I tried this but it doesn't work: 
```
  mariadb:
    image: wodby/mariadb:10.1-2.0.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
      mem_limit: 256MiB
```
Using htop the system teels me that mysqld uses 516M (I've not a mysql server on my host).
"docker stats" tells me 615MiB of ram

thanks
