### ISSUE TITLE
Adding Portainer

### ISSUE THREAD

**Issue by igorbiki** [wodby/docker4drupal#164]
I've been adding Portainer to all my docker-compose files. It's a UI that looks nice and gives you easy access to logs, bash/sh etc. 
```
portainer:
    image: portainer/portainer
    command: --no-auth
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "5000:9000"
```
You could add traefik, since in current form it is using port 5000 (to avoid conflicts on port 9000). Just adding code above and restarting is all it takes. And in my case just visit localhost:5000 and that's it. You can filter all containers, check logs for images. 

Btw this docker4drupal is awesome!
