### ISSUE TITLE
After restarting docker drupal db destroys itself

### ISSUE THREAD

**Issue by ovidijusr** [wodby/docker4drupal#165]
For some reason after i docker-compose down and up, whole database gones and I need to turn it on again.

My docker file:
```
version: "2"

services:
  mariadb:
    image: wodby/mariadb:10.1-2.1.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
   - ./docker-runtime/mariadb-init:/docker-entrypoint-initdb.d # Place init .sql file(s) here.

  php:
    image: wodby/drupal:8-7.0-2.1.2
    environment:
      DB_DRIVER: mysql
      DB_HOST: mariadb
      DB_NAME: drupal
      DB_PASSWORD: drupal
      DB_USER: drupal
      PHP_SITE_NAME: "docker-dev"
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
      PHP_XDEBUG_ENABLED: 1 # Set 1 to enable.
    volumes:
      - ./:/var/www/html

  nginx:
    image: wodby/drupal-nginx:8-1.10-2.1.0
    environment:
      NGINX_STATIC_CONTENT_OPEN_FILE_CACHE: "off"
      NGINX_ERROR_LOG_LEVEL: debug
      NGINX_BACKEND_HOST: php
      NGINX_SERVER_ROOT: /var/www/html/drupal
    depends_on:
      - php
    volumes:
    - ./:/var/www/html
    labels:
      - 'traefik.backend=nginx'
      - 'traefik.port=80'
      - 'traefik.frontend.rule=Host:localhost'

  pma:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST:  mariadb
      PMA_USER: drupal
      PMA_PASSWORD: drupal
      PHP_UPLOAD_MAX_FILESIZE: 3G
      PHP_MAX_INPUT_VARS: 3G
    labels:
      - 'traefik.backend=pma'
      - 'traefik.port=80'
      - 'traefik.frontend.rule=Host:pma.drupal.docker.localhost'

  traefik:
    image: traefik
    command: -c /dev/null --web --docker --logLevel=INFO
    ports:
      - '8000:80'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
```
