### ISSUE TITLE
Simpletest not working on drupal

### ISSUE THREAD

**Issue by daliborstojakovic** [wodby/docker4drupal#168]
I'm using config below

if I run simpletest in drupal i'm getting that base url is not found which is nginx in this case is not found.
I've tries also with domain configured from traefik and same issue

```
php:
    image: wodby/drupal-php:7.0-2.4.2

    environment:
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
      DB_HOST: mariadb
      DB_USER: admin
      DB_PASSWORD: admin
      DB_NAME: somedatabase
      DB_DRIVER: mysql
      PHP_XDEBUG: 1
      PHP_XDEBUG_DEFAULT_ENABLE: 1
      SIMPLETEST_BASE_URL: http://nginx/
      SIMPLETEST_DB: mysql://admin:admin@mariadb/database
    volumes:
      - ./:/var/www/html
    depends_on:
      - mariadb

nginx:
    image: wodby/drupal-nginx:8-1.13-2.4.0
    depends_on:
      - php
    environment:
      NGINX_STATIC_CONTENT_OPEN_FILE_CACHE: "off"
      NGINX_ERROR_LOG_LEVEL: debug
      NGINX_BACKEND_HOST: php
      NGINX_SERVER_ROOT: /var/www/html/web
    volumes:
      - ./:/var/www/html
    labels:
      - 'traefik.backend=nginx'
      - 'traefik.port=80'
      - 'traefik.frontend.rule=Host:somedomain.docker.localhost'
```
