### ISSUE TITLE
Dynamically created Traefik yml file to work with multiple projects

### ISSUE THREAD

**Issue by jaybeaton** [wodby/docker4drupal#182]
On your "Running Multiple Projects with Træfik" page, it talks about setting up Traefik to work with multiple projects:

https://docker4drupal.readthedocs.io/en/latest/multiple-projects/

One of the things it says you need to do is to add a couple lines for each network that's created.  I created a helper script that looks at all existing Docker networks, adds them to a dynamically-created yml file, then runs docker-compose on that file:

https://github.com/jaybeaton/traefik-helper

With this, you never need to manually edit the traefik yml file.  If you add a new docker-compose.yml with a new network, you just need to use traefik-helper.sh to stop traefik and start it back up again.

I haven't been using Docker for long, but it's been working for me.  Other people may find this useful.

**Comment by thegreenbot** [comment]
Thanks Jay, this is great. I've been avoiding this by using only one project-specific instance of traefik at a time, but there are times where I want multiple active projects at once. Good stuff.

**Comment by michaelpporter** [comment]
@jaybeaton take a look at Robo.il I made a command that will add/remove from traefik.yml. 

https://github.com/consolidation/Robo/issues/610

**Comment by csandanov** [comment]
Thanks for sharing.

**Comment by michaelpporter** [comment]
I found a better way, no need to add networks as you go. This method allows you to start and stop projects and not have to restart traefik all the time. You do have to keep traefik running.

Here is my docker-compose.yml from ~/Sites/traefik. it allows for HTTP/HTTPS connections and will listen for new connections.

```yaml
version: '2'
services:
    traefik:
        image: traefik
        restart: unless-stopped
        command: '-c /dev/null --web --docker --logLevel=DEBUG --defaultEntryPoints=''http'',''https'' --entryPoints="Name:https Address::443 TLS:/certs/traefik.cert,/certs/traefik.key" --entryPoints="Name:http Address::80"'
        networks:
            - webgateway
        ports:
            - '80:80'
            - '443:443'
            - '8080:8080'
        volumes:
            - '/var/run/docker.sock:/var/run/docker.sock'
            - './certs:/certs'
    portainer:
        image: portainer/portainer
        restart: unless-stopped
        networks:
            - webgateway
        command: '--no-auth'
        volumes:
            - '/var/run/docker.sock:/var/run/docker.sock'
        labels:
            - traefik.backend=portainer
            - traefik.port=9000
            - 'traefik.frontend.rule=Host:portainer.docker.localhost'
networks:
    webgateway:
        driver: bridge
```

Then in each project I have added networks:

```yaml
version: "2"

services:
  mariadb:
    image: wodby/mariadb:10.1-2.3.3
    networks:
      - web
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  php:
    image: wodby/wordpress-php:7.0-2.2.0
    networks:
      - web
    environment:
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
      PHP_OUTPUT_BUFFERING: 'On'
      PHP_OUTPUT_HANDLER: mb_output_handler
      PHP_XDEBUG: 0
      PHP_XDEBUG_DEFAULT_ENABLE: 1
      PHP_XDEBUG_REMOTE_CONNECT_BACK: 0         # This is needed to respect remote.host setting bellow
      PHP_XDEBUG_REMOTE_HOST: "10.254.254.254"  # You will also need to 'sudo ifconfig lo0 alias 10.254.254.254'
    volumes:
      - project-sync:/var/www/html:nocopy # Docker-sync


  apache:
    image: wodby/wordpress-apache:2.4-1.0.0
    networks:
      - web
    depends_on:
      - php
    environment:
      APACHE_LOG_LEVEL: debug
      APACHE_BACKEND_HOST: php
      APACHE_SERVER_ROOT: /var/www/html/www
      HOME: /var/www/html/www
    volumes:
      - project-sync:/var/www/html:nocopy # Docker-sync
    labels:
      - 'traefik.backend=semitrailers_apache_1'
      - 'traefik.entrypoint=http'
      - 'traefik.enable=true'
      - 'traefik.port=80'
      - 'traefik.frontend.rule=Host:project.docker.localhost'

  mailhog:
    image: mailhog/mailhog
    networks:
      - web
    labels:
      - 'traefik.backend=semitrailers_mailhog_1'
      - 'traefik.port=8025'
      - 'traefik.frontend.rule=Host:mailhog.project.docker.localhost'

networks:
  web:
    external:
      name: traefik_webgateway

volumes:
  project-sync:
    external: true

```



```yaml
version: "2"


services:
  postgres:
    image: postgres:9.6.5
    networks:
      - web
    environment:
      POSTGRES_USER: chf
      POSTGRES_PASSWORD: chf
      POSTGRES_DB: chf
    volumes:
      - ./postgres-init:/docker-entrypoint-initdb.d # Place init .sql file(s) here.

  php:
    image: wodby/drupal-php:7.0-2.4.9
    networks:
      - web
    environment:
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
      PHP_XDEBUG: 1
      PHP_XDEBUG_IDEKEY: PHPSTORM
      PHP_XDEBUG_DEFAULT_ENABLE: 1
      PHP_XDEBUG_REMOTE_AUTOSTART: 1
      PHP_XDEBUG_REMOTE_CONNECT_BACK: 0         # This is needed to respect remote.host setting bellow
      PHP_XDEBUG_REMOTE_HOST: "docker.for.mac.localhost"  # You will also need to 'sudo ifconfig lo0 alias 10.254.254.254'
    volumes:
     - chf-sync:/var/www/html:nocopy # Docker-sync for macOS users

  apache:
    image: wodby/drupal-apache:2.4
    networks:
      - web
    depends_on:
      - php
    environment:
      APACHE_LOG_LEVEL: debug
      APACHE_BACKEND_HOST: php
      APACHE_SERVER_ROOT: /var/www/html/webroot
    volumes:
     - chf-sync:/var/www/html:nocopy # Docker-sync for macOS users
    labels:
      - 'traefik.backend=chf_apache_1'
      - 'traefik.port=80'
      - 'traefik.frontend.rule=Host:chf.docker.localhost'

  mailhog:
    image: mailhog/mailhog
    networks:
      - web
    labels:
      - 'traefik.backend=chf_mailhog_1'
      - 'traefik.port=8025'
      - 'traefik.frontend.rule=Host:mailhog.chf.docker.localhost'

  adminer:
    image: dockette/adminer:pgsql
    networks:
      - web
    labels:
      - 'traefik.backend=chf_adminer_1'
      - 'traefik.port=80'
      - 'traefik.frontend.rule=Host:adminer.chf.docker.localhost'

networks:
  web:
    external:
      name: traefik_webgateway

volumes:
  chf-sync:
   external: true
```
