### ISSUE TITLE
Adding new services?

### ISSUE THREAD

**Issue by kevinquillen** [wodby/docker4drupal#186]
If I wanted to add a new service, in this case [GoAccess](https://goaccess.io), how is that done?

In the compose file, I added:

```
goaccess:
    image: allinurl/goaccess
    labels:
      - 'traefik.backend=goaccess'
      - 'traefik.port=7890'
      - 'traefik.frontend.rule=Host:goaccess.drupal.docker.localhost'
```

I checked in Portainer, and the container was not started. I started the container, and could not access it at that address in the browser.
