### ISSUE TITLE
Unable to add portainer to traefik.yml

### ISSUE THREAD

**Issue by irmantasp** [wodby/docker4drupal#187]
Hi, I am trying to add portainer to traefik.yml and access all containers from there since every instance points to same socket _/var/run/docker.sock_. 
I am not able to access portainer from traefik.yml
### Codebase
Mounted codebase
  
### Host OS 
Ubuntu 14.04 LTS
### Docker info output
```
➜  Work  docker info
Containers: 171
 Running: 10
 Paused: 0
 Stopped: 161
Images: 39
Server Version: 17.05.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 697
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9048e5e50717ea4497b757314bad98ea3763c145
runc version: 9c2d8d184e5da67c95d601382adf14862e4f2228
init version: 949e6fa
Security Options:
 apparmor
Kernel Version: 4.4.0-96-generic
Operating System: Ubuntu 14.04.5 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.711GiB
Name: irmantas-Lenovo-Y50-70
ID: EUHQ:ZIMB:TV7C:IQ7R:2OLS:JIOL:UKKS:XXYI:WIUB:4SAJ:RNPZ:TBG4
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support

```

#### traefik.yml
```yml
version: '2'

services:
  work_traefik:
    image: traefik
    restart: unless-stopped
    command: -c /dev/null --web --docker --logLevel=DEBUG
    networks:
      - codebase1
      - codebase2
    ports:
      - '80:80'
      - '8080:8080'
      - '3306:3306'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  work_portainer:
    image: portainer/portainer
    command: --no-auth
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - 'traefik.backend=work_portainer'
      - 'traefik.port=9000'
      - 'traefik.frontend.rule=Host:portainer.docker.localhost'

networks:
  codebase1:
    external:
      name: codebase_default
  codebase2:
    external:
      name: codebase02_default
```

#### docker network inspect work_default
```
➜  Work  docker network inspect work_default
[
    {
        "Name": "work_default",
        "Id": "b194f594d22226f248d5c7794d42a7645cf1b74c07dd64cf85999981b145bfbb",
        "Created": "2017-09-21T15:58:12.928118959+03:00",
        "Scope": "local",
        "Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "172.18.0.0/16",
                    "Gateway": "172.18.0.1"
                }
            ]
        },
        "Internal": false,
        "Attachable": false,
        "Ingress": false,
        "Containers": {
            "42418698e88e1230a5d6c06d70b85d1f16584a8a96e39445c855211e8249b341": {
                "Name": "work_work_portainer_1",
                "EndpointID": "fc5badd01a7052c2ce6ae09ec34798843d5bcd25180e1dcc821ae10e26b909c3",
                "MacAddress": "02:42:ac:12:00:02",
                "IPv4Address": "172.18.0.2/16",
                "IPv6Address": ""
            }
        },
        "Options": {},
        "Labels": {}
    }
]
```
#### docker-compose logs -f
```
work_traefik_1    | time="2017-09-21T13:33:07Z" level=warning msg="Error forwarding to http://172.18.0.2:9000, err: dial tcp 172.18.0.2:9000: i/o timeout" 
```
