### ISSUE TITLE
XDebug not working in Atom on Windows 10

### ISSUE THREAD

**Issue by BrizzleRocker** [wodby/docker4drupal#193]
### Codebase
Mounted code base

### Host OS 
Windows 10 Pro - Version 1703

### Docker info output
```
Containers: 29
 Running: 6
 Paused: 0
 Stopped: 23
Images: 16
Server Version: 17.09.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 3f2f8b84a77f73d38244dd690525642a72156c64
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.49-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 3.837GiB
Name: moby
ID: UXL7:5CJZ:4HR2:L3J6:F6QV:EA3Z:6EM3:APPF:CAYW:AFRX:5DCD:5AY7
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 66
 Goroutines: 66
 System Time: 2017-10-09T09:00:38.9153497Z
 EventsListeners: 1
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

### Docker compose file
```yml
version: "2"

services:
  mariadb:
    image: wodby/mariadb:10.1-2.3.3
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: drupal_novation
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
    volumes:
      - ./mariadb-init:/docker-entrypoint-initdb.d # Place init .sql file(s) here.
#      - /path/to/mariadb/data/on/host:/var/lib/mysql # I want to manage volumes manually.

  php:
# 1. Images with vanilla Drupal – wodby/drupal:[DRUPAL_VERSION]-[PHP_VERSION]-[STABILITY_TAG].
#    image: wodby/drupal:8-7.1-2.4.4
#    image: wodby/drupal:8-7.0-2.4.4
#    image: wodby/drupal:7-7.1-2.4.4
#    image: wodby/drupal:7-7.0-2.4.4
#    image: wodby/drupal:7-5.6-2.4.4
#    image: wodby/drupal:6-5.6-2.4.4
#    image: wodby/drupal:6-5.3-2.4.4
# 2. Images without Drupal – wodby/drupal-php:[PHP_VERSION]-[STABILITY_TAG].
#    image: wodby/drupal-php:7.1-2.4.3
#    image: wodby/drupal-php:7.0-2.4.3
    image: wodby/drupal-php:5.6-2.4.3
#    image: wodby/drupal-php:5.3-2.4.3

    environment:
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
      DB_HOST: mariadb
      DB_USER: drupal
      DB_PASSWORD: drupal
      DB_NAME: drupal_novation
      DB_DRIVER: mysql
      PHP_XDEBUG: 1
      PHP_XDEBUG_DEFAULT_ENABLE: 1
      PHP_XDEBUG_REMOTE_CONNECT_BACK: 0         # This is needed to respect remote.host setting below
      PHP_XDEBUG_REMOTE_HOST: "10.0.75.1"  # You will also need to 'sudo ifconfig lo0 alias 10.254.254.254'
      PHP_XDEBUG_IDEKEY: "xdebug.atom" # specific to me, change to your own IDE key
    volumes:
#      - codebase:/var/www/html
      - ./:/var/www/html # Local codebase
# Options for macOS users (https://docker4drupal.readthedocs.io/en/latest/macos)
#      - codebase:/var/www/html:cached # User-guided caching
#      - docker-sync:/var/www/html # Docker-sync

#  nginx: - disabled

  apache:
    image: wodby/drupal-apache:2.4-1.0.2
    depends_on:
      - php
    environment:
      APACHE_LOG_LEVEL: debug
      APACHE_BACKEND_HOST: php
      APACHE_SERVER_ROOT: /var/www/html
    volumes:
#      - codebase:/var/www/html
       - ./:/var/www/html # Local codebase
## Options for macOS users (https://docker4drupal.readthedocs.io/en/latest/macos)
##      - codebase:/var/www/html:cached # User-guided caching
##      - docker-sync:/var/www/html # Docker-sync
    labels:
      - 'traefik.backend=apache'
      - 'traefik.port=80'
      - 'traefik.frontend.rule=Host:novation.docker.localhost'

#  varnish: - disabled
#  redis:  - disabled
  # adminer:  - disabled - thought this might be conflicting on port 9000
#  pma: - disabled
#  solr:  - disabled

  mailhog:
    image: mailhog/mailhog
    labels:
      - 'traefik.backend=mailhog'
      - 'traefik.port=8025'
      - 'traefik.frontend.rule=Host:mailhog.novation.docker.localhost'

#  nodejs: - disabled
#  node:  - disabled

  memcached:
    image: wodby/memcached:1.4-2.0.0

#  rsyslog: - disabled
#  athenapdf: - disabled
  # portainer: - disabled

  traefik:
    image: traefik
    command: -c /dev/null --web --docker --logLevel=INFO
    ports:
      - '80:80'
      - '8080:8080' # Dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  codebase:
## Docker-sync for macOS users
#  docker-sync:
#    external: true

```
I've tried setting Atom to various hosts 127.0.0.1, localhost, *, 10.0.75.1 etc but cannot get it to pick up debug information, it just sits there listening. I'm using Chrome with the Xdebug Helper extension.

Firewall checked as per https://github.com/wodby/docker4drupal/issues/192 (although mine is disabled for my home network).
