### ISSUE TITLE
Sometimes the php container crashes: "zend_mm_heap corrupted"

### ISSUE THREAD

**Issue by cbeier** [wodby/docker4drupal#197]
### Codebase
I use the "wodby/drupal-php:7.0-2.4.3" docker image for the php container.

The problem occurs after a update of the codebase and some drush commands (drush cim, drush cr). Often after a `drush cr` inside the php container.

The php container is always running (even with the problem) and does not exist with exit code. To get the drupal installation up again is to restart the php container (`docker-compose restart php`).
  
### Host OS 
Docker Host: Mac OS X Sierra with Docker4Mac
Docker Host: Ubuntu Linux with Docker

The problem occurs on both hosts.

The other information refers to the Linux host

### Docker info output
```
Containers: 11
 Running: 11
 Paused: 0
 Stopped: 0
Images: 7
Server Version: 17.09.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 06b9cb35161009dcb7123345749fef02f7cea8e0
runc version: 3f2f8b84a77f73d38244dd690525642a72156c64
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.4.27-x86_64-jb1
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.818GiB
Name: xxx
ID: KTKS:GTLY:RQ3O:KGFC:W2OX:JUX6:ZS2K:IJB2:JR5D:PUVM:FNHG:OVIP
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

### Docker compose file
```yml
# The php container section:

  php:
    # 2. Images without Drupal – wodby/drupal-php:[PHP_VERSION]-[STABILITY_TAG].
    image: wodby/drupal-php:7.0-2.4.3
    environment:
      # PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
      DB_HOST: mariadb
      DB_USER: drupal
      DB_PASSWORD: drupal
      DB_NAME: drupal
      DB_DRIVER: mysql
      # PHP_XDEBUG: 1
      # PHP_XDEBUG_DEFAULT_ENABLE: 1
      # PHP_XDEBUG_REMOTE_CONNECT_BACK: 0         # This is needed to respect remote.host setting below
      # PHP_XDEBUG_REMOTE_HOST: "10.254.254.254"  # You will also need to 'sudo ifconfig lo0 alias 10.254.254.254'
    volumes:
      - ../src/:/var/www/html
      - ../data/ssh-key:/home/www-data/.ssh
      - ../data/ssh-key:/root/.ssh
      # Options for macOS users (https://docker4drupal.readthedocs.io/en/latest/macos)
      #   - codebase:/var/www/html:cached # User-guided caching
      #   - docker-sync:/var/www/html # Docker-sync
```

### Logs output
```
php_1      | [17-Oct-2017 09:02:24] WARNING: [pool www] child 37 said into stderr: "zend_mm_heap corrupted"
php_1      | [17-Oct-2017 09:02:24] WARNING: [pool www] child 37 exited with code 1 after 86445.483074 seconds from start
php_1      | [17-Oct-2017 09:02:24] NOTICE: [pool www] child 380 started
php_1      | [17-Oct-2017 09:02:56] WARNING: [pool www] child 38 said into stderr: "zend_mm_heap corrupted"
php_1      | [17-Oct-2017 09:02:56] WARNING: [pool www] child 38 exited with code 1 after 86417.441816 seconds from start
php_1      | [17-Oct-2017 09:02:56] NOTICE: [pool www] child 381 started
```
