### ISSUE TITLE
cannot seem to run traefik on port 80??

### ISSUE THREAD

**Issue by dakkusingh** [wodby/docker4drupal#198]
Hi guys,
When i am running traefik on port 8000 everything seems fine. However, switching over to port 80 doesnt seem to resolve for me. This is what is in my docker-compose file.

```
  traefik:
    image: traefik
    command: -c /dev/null --web --docker --logLevel=INFO
    ports:
      - '80:80'
#      - '8080:8080' # Dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
```

any help?
