### ISSUE TITLE
PDOException: SQLSTATE[HY000] [2002] No such file or directory 

### ISSUE THREAD

**Issue by MikeiLL** [wodby/docker4drupal#209]
### Codebase
Identical to another Drupal 7 install
  
### Host OS 
macOS Sierra

### Docker info output
```
Containers: 10
 Running: 7
 Paused: 0
 Stopped: 3
Images: 25
Server Version: 17.03.1-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 155
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.27-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.952 GiB
Name: moby
ID: SAMR:3ABT:3G24:PBCI:UI26:P7XZ:ADPA:LLXW:XBA2:DWXV:NGNC:6O3H
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 76
 Goroutines: 78
 System Time: 2017-11-16T00:24:16.859123503Z
 EventsListeners: 2
No Proxy: *.local, 169.254/16
Username: mikeill
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

### Docker compose file
```
version: "2"
# https://docker4drupal.readthedocs.io/en/latest/
# drupal.docker.localhost:8000
services:
  mariadb:
    image: wodby/mariadb:10.1-2.3.5
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
    volumes:
      - ./mariadb-init:/docker-entrypoint-initdb.d # Place init .sql file(s) here.
#      - /path/to/mariadb/data/on/host:/var/lib/mysql # I want to manage volumes manually.

  php:
# 1. Images with vanilla Drupal – wodby/drupal:[DRUPAL_VERSION]-[PHP_VERSION]-[STABILITY_TAG].
#    image: wodby/drupal:8-7.1-3.0.0
#    image: wodby/drupal:8-7.0-3.0.0
#    image: wodby/drupal:7-7.1-3.0.0
#    image: wodby/drupal:7-7.0-3.0.0
#    image: wodby/drupal:7-5.6-3.0.0
#    image: wodby/drupal:6-5.6-3.0.0
#    image: wodby/drupal:6-5.3-3.0.0
# 2. Images without Drupal – wodby/drupal-php:[PHP_VERSION]-[STABILITY_TAG].
#    image: wodby/drupal-php:7.1-3.0.0
#    image: wodby/drupal-php:7.0-3.0.0
    image: wodby/drupal-php:5.6-3.0.0
#    image: wodby/drupal-php:5.3-3.0.0
    environment:
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
      PHP_FPM_CLEAR_ENV: "no"
      DB_HOST: mariadb
      DB_USER: drupal
      DB_PASSWORD: drupal
      DB_NAME: drupal
      DB_DRIVER: mysql
    volumes:
#      - ./:/var/www/html:cached # User-guided caching
      - docker-sync:/var/www/html # Docker-sync

  apache:
    image: wodby/php-apache:2.4-2.0.0
    depends_on:
      - php
    environment:
      APACHE_LOG_LEVEL: debug
      APACHE_BACKEND_HOST: php
      APACHE_SERVER_ROOT: /var/www/html
    volumes:
 #     - ./:/var/www/html:cached # User-guided caching
      - docker-sync:/var/www/html # Docker-sync
## Options for macOS users (https://docker4drupal.readthedocs.io/en/latest/macos)
 #     - ./:/var/www/html:cached # User-guided caching
#      - docker-sync:/var/www/html # Docker-sync
    labels:
      - 'traefik.backend=apache'
      - 'traefik.port=80'
      - 'traefik.frontend.rule=Host:drupal.docker.localhost'


  mailhog:
    image: mailhog/mailhog
    labels:
      - 'traefik.backend=mailhog'
      - 'traefik.port=8025'
      - 'traefik.frontend.rule=Host:mailhog.drupal.docker.localhost'

  portainer:
    image: portainer/portainer
    command: --no-auth -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - 'traefik.backend=portainer'
      - 'traefik.port=9000'
      - 'traefik.frontend.rule=Host:portainer.drupal.docker.localhost'

  traefik:
    image: traefik
    command: -c /dev/null --web --docker --logLevel=INFO
    ports:
      - '8000:80'
      - '8080:8080' # Dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
 # ./:
## Docker-sync for macOS users
  docker-sync:
    external: true
## For Xdebug profiler
#  files:

```

### Logs output
```
mariadb_1    | MySQL init process done. Ready for start up.
mariadb_1    | 
mariadb_1    | 2017-11-15 21:09:27 139916018207560 [Note] mysqld (mysqld 10.1.26-MariaDB) starting as process 1 ...
mariadb_1    | 2017-11-15 21:09:27 139916018207560 [Note] InnoDB: Using mutexes to ref count buffer pool pages
mariadb_1    | 2017-11-15 21:09:27 139916018207560 [Note] InnoDB: The InnoDB memory heap is disabled
mariadb_1    | 2017-11-15 21:09:27 139916018207560 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
mariadb_1    | 2017-11-15 21:09:27 139916018207560 [Note] InnoDB: GCC builtin __atomic_thread_fence() is used for memory barrier
mariadb_1    | 2017-11-15 21:09:27 139916018207560 [Note] InnoDB: Compressed tables use zlib 1.2.11
mariadb_1    | 2017-11-15 21:09:27 139916018207560 [Note] InnoDB: Using Linux native AIO
mariadb_1    | 2017-11-15 21:09:27 139916018207560 [Note] InnoDB: Using SSE crc32 instructions
mariadb_1    | 2017-11-15 21:09:27 139916018207560 [Note] InnoDB: Initializing buffer pool, size = 1.0G
mariadb_1    | 2017-11-15 21:09:27 139916018207560 [Note] InnoDB: Completed initialization of buffer pool
mariadb_1    | 2017-11-15 21:09:27 139916018207560 [Note] InnoDB: Highest supported file format is Barracuda.
mariadb_1    | 2017-11-15 21:09:28 139916018207560 [Note] InnoDB: 128 rollback segment(s) are active.
mariadb_1    | 2017-11-15 21:09:28 139916018207560 [Note] InnoDB: Waiting for purge to start
mariadb_1    | 2017-11-15 21:09:28 139916018207560 [Note] InnoDB:  Percona XtraDB (http://www.percona.com) 5.6.36-82.1 started; log sequence number 74808575
mariadb_1    | 2017-11-15 21:09:28 139914517334760 [Note] InnoDB: Dumping buffer pool(s) not yet started
mariadb_1    | 2017-11-15 21:09:28 139916018207560 [Note] Plugin 'FEEDBACK' is disabled.
mariadb_1    | 2017-11-15 21:09:28 139916018207560 [Note] Server socket created on IP: '0.0.0.0'.
mariadb_1    | 2017-11-15 21:09:28 139916018207560 [Warning] 'proxies_priv' entry '@% root@f0d3e9d8dc81' ignored in --skip-name-resolve mode.
mariadb_1    | 2017-11-15 21:09:28 139916018207560 [Note] Reading of all Master_info entries succeded
mariadb_1    | 2017-11-15 21:09:28 139916018207560 [Note] Added new Master_info '' to hash table
mariadb_1    | 2017-11-15 21:09:28 139916018207560 [Note] mysqld: ready for connections.
mariadb_1    | Version: '10.1.26-MariaDB'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MariaDB Server
mariadb_1    | 2017-11-16  0:18:07 139914516515560 [Note] mysqld: Normal shutdown
mariadb_1    | 
mariadb_1    | 2017-11-16  0:18:07 139914516515560 [Note] Event Scheduler: Purging the queue. 0 events
mariadb_1    | 2017-11-16  0:18:07 139914517711592 [Note] InnoDB: FTS optimize thread exiting.
mariadb_1    | 2017-11-16  0:18:07 139914516515560 [Note] InnoDB: Starting shutdown...
mariadb_1    | 2017-11-16  0:18:08 139914516515560 [Note] InnoDB: Waiting for page_cleaner to finish flushing of buffer pool
mariadb_1    | 2017-11-16  0:18:10 139914516515560 [Note] InnoDB: Shutdown completed; log sequence number 74808585
mariadb_1    | 2017-11-16  0:18:11 139914516515560 [Note] mysqld: Shutdown complete
mariadb_1    | 

```

Getting the following error in the browser at drupal.docker.localhost:8000:

PDOException: SQLSTATE[HY000] [2002] No such file or directory in lock_may_be_available() (line 167 of /var/www/html/includes/lock.inc).

This address works: drupal.docker.localhost:8080
