### ISSUE TITLE
Unable to use drupal api driver with behat

### ISSUE THREAD

**Issue by jsayegh** [wodby/docker4drupal#214]
I tried to setup the behat drupal extension on a docker4drupal stack, it worked only when i didn't enable the drupal api driver in the behat.yml file.
I got the following error when i tried to run a test:

PHP Fatal error: Undefined class constant 'MYSQL_ATTR_USE_BUFFERED_QUERY' in /home/gitlab/netto982df6/netto/includes/database/mysql/database.inc on line 56. 

### Docker compose file
```yml
# 
version: "2"

services:
  mariadb:
    image: wodby/mariadb:10.1-2.1.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: netto
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
    volumes:
#    - ./mariadb-init:/docker-entrypoint-initdb.d # Place init .sql file(s) here.
#    - /path/to/mariadb/data/on/host:/var/lib/mysql # I want to manage volumes manually.
      - ./mariadb-init:/var/opt/mysql/mariadb-dump

  php:
    image: wodby/drupal-php:5.6-2.0.0
#    image: wodby/drupal-php:7.0-2.0.0
#    image: wodby/drupal-php:7.1-2.0.0
#    image: wodby/drupal-php:5.6-2.0.0
#    image: wodby/drupal-php:5.3-2.0.0
    environment:
      PHP_SITE_NAME: dev
      PHP_HOST_NAME: localhost:80
#      PHP_DOCROOT: public # Relative path inside the /var/www/html/ directory.
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
      PHP_XDEBUG_ENABLED: 0 # Set 1 to enable.
      NETTO_ENV: developpement
    volumes:
      - ./:/var/www/html

  nginx:
    image: wodby/drupal-nginx:7-1.10-2.0.0
    depends_on:
      - php
    environment:
      NGINX_BACKEND_HOST: php
      NGINX_SERVER_NAME: localhost
      NGINX_UPSTREAM_NAME: php
#      NGINX_DOCROOT: public # Relative path inside the /var/www/html/ directory.
      DRUPAL_VERSION: 7 # Allowed: 7, 8.
    volumes_from:
      - php
    networks:
      - default
      - traefik
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=traefik_default'
      - 'traefik.backend=nginx_${COMPOSE_PROJECT_NAME}'
      - 'traefik.frontend.rule=Host:${COMPOSE_PROJECT_URL}'

  pma:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mariadb
      PMA_USER: drupal
      PMA_PASSWORD: drupal
      PHP_UPLOAD_MAX_FILESIZE: 1G
      PHP_MAX_INPUT_VARS: 1G
    networks:
      - default
      - traefik
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=traefik_default'
      - 'traefik.backend=pma_${COMPOSE_PROJECT_NAME}'
      - 'traefik.frontend.rule=Host:pma.${COMPOSE_PROJECT_URL}'

  mailhog:
    image: mailhog/mailhog
    networks:
      - default
      - traefik
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=traefik_default'
      - 'traefik.backend=mailhog_${COMPOSE_PROJECT_NAME}'
      - 'traefik.port=8025'
      - 'traefik.frontend.rule=Host:mailhog.${COMPOSE_PROJECT_URL}'

networks:
  traefik:
    external:
      name: traefik_default

#  redis:
#    image: redis:3.2-alpine

#  memcached:
#    image: memcached:1.4-alpine

#  memcached-admin:
#    image: phynias/phpmemcachedadmin
#    ports:
#      - "80016:80"

#  solr:
#    image: solr:5.5-alpine
#    volumes:
#      - ./docker-runtime/solr:/opt/solr/server/solr/mycores
#    ports:
#      - "80013:8983"

#  varnish:
#    image: wodby/drupal-varnish
#    depends_on:
#      - nginx
#    environment:
#      VARNISH_SECRET: secret
#      VARNISH_BACKEND_HOST: nginx
#      VARNISH_BACKEND_PORT: 80
#      VARNISH_MEMORY_SIZE: 256M
#      VARNISH_STORAGE_SIZE: 1024M
#    ports:
#      - "8004:6081" # HTTP Proxy
#      - "8005:6082" # Control terminal


```
