### ISSUE TITLE
404 page not found

### ISSUE THREAD

**Issue by neuquen** [wodby/docker4drupal#243]
I followed the [Quick Start guide](https://wodby.com/stacks/drupal/docs/local/quick-start/#option-2-mount-my-drupal-codebase) to mount my own codebase.  After running `docker-compose up -d` and going to http://drupal.docker.localhost:8000 I get a `404 page not found` error.  I'm currently using the Docker for Windows application.  See below for my current setup.

The one unique aspect of my setup is my PHP/NGINX volumes are set to `- ./Source:/var/www/html` instead of `- ./:/var/www/html` because my codebase lives under a sub-directory called `/Source` and my docker-compose.yml file is one directory above it.

One other strange thing I've noticed is that sometimes when I go to the site at http://drupal.docker.localhost:8000 it will return a `503`, but when I go to the site using http://127.0.01:8000 it consistently returns a `404`.

### Codebase
mounted codebase
  
### Host OS 
Windows 10

### Docker info output
```
$ docker info
Containers: 6
 Running: 6
 Paused: 0
 Stopped: 0
Images: 7
Server Version: 17.06.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfb82a876ecc11b5ca0977d1733adbe58599088a
runc version: 2d41c047c83e09a6d61d464906feb2a2f3c52aa4
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.36-moby
Operating System: Alpine Linux v3.5
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.934GiB
Name: moby
ID: WOGS:CDYJ:DPTJ:VQWZ:2E2Y:7TV3:YUMR:CX2K:V6QJ:IGAD:2HH5:ZWBB
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 64
 Goroutines: 64
 System Time: 2018-02-20T22:08:40.2857979Z
 EventsListeners: 1
Http Proxy: http://www.example.com
Https Proxy: http://www.example.com
Registry: https://index.docker.io/v1/
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

### Docker compose file
```yml
version: "2"

services:
  mariadb:
    image: wodby/mariadb:10.2-3.0.2
#    image: wodby/mariadb:10.1-3.0.2
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
    volumes:
      - ./mariadb-init:/docker-entrypoint-initdb.d # Place init .sql file(s) here.
#      - /path/to/mariadb/data/on/host:/var/lib/mysql # I want to manage volumes manually.

  php:
    image: wodby/drupal-php:5.6-3.3.1
    environment:
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
      PHP_FPM_CLEAR_ENV: "no"
      DB_HOST: mariadb
      DB_USER: drupal
      DB_PASSWORD: drupal
      DB_NAME: drupal
      DB_DRIVER: mysql
#      PHP_XDEBUG: 1
#      PHP_XDEBUG_DEFAULT_ENABLE: 1
#      PHP_XDEBUG_REMOTE_CONNECT_BACK: 0
#      PHP_XDEBUG_REMOTE_HOST: "10.254.254.254"
#      PHP_XDEBUG_PROFILER_OUTPUT_DIR: /mnt/files/xdebug/profiler
#      PHP_XDEBUG_TRACE_OUTPUT_DIR: /mnt/files/xdebug/traces
#      PHP_BLACKFIRE: 1
    volumes:
      - ./Source:/var/www/html
## Options for macOS users (https://docker4drupal.readthedocs.io/en/latest/macos)
#      - codebase:/var/www/html:cached # User-guided caching
#      - docker-sync:/var/www/html # Docker-sync
## For Xdebug profiler files
#      - files:/mnt/files

  nginx:
# wodby/drupal-nginx:[DRUPAL_VERSION]-[NGINX_VERSION]-[STABILITY_TAG].
    image: wodby/drupal-nginx:7-1.13-3.0.2
    depends_on:
      - php
    environment:
      NGINX_STATIC_CONTENT_OPEN_FILE_CACHE: "off"
      NGINX_ERROR_LOG_LEVEL: debug
      NGINX_BACKEND_HOST: php
      NGINX_SERVER_ROOT: /var/www/html
#      NGINX_DRUPAL_FILE_PROXY_URL: example.com
    volumes_from:
      - php
# Options for macOS users (https://docker4drupal.readthedocs.io/en/latest/macos)
#      - codebase:/var/www/html:cached # User-guided caching
#      - docker-sync:/var/www/html # Docker-sync
    labels:
      - 'traefik.backend=nginx'
      - 'traefik.port=80'
      - 'traefik.frontend.rule=Host:drupal.docker.localhost'

  mailhog:
    image: mailhog/mailhog
    labels:
      - 'traefik.backend=mailhog'
      - 'traefik.port=8025'
      - 'traefik.frontend.rule=Host:mailhog.drupal.docker.localhost'

  portainer:
    image: portainer/portainer
    command: --no-auth -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - 'traefik.backend=portainer'
      - 'traefik.port=9000'
      - 'traefik.frontend.rule=Host:portainer.drupal.docker.localhost'

  traefik:
    image: traefik
    command: -c /dev/null --web --docker --logLevel=INFO
    ports:
      - '8000:80'
#      - '8080:8080' # Dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  codebase:
## Docker-sync for macOS users
#  docker-sync:
#    external: true
## For Xdebug profiler
#  files:

```

### Logs output
```
$ docker-compose logs nginx
Attaching to container_nginx_1
nginx_1      | 2018/02/20 21:47:40 [notice] 1#1: using the "epoll" event method
nginx_1      | 2018/02/20 21:47:40 [notice] 1#1: nginx/1.13.7
nginx_1      | 2018/02/20 21:47:40 [notice] 1#1: built by gcc 6.3.0 (Alpine 6.3.0)
nginx_1      | 2018/02/20 21:47:40 [notice] 1#1: OS: Linux 4.9.36-moby
nginx_1      | 2018/02/20 21:47:40 [notice] 1#1: getrlimit(RLIMIT_NOFILE): 1048576:1048576
nginx_1      | 2018/02/20 21:47:40 [notice] 1#1: start worker processes
nginx_1      | 2018/02/20 21:47:40 [notice] 1#1: start worker process 24
nginx_1      | 2018/02/20 21:47:40 [notice] 1#1: start worker process 25
nginx_1      | 2018/02/20 21:52:03 [notice] 1#1: signal 15 (SIGTERM) received, exiting
nginx_1      | 2018/02/20 21:52:03 [notice] 24#24: exiting
nginx_1      | 2018/02/20 21:52:03 [notice] 25#25: exiting
nginx_1      | 2018/02/20 21:52:03 [notice] 24#24: exit
nginx_1      | 2018/02/20 21:52:03 [notice] 25#25: exit
nginx_1      | 2018/02/20 21:52:03 [notice] 1#1: signal 17 (SIGCHLD) received from 24
nginx_1      | 2018/02/20 21:52:03 [notice] 1#1: worker process 24 exited with code 0
nginx_1      | 2018/02/20 21:52:03 [notice] 1#1: signal 29 (SIGIO) received
nginx_1      | 2018/02/20 21:52:03 [notice] 1#1: signal 17 (SIGCHLD) received from 25
nginx_1      | 2018/02/20 21:52:03 [notice] 1#1: worker process 25 exited with code 0
nginx_1      | 2018/02/20 21:52:03 [notice] 1#1: exit
nginx_1      | 2018/02/20 21:52:07 [notice] 1#1: using the "epoll" event method
nginx_1      | 2018/02/20 21:52:07 [notice] 1#1: nginx/1.13.7
nginx_1      | 2018/02/20 21:52:07 [notice] 1#1: built by gcc 6.3.0 (Alpine 6.3.0)
nginx_1      | 2018/02/20 21:52:07 [notice] 1#1: OS: Linux 4.9.36-moby
nginx_1      | 2018/02/20 21:52:07 [notice] 1#1: getrlimit(RLIMIT_NOFILE): 1048576:1048576
nginx_1      | 2018/02/20 21:52:07 [notice] 1#1: start worker processes
nginx_1      | 2018/02/20 21:52:07 [notice] 1#1: start worker process 24
nginx_1      | 2018/02/20 21:52:07 [notice] 1#1: start worker process 25

$ docker-compose logs php
Attaching to container_php_1
php_1        | [20-Feb-2018 21:11:02] NOTICE: fpm is running, pid 1
php_1        | [20-Feb-2018 21:11:02] NOTICE: ready to handle connections
php_1        | [20-Feb-2018 21:45:23] NOTICE: Terminating ...
php_1        | [20-Feb-2018 21:45:23] NOTICE: exiting, bye-bye!
php_1        | container_linux.go:262: starting container process caused "process_linux.go:339: container init caused \"rootfs_linux.go:57: mounting \\\"/C/path/to/directory/Source\\\" to rootfs \\\"/var/lib/docker/overlay2/d8b5365ab576f25fc26e79ecbba47e2a5749e583d118643c40ececaa3304c9d4/merged\\\" at \\\"/var/www/html\\\" caused \\\"stat /C/path/to/directory/Source: input/output error\\\"\""
php_1        | [20-Feb-2018 21:47:39] NOTICE: fpm is running, pid 1
php_1        | [20-Feb-2018 21:47:39] NOTICE: ready to handle connections
php_1        | [20-Feb-2018 21:52:03] NOTICE: Terminating ...
php_1        | [20-Feb-2018 21:52:03] NOTICE: exiting, bye-bye!
php_1        | [20-Feb-2018 21:52:06] NOTICE: fpm is running, pid 1
php_1        | [20-Feb-2018 21:52:06] NOTICE: ready to handle connections

$ docker-compose ps
           Name                          Command               State          Ports
-------------------------------------------------------------------------------------------
container_mailhog_1     MailHog                          Up      1025/tcp, 8025/tcp
container_mariadb_1     /docker-entrypoint.sh mysqld     Up      3306/tcp
container_nginx_1       /docker-entrypoint.sh sudo ...   Up      80/tcp
container_php_1         /docker-entrypoint.sh php-fpm    Up      9000/tcp
container_portainer_1   /portainer --no-auth -H un ...   Up      9000/tcp
container_traefik_1     /traefik -c /dev/null --we ...   Up      0.0.0.0:8000->80/tcp

PS C:\> docker-compose exec php ls -lah /var/www/html
total 315
drwxr-xr-x    2 root     root        8.0K Feb 20 14:34 .
drwxr-xr-x    1 www-data www-data    4.0K Dec  5 07:32 ..
-rwxr-xr-x    1 root     root         331 Feb 20 14:34 .editorconfig
-rwxr-xr-x    1 root     root         218 Feb 20 14:34 .gitignore
-rwxr-xr-x    1 root     root        6.0K Feb 20 14:34 .htaccess
-rwxr-xr-x    1 root     root       14.3K Feb 20 14:34 403.html
-rwxr-xr-x    1 root     root       14.3K Feb 20 14:34 404.html
-rwxr-xr-x    1 root     root      111.2K Feb 20 14:34 CHANGELOG.txt
-rwxr-xr-x    1 root     root        1.5K Feb 20 14:34 COPYRIGHT.txt
-rwxr-xr-x    1 root     root        1.7K Feb 20 14:34 INSTALL.mysql.txt
-rwxr-xr-x    1 root     root        1.9K Feb 20 14:34 INSTALL.pgsql.txt
-rwxr-xr-x    1 root     root        1.3K Feb 20 14:34 INSTALL.sqlite.txt
-rwxr-xr-x    1 root     root       18.0K Feb 20 14:34 INSTALL.txt
-rwxr-xr-x    1 root     root       18.0K Feb 20 14:34 LICENSE.txt
-rwxr-xr-x    1 root     root        8.8K Feb 20 14:34 MAINTAINERS.txt
-rwxr-xr-x    1 root     root          27 Feb 20 14:34 README.md
-rwxr-xr-x    1 root     root        5.4K Feb 20 14:34 README.txt
-rwxr-xr-x    1 root     root       10.1K Feb 20 14:34 UPGRADE.txt
-rwxr-xr-x    1 root     root        6.6K Feb 20 14:34 authorize.php
-rwxr-xr-x    1 root     root        4.3K Feb 20 14:34 cron-stats.php
-rwxr-xr-x    1 root     root         746 Feb 20 14:34 cron.php
-rwxr-xr-x    1 root     root        4.6K Feb 20 14:34 healthcheck.php
drwxr-xr-x    2 root     root           0 Feb 20 14:34 includes
-rwxr-xr-x    1 root     root         550 Feb 20 14:34 index.php
-rwxr-xr-x    1 root     root         729 Feb 20 14:34 install.php
drwxr-xr-x    2 root     root           0 Feb 20 14:34 misc
drwxr-xr-x    2 root     root           0 Feb 20 14:34 modules
drwxr-xr-x    2 root     root           0 Feb 20 14:34 profiles
-rwxr-xr-x    1 root     root        2.3K Feb 20 14:34 robots.txt
drwxr-xr-x    2 root     root           0 Feb 20 14:34 scripts
drwxr-xr-x    2 root     root           0 Feb 20 14:34 sites
drwxr-xr-x    2 root     root           0 Feb 20 14:34 themes
-rwxr-xr-x    1 root     root       20.0K Feb 20 14:34 update.php
-rwxr-xr-x    1 root     root         435 Feb 20 14:34 xmlrpc.php


PS C:\> docker-compose exec nginx ls -lah /var/www/html
total 315
drwxr-xr-x    2 root     root        8.0K Feb 20 14:34 .
drwxr-xr-x    3 root     root        4.0K Nov 30 06:22 ..
-rwxr-xr-x    1 root     root         331 Feb 20 14:34 .editorconfig
-rwxr-xr-x    1 root     root         218 Feb 20 14:34 .gitignore
-rwxr-xr-x    1 root     root        6.0K Feb 20 14:34 .htaccess
-rwxr-xr-x    1 root     root       14.3K Feb 20 14:34 403.html
-rwxr-xr-x    1 root     root       14.3K Feb 20 14:34 404.html
-rwxr-xr-x    1 root     root      111.2K Feb 20 14:34 CHANGELOG.txt
-rwxr-xr-x    1 root     root        1.5K Feb 20 14:34 COPYRIGHT.txt
-rwxr-xr-x    1 root     root        1.7K Feb 20 14:34 INSTALL.mysql.txt
-rwxr-xr-x    1 root     root        1.9K Feb 20 14:34 INSTALL.pgsql.txt
-rwxr-xr-x    1 root     root        1.3K Feb 20 14:34 INSTALL.sqlite.txt
-rwxr-xr-x    1 root     root       18.0K Feb 20 14:34 INSTALL.txt
-rwxr-xr-x    1 root     root       18.0K Feb 20 14:34 LICENSE.txt
-rwxr-xr-x    1 root     root        8.8K Feb 20 14:34 MAINTAINERS.txt
-rwxr-xr-x    1 root     root          27 Feb 20 14:34 README.md
-rwxr-xr-x    1 root     root        5.4K Feb 20 14:34 README.txt
-rwxr-xr-x    1 root     root       10.1K Feb 20 14:34 UPGRADE.txt
-rwxr-xr-x    1 root     root        6.6K Feb 20 14:34 authorize.php
-rwxr-xr-x    1 root     root        4.3K Feb 20 14:34 cron-stats.php
-rwxr-xr-x    1 root     root         746 Feb 20 14:34 cron.php
-rwxr-xr-x    1 root     root        4.6K Feb 20 14:34 healthcheck.php
drwxr-xr-x    2 root     root           0 Feb 20 14:34 includes
-rwxr-xr-x    1 root     root         550 Feb 20 14:34 index.php
-rwxr-xr-x    1 root     root         729 Feb 20 14:34 install.php
drwxr-xr-x    2 root     root           0 Feb 20 14:34 misc
drwxr-xr-x    2 root     root           0 Feb 20 14:34 modules
drwxr-xr-x    2 root     root           0 Feb 20 14:34 profiles
-rwxr-xr-x    1 root     root        2.3K Feb 20 14:34 robots.txt
drwxr-xr-x    2 root     root           0 Feb 20 14:34 scripts
drwxr-xr-x    2 root     root           0 Feb 20 14:34 sites
drwxr-xr-x    2 root     root           0 Feb 20 14:34 themes
-rwxr-xr-x    1 root     root       20.0K Feb 20 14:34 update.php
-rwxr-xr-x    1 root     root         435 Feb 20 14:34 xmlrpc.php
```

**Comment by michaelpporter** [comment]
Try this file:

```yml
version: "2"

services:
  mariadb:
    image: wodby/mariadb:10.2-3.0.2
#    image: wodby/mariadb:10.1-3.0.2
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
    volumes:
      - ./mariadb-init:/docker-entrypoint-initdb.d # Place init .sql file(s) here.
#      - /path/to/mariadb/data/on/host:/var/lib/mysql # I want to manage volumes manually.

  php:
    image: wodby/drupal-php:5.6-3.3.1
    environment:
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
      PHP_FPM_CLEAR_ENV: "no"
      DB_HOST: mariadb
      DB_USER: drupal
      DB_PASSWORD: drupal
      DB_NAME: drupal
      DB_DRIVER: mysql
#      PHP_XDEBUG: 1
#      PHP_XDEBUG_DEFAULT_ENABLE: 1
#      PHP_XDEBUG_REMOTE_CONNECT_BACK: 0
#      PHP_XDEBUG_REMOTE_HOST: "10.254.254.254"
#      PHP_XDEBUG_PROFILER_OUTPUT_DIR: /mnt/files/xdebug/profiler
#      PHP_XDEBUG_TRACE_OUTPUT_DIR: /mnt/files/xdebug/traces
#      PHP_BLACKFIRE: 1
    volumes:
      - ./Source:/var/www/html:cached

  nginx:
    image: wodby/drupal-nginx:7-1.13-3.0.2
    depends_on:
      - php
    environment:
      NGINX_STATIC_CONTENT_OPEN_FILE_CACHE: "off"
      NGINX_ERROR_LOG_LEVEL: debug
      NGINX_BACKEND_HOST: php
      NGINX_SERVER_ROOT: /var/www/html
#      NGINX_DRUPAL_FILE_PROXY_URL: example.com
    volumes_from:
      - php
    labels:
      - 'traefik.backend=nginx'
      - 'traefik.port=80'
      - 'traefik.frontend.rule=Host:drupal.docker.localhost'

  mailhog:
    image: mailhog/mailhog
    labels:
      - 'traefik.backend=mailhog'
      - 'traefik.port=8025'
      - 'traefik.frontend.rule=Host:mailhog.drupal.docker.localhost'

  portainer:
    image: portainer/portainer
    command: --no-auth -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - 'traefik.backend=portainer'
      - 'traefik.port=9000'
      - 'traefik.frontend.rule=Host:portainer.drupal.docker.localhost'

  traefik:
    image: traefik
    command: -c /dev/null --web --docker --logLevel=INFO
    ports:
      - '8000:80'
#      - '8080:8080' # Dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
```
