### ISSUE TITLE
Using docker-compose.override.yml does not appear to mount properly

### ISSUE THREAD

**Issue by bleen** [wodby/docker4drupal#250]
### Codebase
mounted codebase
  
### Host OS 
macOS high Sierra

### Docker info output
```
Containers: 28
 Running: 6
 Paused: 0
 Stopped: 22
Images: 28
Server Version: 17.12.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 89623f28b87a6004d4b785663257362d1658a729
runc version: b2567b37d7b75eb4cf325b77297b140ea686ce8f
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.60-linuxkit-aufs
Operating System: Docker for Mac
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.952GiB
Name: linuxkit-025000000001
ID: P6DP:PUOX:MXVD:D32G:CVOM:XH6W:ZEN3:JVPW:JIP2:IPV2:4YWD:7VCN
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 71
 Goroutines: 81
 System Time: 2018-03-12T16:50:16.569180741Z
 EventsListeners: 3
HTTP Proxy: docker.for.mac.http.internal:3128
HTTPS Proxy: docker.for.mac.http.internal:3129
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

### Docker compose file
```yml
no changes from https://github.com/wodby/docker4drupal
```

I cloned the https://github.com/wodby/docker4drupal repo to a folder called ~/Sites/d8-contrib and made no changes whatsoever (except `PROJECT_NAME=d8_contrib` in .env). Then I `git cloned` drupal core into ~/Sites/d8-contrib/web and ran `composer up` locally. (I know I can use the vanilla drupal that comes with the container, but I'm trying to use this to figure out how to use my own codebase.) Everything works, but when i inspect the PHP container I see this under "mounts":

```json
"Mounts": [
            {
                "Type": "volume",
                "Name": "d8contrib_codebase",
                "Source": "/var/lib/docker/volumes/d8contrib_codebase/_data",
                "Destination": "/var/www/html",
                "Driver": "local",
                "Mode": "rw",
                "RW": true,
                "Propagation": ""
            }
        ],
```

If I edit docker-compose.override.yml to this (removing "codebase"): 
```yml
version: "2"

services:
  php:
    image: wodby/drupal:$DRUPAL_TAG
    environment:
      PHP_FPM_CLEAR_ENV: "no"
    volumes:
      - ./:/var/www/html:cached

  nginx:
    volumes:
      - ./:/var/www/html:cached
```
and then inspect the container I see:

```json
"Mounts": [
            {
                "Type": "bind",
                "Source": "/Users/bleen/Sites/d8-contrib",
                "Destination": "/var/www/html",
                "Mode": "cached",
                "RW": true,
                "Propagation": "rprivate"
            }
        ],
```

Am I doing something wrong? Why wont my local dir get mounted unless I edit the docker-compose.override.yml file?

Thanks!!

**Comment by bleen** [comment]
... shouldnt docker-compose.override.yml actually be: 

```yml
version: "2"

services:
  php:
    image: wodby/drupal:$DRUPAL_TAG
    environment:
      PHP_FPM_CLEAR_ENV: "no"
    volumes:
      - ./web:/var/www/html:cached

  nginx:
    volumes:
      - ./web:/var/www/html:cached
```
Happy to open a PR...
