### ISSUE TITLE
404 for domains ending with .localhost

### ISSUE THREAD

**Issue by sobi3ch** [wodby/docker4drupal#256]
### Codebase
Built-in vanilla Drupal or mounted codebase (both)
  
### Description
I found out in this comment https://github.com/wodby/docker4drupal/issues/223#issuecomment-353203350 witch is telling me that I shouldn't use domains ending with `.localhost`. And guess what? This works like a charm. Before I found this solution I was testing my files and directories privileges,  and other things, obviously nothing works.

I'm working in chrome and the following link is a proove we have this problem from 2015 https://bugs.chromium.org/p/chromium/issues/detail?id=489973

And this is the stackoverflow issue about the same thing https://stackoverflow.com/questions/41122676/vagrant-not-working-with-localhost-extension-on-chrome

After all when I've tested  `drupal.docker.localhost` domain with Firefox it works fine.

### Proposed solution
Change default domain to end with `.local` instead of `.localhost`
`drupal.docker.localhost -> drupal.docker.local`

### Host OS
Ubuntu 17.10

### Docker info output
```
Containers: 6
 Running: 6
 Paused: 0
 Stopped: 0
Images: 854
Server Version: 17.12.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 89623f28b87a6004d4b785663257362d1658a729
runc version: b2567b37d7b75eb4cf325b77297b140ea686ce8f
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.13.0-37-generic
Operating System: Ubuntu 17.10
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.33GiB
Name: cc-Inspiron-5570
ID: WVVO:5T3K:IBJX:KY3M:EYFM:7Q6H:6OA6:WAN7:JTBR:E2PZ:I357:GEK5
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

### Docker compose file
```yml
version: "2"

services:
  mariadb:
    image: wodby/mariadb:$MARIADB_TAG
    container_name: "${PROJECT_NAME}_mariadb"
    stop_grace_period: 30s
    environment:
      MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
      MYSQL_DATABASE: $DB_NAME
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASSWORD
#    volumes:
#      - ./mariadb-init:/docker-entrypoint-initdb.d # Place init .sql file(s) here.
#      - /path/to/mariadb/data/on/host:/var/lib/mysql # I want to manage volumes manually.

  php:
    image: wodby/drupal-php:$PHP_TAG
    container_name: "${PROJECT_NAME}_php"
    environment:
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
      DB_HOST: $DB_HOST
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
      DB_NAME: $DB_NAME
      DB_DRIVER: $DB_DRIVER
#      PHP_XDEBUG: 1
#      PHP_XDEBUG_DEFAULT_ENABLE: 1
#      PHP_XDEBUG_REMOTE_CONNECT_BACK: 0
#      PHP_XDEBUG_REMOTE_HOST: "10.254.254.254"
#      PHP_BLACKFIRE: 1
    volumes:
      - ./:/var/www/html
## For macOS users (https://wodby.com/stacks/drupal/docs/local/docker-for-mac/)
#      - ./:/var/www/html:cached # User-guided caching
#      - docker-sync:/var/www/html # Docker-sync
## For Xdebug profiler files
#      - files:/mnt/files

  nginx:
    image: wodby/drupal-nginx:$NGINX_TAG
    container_name: "${PROJECT_NAME}_nginx"
    depends_on:
      - php
    environment:
      NGINX_STATIC_CONTENT_OPEN_FILE_CACHE: "off"
      NGINX_ERROR_LOG_LEVEL: debug
      NGINX_BACKEND_HOST: php
      NGINX_SERVER_ROOT: /var/www/html/drupal8
#      NGINX_DRUPAL_FILE_PROXY_URL: http://example.com
    volumes:
      - ./:/var/www/html
# For macOS users (https://wodby.com/stacks/drupal/docs/local/docker-for-mac/)
#      - ./:/var/www/html:cached # User-guided caching
#      - docker-sync:/var/www/html # Docker-sync
    labels:
      - 'traefik.backend=nginx'
      - 'traefik.port=80'
      - 'traefik.frontend.rule=Host:${PROJECT_BASE_URL}'

  mailhog:
    image: mailhog/mailhog
    container_name: "${PROJECT_NAME}_mailhog"
    labels:
      - 'traefik.backend=mailhog'
      - 'traefik.port=8025'
      - 'traefik.frontend.rule=Host:mailhog.${PROJECT_BASE_URL}'

#  postgres:
#    image: wodby/postgres:$POSTGRES_TAG
#    container_name: "${PROJECT_NAME}_postgres"
#    stop_grace_period: 30s
#    environment:
#      POSTGRES_PASSWORD: $DB_PASSWORD
#      POSTGRES_DB: $DB_NAME
#      POSTGRES_USER: $DB_USER
#    volumes:
#      - ./postgres-init:/docker-entrypoint-initdb.d # Place init file(s) here.
#      - /path/to/postgres/data/on/host:/var/lib/postgresql/data # I want to manage volumes manually.

#  apache:
#    image: wodby/php-apache:$APACHE_TAG
#    container_name: "${PROJECT_NAME}_apache"
#    depends_on:
#      - php
#    environment:
#      APACHE_LOG_LEVEL: debug
#      APACHE_BACKEND_HOST: php
#      APACHE_SERVER_ROOT: /var/www/html/web
#    volumes:
#      - ./:/var/www/html
## For macOS users (https://wodby.com/stacks/drupal/docs/local/docker-for-mac/)
##      - ./:/var/www/html:cached # User-guided caching
##      - docker-sync:/var/www/html # Docker-sync
#    labels:
#      - 'traefik.backend=apache'
#      - 'traefik.port=80'
#      - 'traefik.frontend.rule=Host:${PROJECT_BASE_URL}'

#  varnish:
#    image: wodby/drupal-varnish:$VARNISH_TAG
#    container_name: "${PROJECT_NAME}_varnish"
#    depends_on:
#      - nginx
#    environment:
#      VARNISH_SECRET: secret
#      VARNISH_BACKEND_HOST: nginx
#      VARNISH_BACKEND_PORT: 80
#    labels:
#      - 'traefik.backend=varnish'
#      - 'traefik.port=6081'
#      - 'traefik.frontend.rule=Host:varnish.${PROJECT_BASE_URL}'

#  redis:
#    container_name: "${PROJECT_NAME}_redis"
#    image: wodby/redis:$REDIS_TAG

#  adminer:
#    container_name: "${PROJECT_NAME}_adminer"
#    image: wodby/adminer:$ADMINER_TAG
#    environment:
#      ADMINER_SALT: adminer-salt
#    labels:
#      - 'traefik.backend=adminer'
#      - 'traefik.port=9000'
#      - 'traefik.frontend.rule=Host:adminer.${PROJECT_BASE_URL}'

#  pma:
#    image: phpmyadmin/phpmyadmin
#    container_name: "${PROJECT_NAME}_pma"
#    environment:
#      PMA_HOST: $DB_HOST
#      PMA_USER: $DB_USER
#      PMA_PASSWORD: $DB_PASSWORD
#      PHP_UPLOAD_MAX_FILESIZE: 1G
#      PHP_MAX_INPUT_VARS: 1G
#    labels:
#      - 'traefik.backend=pma'
#      - 'traefik.port=80'
#      - 'traefik.frontend.rule=Host:pma.${PROJECT_BASE_URL}'

#  solr:
#    image: wodby/drupal-solr:$SOLR_TAG
#    container_name: "${PROJECT_NAME}_solr"
#    environment:
#      SOLR_HEAP: 1024m
#    labels:
#      - 'traefik.backend=solr'
#      - 'traefik.port=8983'
#      - 'traefik.frontend.rule=Host:solr.${PROJECT_BASE_URL}'

#  nodejs:
#    image: wodby/drupal-node:$DRUPAL_NODE_TAG
#    container_name: "${PROJECT_NAME}_drupal_nodejs"
#    environment:
#       NODE_SERVICE_KEY: node-service-key
#    labels:
#      - 'traefik.backend=nodejs'
#      - 'traefik.port=8080'
#      - 'traefik.frontend.rule=Host:nodejs.${PROJECT_BASE_URL}'
#    volumes:
#      - ./path/to/your/single-page-app:/app
#    command: sh -c 'npm install && npm run start'

#  memcached:
#    container_name: "${PROJECT_NAME}_memcached"
#    image: wodby/memcached:$MEMCACHED_TAG

#  rsyslog:
#    container_name: "${PROJECT_NAME}_rsyslog"
#    image: wodby/rsyslog:$RSYSLOG_TAG

#  athenapdf:
#    image: arachnysdocker/athenapdf-service:$ATHENAPDF_TAG
#    container_name: "${PROJECT_NAME}_athenapdf"
#    environment:
#      WEAVER_AUTH_KEY: weaver-auth-key
#      WEAVER_ATHENA_CMD: "athenapdf -S"
#      WEAVER_MAX_WORKERS: 10
#      WEAVER_MAX_CONVERSION_QUEUE: 50
#      WEAVER_WORKER_TIMEOUT: 90
#      WEAVER_CONVERSION_FALLBACK: "false"

#  node:
#    image: node:alpine
#    container_name: "${PROJECT_NAME}_node"
#    working_dir: /app
#    labels:
#      - 'traefik.backend=node'
#      - 'traefik.port=3000'
#      - 'traefik.frontend.rule=Host:front.${PROJECT_BASE_URL}'
#    expose:
#      - "3000"
#    volumes:
#      - ./path/to/your/single-page-app:/app
#    command: sh -c 'npm install && npm run start'

#  blackfire:
#    image: blackfire/blackfire
#    container_name: "${PROJECT_NAME}_blackfire"
#    environment:
#      BLACKFIRE_SERVER_ID: XXXXX
#      BLACKFIRE_SERVER_TOKEN: YYYYY

#  webgrind:
#    image: wodby/webgrind:$WEBGRIND_TAG
#    container_name: "${PROJECT_NAME}_webgrind"
#    environment:
#      WEBGRIND_PROFILER_DIR: /mnt/files/xdebug/profiler
#    labels:
#      - 'traefik.backend=webgrind'
#      - 'traefik.port=8080'
#      - 'traefik.frontend.rule=Host:webgrind.${PROJECT_BASE_URL}'
#    volumes:
#      - files:/mnt/files

  portainer:
    image: portainer/portainer
    container_name: "${PROJECT_NAME}_portainer"
    command: --no-auth -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - 'traefik.backend=portainer'
      - 'traefik.port=9000'
      - 'traefik.frontend.rule=Host:portainer.${PROJECT_BASE_URL}'

  traefik:
    image: traefik
    container_name: "${PROJECT_NAME}_traefik"
    command: -c /dev/null --web --docker --logLevel=INFO
    ports:
      - '8000:80'
#      - '8080:8080' # Dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

#volumes:
## Docker-sync for macOS users
#  docker-sync:
#    external: true
## For Xdebug profiler
#  files:
```

### Logs output
```
my_drupal8_project_nginx | 2018/03/21 10:51:18 [notice] 1#1: using the "epoll" event method
my_drupal8_project_nginx | 2018/03/21 10:51:18 [notice] 1#1: nginx/1.13.9
my_drupal8_project_nginx | 2018/03/21 10:51:18 [notice] 1#1: built by gcc 6.4.0 (Alpine 6.4.0) 
my_drupal8_project_nginx | 2018/03/21 10:51:18 [notice] 1#1: OS: Linux 4.13.0-37-generic
my_drupal8_project_nginx | 2018/03/21 10:51:18 [notice] 1#1: getrlimit(RLIMIT_NOFILE): 1048576:1048576
my_drupal8_project_nginx | 2018/03/21 10:51:18 [notice] 1#1: start worker processes
my_drupal8_project_nginx | 2018/03/21 10:51:18 [notice] 1#1: start worker process 38
my_drupal8_project_nginx | 2018/03/21 10:51:18 [notice] 1#1: start worker process 39
my_drupal8_project_nginx | 2018/03/21 10:51:18 [notice] 1#1: start worker process 40
my_drupal8_project_nginx | 2018/03/21 10:51:18 [notice] 1#1: start worker process 41
my_drupal8_project_nginx | 2018/03/21 10:51:18 [notice] 1#1: start worker process 42
my_drupal8_project_nginx | 2018/03/21 10:51:18 [notice] 1#1: start worker process 43
my_drupal8_project_nginx | 2018/03/21 10:51:18 [notice] 1#1: start worker process 44
my_drupal8_project_nginx | 2018/03/21 10:51:18 [notice] 1#1: start worker process 45
my_drupal8_project_nginx | 192.168.16.2 - - [21/Mar/2018:10:52:46 +0000] "GET / HTTP/1.1" 302 324 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.167 Safari/537.36"
my_drupal8_project_nginx | 192.168.16.2 - - [21/Mar/2018:10:52:47 +0000] "GET /core/install.php HTTP/1.1" 200 4142 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.167 Safari/537.36"
my_drupal8_project_nginx | 2018/03/21 10:52:47 [info] 39#39: *5 client closed connection while waiting for request, client: 192.168.16.2, server: 0.0.0.0:80
my_drupal8_project_mailhog | 2018/03/21 10:51:17 Using in-memory storage
my_drupal8_project_nginx | 192.168.16.2 - - [21/Mar/2018:10:54:15 +0000] "POST /core/install.php HTTP/1.1" 302 496 "http://drupal.docker.local:8000/core/install.php" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.167 Safari/537.36"
my_drupal8_project_mailhog | 2018/03/21 10:51:17 [SMTP] Binding to address: 0.0.0.0:1025
my_drupal8_project_nginx | 192.168.16.2 - - [21/Mar/2018:10:54:16 +0000] "GET /core/install.php?langcode=en HTTP/1.1" 200 2383 "http://drupal.docker.local:8000/core/install.php" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.167 Safari/537.36"
my_drupal8_project_mailhog | [HTTP] Binding to address: 0.0.0.0:8025
my_drupal8_project_nginx | 192.168.16.2 - - [21/Mar/2018:10:54:19 +0000] "POST /core/install.php?langcode=en HTTP/1.1" 302 580 "http://drupal.docker.local:8000/core/install.php?langcode=en" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.167 Safari/537.36"
my_drupal8_project_mailhog | 2018/03/21 10:51:17 Serving under http://0.0.0.0:8025/
my_drupal8_project_traefik | time="2018-03-21T10:51:17Z" level=info msg="Using TOML configuration file /dev/null" 
my_drupal8_project_nginx | 192.168.16.2 - - [21/Mar/2018:10:54:19 +0000] "GET /core/install.php?langcode=en&profile=standard HTTP/1.1" 200 2944 "http://drupal.docker.local:8000/core/install.php?langcode=en" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.167 Safari/537.36"
my_drupal8_project_mariadb | Initializing database
my_drupal8_project_portainer | 2018/03/21 10:51:17 Starting Portainer 1.16.4 on :9000
my_drupal8_project_traefik | time="2018-03-21T10:51:17Z" level=warning msg="web provider configuration is deprecated, you should use these options : api, rest provider, ping and metrics" 
my_drupal8_project_mailhog | Creating API v1 with WebPath: 
my_drupal8_project_mariadb | 
my_drupal8_project_traefik | time="2018-03-21T10:51:17Z" level=info msg="Traefik version v1.5.4 built on 2018-03-15_01:35:21PM" 
my_drupal8_project_mailhog | Creating API v2 with WebPath: 
my_drupal8_project_mariadb | PLEASE REMEMBER TO SET A PASSWORD FOR THE MariaDB root USER !
my_drupal8_project_php | [21-Mar-2018 10:51:18] NOTICE: fpm is running, pid 1
my_drupal8_project_traefik | time="2018-03-21T10:51:17Z" level=info msg="
my_drupal8_project_mailhog | [APIv1] KEEPALIVE /api/v1/events
my_drupal8_project_mariadb | To do so, start the server, then issue the following commands:
my_drupal8_project_php | [21-Mar-2018 10:51:18] NOTICE: ready to handle connections
my_drupal8_project_mailhog | [APIv1] KEEPALIVE /api/v1/events
my_drupal8_project_traefik | Stats collection is disabled.
my_drupal8_project_mariadb | 
my_drupal8_project_php | 192.168.16.7 -  21/Mar/2018:10:52:46 +0000 "GET /index.php" 302
my_drupal8_project_mailhog | [APIv1] KEEPALIVE /api/v1/events
my_drupal8_project_traefik | Help us improve Traefik by turning this feature on :)
my_drupal8_project_mariadb | '/usr/bin/mysqladmin' -u root password 'new-password'
my_drupal8_project_php | 192.168.16.7 -  21/Mar/2018:10:52:46 +0000 "GET /core/install.php" 200
my_drupal8_project_mailhog | [APIv1] KEEPALIVE /api/v1/events
my_drupal8_project_traefik | More details on: https://docs.traefik.io/basics/#collected-data
my_drupal8_project_mariadb | '/usr/bin/mysqladmin' -u root -h  password 'new-password'
my_drupal8_project_php | 192.168.16.7 -  21/Mar/2018:10:54:15 +0000 "POST /core/install.php" 302
my_drupal8_project_mailhog | [APIv1] KEEPALIVE /api/v1/events
my_drupal8_project_traefik | " 
my_drupal8_project_mariadb | 
my_drupal8_project_php | 192.168.16.7 -  21/Mar/2018:10:54:15 +0000 "GET /core/install.php" 200
my_drupal8_project_mailhog | [APIv1] KEEPALIVE /api/v1/events
my_drupal8_project_traefik | time="2018-03-21T10:51:17Z" level=info msg="Preparing server traefik &{Network: Address::8080 TLS:<nil> Redirect:<nil> Auth:<nil> WhitelistSourceRange:[] Compress:false ProxyProtocol:<nil> ForwardedHeaders:0xc42069fd20} with readTimeout=0s writeTimeout=0s idleTimeout=3m0s" 
my_drupal8_project_mariadb | Alternatively you can run:
my_drupal8_project_php | 192.168.16.7 -  21/Mar/2018:10:54:19 +0000 "POST /core/install.php" 302
my_drupal8_project_mailhog | [APIv1] KEEPALIVE /api/v1/events
my_drupal8_project_traefik | time="2018-03-21T10:51:17Z" level=info msg="Preparing server http &{Network: Address::80 TLS:<nil> Redirect:<nil> Auth:<nil> WhitelistSourceRange:[] Compress:false ProxyProtocol:<nil> ForwardedHeaders:0xc42069fd00} with readTimeout=0s writeTimeout=0s idleTimeout=3m0s" 
my_drupal8_project_mariadb | '/usr/bin/mysql_secure_installation'
my_drupal8_project_mailhog | [APIv1] KEEPALIVE /api/v1/events
my_drupal8_project_php | 192.168.16.7 -  21/Mar/2018:10:54:19 +0000 "GET /core/install.php" 200
my_drupal8_project_traefik | time="2018-03-21T10:51:17Z" level=info msg="Starting provider *docker.Provider {"Watch":true,"Filename":"","Constraints":null,"Trace":false,"DebugLogGeneratedTemplate":false,"Endpoint":"unix:///var/run/docker.sock","Domain":"","TLS":null,"ExposedByDefault":true,"UseBindPortIP":false,"SwarmMode":false}" 
my_drupal8_project_mariadb | 
my_drupal8_project_mailhog | [APIv1] KEEPALIVE /api/v1/events
my_drupal8_project_traefik | time="2018-03-21T10:51:17Z" level=info msg="Starting server on :8080" 
my_drupal8_project_mailhog | [APIv1] KEEPALIVE /api/v1/events
my_drupal8_project_mariadb | which will also give you the option of removing the test
my_drupal8_project_traefik | time="2018-03-21T10:51:17Z" level=info msg="Starting server on :80" 
my_drupal8_project_mariadb | databases and anonymous user created by default.  This is
my_drupal8_project_traefik | time="2018-03-21T10:51:17Z" level=info msg="Server configuration reloaded on :80" 
my_drupal8_project_mariadb | strongly recommended for production servers.
my_drupal8_project_traefik | time="2018-03-21T10:51:17Z" level=info msg="Server configuration reloaded on :8080" 
my_drupal8_project_mariadb | 
my_drupal8_project_traefik | time="2018-03-21T10:51:19Z" level=info msg="Server configuration reloaded on :8080" 
my_drupal8_project_mariadb | See the MariaDB Knowledgebase at http://mariadb.com/kb or the
my_drupal8_project_traefik | time="2018-03-21T10:51:19Z" level=info msg="Server configuration reloaded on :80" 
my_drupal8_project_mariadb | MySQL manual for more instructions.
my_drupal8_project_mariadb | 
my_drupal8_project_mariadb | Please report any problems at http://mariadb.org/jira
my_drupal8_project_mariadb | 
my_drupal8_project_mariadb | The latest information about MariaDB is available at http://mariadb.org/.
my_drupal8_project_mariadb | You can find additional information about the MySQL part at:
my_drupal8_project_mariadb | http://dev.mysql.com
my_drupal8_project_mariadb | Consider joining MariaDB's strong and vibrant community:
my_drupal8_project_mariadb | https://mariadb.org/get-involved/
my_drupal8_project_mariadb | 
my_drupal8_project_mariadb | Database initialized
my_drupal8_project_mariadb | MySQL init process in progress...
my_drupal8_project_mariadb | 2018-03-21 10:51:19 140706196441992 [Note] mysqld (mysqld 10.2.12-MariaDB) starting as process 101 ...
my_drupal8_project_mariadb | 2018-03-21 10:51:19 140706196441992 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
my_drupal8_project_mariadb | 2018-03-21 10:51:19 140706196441992 [Note] InnoDB: Uses event mutexes
my_drupal8_project_mariadb | 2018-03-21 10:51:19 140706196441992 [Note] InnoDB: Compressed tables use zlib 1.2.11
my_drupal8_project_mariadb | 2018-03-21 10:51:19 140706196441992 [Note] InnoDB: Using Linux native AIO
my_drupal8_project_mariadb | 2018-03-21 10:51:19 140706196441992 [Note] InnoDB: Number of pools: 1
my_drupal8_project_mariadb | 2018-03-21 10:51:19 140706196441992 [Note] InnoDB: Using SSE2 crc32 instructions
my_drupal8_project_mariadb | 2018-03-21 10:51:19 140706196441992 [Note] InnoDB: Initializing buffer pool, total size = 1G, instances = 4, chunk size = 128M
my_drupal8_project_mariadb | 2018-03-21 10:51:19 140706196441992 [Note] InnoDB: Completed initialization of buffer pool
my_drupal8_project_mariadb | 2018-03-21 10:51:19 140704721582824 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
my_drupal8_project_mariadb | 2018-03-21 10:51:19 140706196441992 [Note] InnoDB: Highest supported file format is Barracuda.
my_drupal8_project_mariadb | 2018-03-21 10:51:19 140706196441992 [Note] InnoDB: 128 out of 128 rollback segments are active.
my_drupal8_project_mariadb | 2018-03-21 10:51:19 140706196441992 [Note] InnoDB: Creating shared tablespace for temporary tables
my_drupal8_project_mariadb | 2018-03-21 10:51:19 140706196441992 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
my_drupal8_project_mariadb | 2018-03-21 10:51:19 140706196441992 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
my_drupal8_project_mariadb | 2018-03-21 10:51:19 140706196441992 [Note] InnoDB: Waiting for purge to start
my_drupal8_project_mariadb | 2018-03-21 10:51:20 140706196441992 [Note] InnoDB: 5.7.20 started; log sequence number 1619205
my_drupal8_project_mariadb | 2018-03-21 10:51:20 140704750582504 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
my_drupal8_project_mariadb | 2018-03-21 10:51:20 140704750582504 [Note] InnoDB: Buffer pool(s) load completed at 180321 10:51:20
my_drupal8_project_mariadb | 2018-03-21 10:51:20 140706196441992 [Note] Plugin 'FEEDBACK' is disabled.
my_drupal8_project_mariadb | 2018-03-21 10:51:20 140706196441992 [Warning] 'user' entry 'root@81e7a5a31a05' ignored in --skip-name-resolve mode.
my_drupal8_project_mariadb | 2018-03-21 10:51:20 140706196441992 [Warning] 'user' entry '@81e7a5a31a05' ignored in --skip-name-resolve mode.
my_drupal8_project_mariadb | 2018-03-21 10:51:20 140706196441992 [Warning] 'proxies_priv' entry '@% root@81e7a5a31a05' ignored in --skip-name-resolve mode.
my_drupal8_project_mariadb | 2018-03-21 10:51:20 140706196441992 [Note] Reading of all Master_info entries succeded
my_drupal8_project_mariadb | 2018-03-21 10:51:20 140706196441992 [Note] Added new Master_info '' to hash table
my_drupal8_project_mariadb | 2018-03-21 10:51:20 140706196441992 [Note] mysqld: ready for connections.
my_drupal8_project_mariadb | Version: '10.2.12-MariaDB'  socket: '/var/run/mysqld/mysqld.sock'  port: 0  MariaDB Server
my_drupal8_project_mariadb | 2018-03-21 10:51:21 140704741362408 [Warning] 'proxies_priv' entry '@% root@81e7a5a31a05' ignored in --skip-name-resolve mode.
my_drupal8_project_mariadb | 2018-03-21 10:51:21 140704741362408 [Warning] 'proxies_priv' entry '@% root@81e7a5a31a05' ignored in --skip-name-resolve mode.
my_drupal8_project_mariadb | 
my_drupal8_project_mariadb | 2018-03-21 10:51:21 140704741042920 [Note] mysqld (unknown): Normal shutdown
my_drupal8_project_mariadb | 2018-03-21 10:51:21 140704741042920 [Note] Event Scheduler: Purging the queue. 0 events
my_drupal8_project_mariadb | 2018-03-21 10:51:21 140704751053544 [Note] InnoDB: FTS optimize thread exiting.
my_drupal8_project_mariadb | 2018-03-21 10:51:21 140704741042920 [Note] InnoDB: Starting shutdown...
my_drupal8_project_mariadb | 2018-03-21 10:51:21 140704750582504 [Note] InnoDB: Dumping buffer pool(s) to /var/lib/mysql/ib_buffer_pool
my_drupal8_project_mariadb | 2018-03-21 10:51:21 140704750582504 [Note] InnoDB: Buffer pool(s) dump completed at 180321 10:51:21
my_drupal8_project_mariadb | 2018-03-21 10:51:22 140704741042920 [Note] InnoDB: Shutdown completed; log sequence number 1619224
my_drupal8_project_mariadb | 2018-03-21 10:51:22 140704741042920 [Note] InnoDB: Removed temporary tablespace data file: "ibtmp1"
my_drupal8_project_mariadb | 2018-03-21 10:51:22 140704741042920 [Note] mysqld: Shutdown complete
my_drupal8_project_mariadb | 
my_drupal8_project_mariadb | 
my_drupal8_project_mariadb | MySQL init process done. Ready for start up.
my_drupal8_project_mariadb | 
my_drupal8_project_mariadb | 2018-03-21 10:51:22 140244371229576 [Note] mysqld (mysqld 10.2.12-MariaDB) starting as process 1 ...
my_drupal8_project_mariadb | 2018-03-21 10:51:22 140244371229576 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
my_drupal8_project_mariadb | 2018-03-21 10:51:22 140244371229576 [Note] InnoDB: Uses event mutexes
my_drupal8_project_mariadb | 2018-03-21 10:51:22 140244371229576 [Note] InnoDB: Compressed tables use zlib 1.2.11
my_drupal8_project_mariadb | 2018-03-21 10:51:22 140244371229576 [Note] InnoDB: Using Linux native AIO
my_drupal8_project_mariadb | 2018-03-21 10:51:22 140244371229576 [Note] InnoDB: Number of pools: 1
my_drupal8_project_mariadb | 2018-03-21 10:51:22 140244371229576 [Note] InnoDB: Using SSE2 crc32 instructions
my_drupal8_project_mariadb | 2018-03-21 10:51:22 140244371229576 [Note] InnoDB: Initializing buffer pool, total size = 1G, instances = 4, chunk size = 128M
my_drupal8_project_mariadb | 2018-03-21 10:51:23 140244371229576 [Note] InnoDB: Completed initialization of buffer pool
my_drupal8_project_mariadb | 2018-03-21 10:51:23 140242896370408 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
my_drupal8_project_mariadb | 2018-03-21 10:51:23 140244371229576 [Note] InnoDB: Highest supported file format is Barracuda.
my_drupal8_project_mariadb | 2018-03-21 10:51:23 140244371229576 [Note] InnoDB: 128 out of 128 rollback segments are active.
my_drupal8_project_mariadb | 2018-03-21 10:51:23 140244371229576 [Note] InnoDB: Creating shared tablespace for temporary tables
my_drupal8_project_mariadb | 2018-03-21 10:51:23 140244371229576 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
my_drupal8_project_mariadb | 2018-03-21 10:51:23 140244371229576 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
my_drupal8_project_mariadb | 2018-03-21 10:51:23 140244371229576 [Note] InnoDB: Waiting for purge to start
my_drupal8_project_mariadb | 2018-03-21 10:51:23 140244371229576 [Note] InnoDB: 5.7.20 started; log sequence number 1619224
my_drupal8_project_mariadb | 2018-03-21 10:51:23 140242925370088 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
my_drupal8_project_mariadb | 2018-03-21 10:51:23 140242925370088 [Note] InnoDB: Buffer pool(s) load completed at 180321 10:51:23
my_drupal8_project_mariadb | 2018-03-21 10:51:23 140244371229576 [Note] Plugin 'FEEDBACK' is disabled.
my_drupal8_project_mariadb | 2018-03-21 10:51:23 140244371229576 [Note] Server socket created on IP: '0.0.0.0'.
my_drupal8_project_mariadb | 2018-03-21 10:51:23 140244371229576 [Warning] 'proxies_priv' entry '@% root@81e7a5a31a05' ignored in --skip-name-resolve mode.
my_drupal8_project_mariadb | 2018-03-21 10:51:23 140244371229576 [Note] Reading of all Master_info entries succeded
my_drupal8_project_mariadb | 2018-03-21 10:51:23 140244371229576 [Note] Added new Master_info '' to hash table
my_drupal8_project_mariadb | 2018-03-21 10:51:23 140244371229576 [Note] mysqld: ready for connections.
my_drupal8_project_mariadb | Version: '10.2.12-MariaDB'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MariaDB Server

```
