### ISSUE TITLE
Unable to access on my website

### ISSUE THREAD

**Issue by Gmulti** [wodby/docker4drupal#264]
ERR_CONNECTION_REFUSED with chrome when i go on : http://drupal.docker.localhost:8000/

### Codebase
Built-in vanilla Drupal
  
### Host OS 
macOS High Sierra

### Docker info output
```
Containers: 10
 Running: 7
 Paused: 0
 Stopped: 3
Images: 12
Server Version: 18.03.0-ce
Storage Driver: aufs
 Root Dir: /mnt/sda1/var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 93
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfd04396dc68220d1cecbe686a6cc3aa5ce3667c
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.89-boot2docker
Operating System: Boot2Docker 18.03.0-ce (TCL 8.2.1); HEAD : 404ee40 - Thu Mar 22 17:12:23 UTC 2018
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 995.6MiB
Name: default
ID: 6OG5:WWLX:XU7M:DSWU:TBQP:N35I:XNCN:GDQN:JYRV:YR46:GVLI:CND3
Docker Root Dir: /mnt/sda1/var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
 provider=virtualbox
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

### Docker compose file
```yml
version: "2"

services:
  mariadb:
    image: wodby/mariadb:$MARIADB_TAG
    container_name: "${PROJECT_NAME}_mariadb"
    stop_grace_period: 30s
    environment:
      MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
      MYSQL_DATABASE: $DB_NAME
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASSWORD
#    volumes:
#      - ./mariadb-init:/docker-entrypoint-initdb.d # Place init .sql file(s) here.
#      - /path/to/mariadb/data/on/host:/var/lib/mysql # I want to manage volumes manually.

  php:
    image: wodby/drupal-php:$PHP_TAG
    container_name: "${PROJECT_NAME}_php"
    environment:
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
      DB_HOST: $DB_HOST
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
      DB_NAME: $DB_NAME
      DB_DRIVER: $DB_DRIVER
## Read instructions at https://wodby.com/stacks/drupal/docs/local/xdebug/
#      PHP_XDEBUG: 1
#      PHP_XDEBUG_DEFAULT_ENABLE: 1
#      PHP_XDEBUG_REMOTE_CONNECT_BACK: 0
#      PHP_IDE_CONFIG: serverName=my-ide
#      PHP_XDEBUG_REMOTE_HOST: 172.17.0.1 # Linux
#      PHP_XDEBUG_REMOTE_HOST: 10.254.254.254 # macOS
#      PHP_XDEBUG_REMOTE_HOST: 10.0.75.1 # Windows
    volumes:
      # - ./:/var/www/html
## For macOS users (https://wodby.com/stacks/drupal/docs/local/docker-for-mac/)
     - ./:/var/www/html:cached # User-guided caching
     - docker-sync:/var/www/html # Docker-sync
## For Xdebug profiler files
#      - files:/mnt/files

  nginx:
    image: wodby/drupal-nginx:$NGINX_TAG
    container_name: "${PROJECT_NAME}_nginx"
    depends_on:
      - php
    environment:
      NGINX_STATIC_CONTENT_OPEN_FILE_CACHE: "off"
      NGINX_ERROR_LOG_LEVEL: debug
      NGINX_BACKEND_HOST: php
      NGINX_SERVER_ROOT: /var/www/html/web
#      NGINX_DRUPAL_FILE_PROXY_URL: http://example.com
    volumes:
      # - ./:/var/www/html
# For macOS users (https://wodby.com/stacks/drupal/docs/local/docker-for-mac/)
     - ./:/var/www/html:cached # User-guided caching
     - docker-sync:/var/www/html # Docker-sync
    labels:
      - 'traefik.backend=nginx'
      - 'traefik.port=80'
      - 'traefik.frontend.rule=Host:${PROJECT_BASE_URL}'

  mailhog:
    image: mailhog/mailhog
    container_name: "${PROJECT_NAME}_mailhog"
    labels:
      - 'traefik.backend=mailhog'
      - 'traefik.port=8025'
      - 'traefik.frontend.rule=Host:mailhog.${PROJECT_BASE_URL}'

#  postgres:
#    image: wodby/postgres:$POSTGRES_TAG
#    container_name: "${PROJECT_NAME}_postgres"
#    stop_grace_period: 30s
#    environment:
#      POSTGRES_PASSWORD: $DB_PASSWORD
#      POSTGRES_DB: $DB_NAME
#      POSTGRES_USER: $DB_USER
#    volumes:
#      - ./postgres-init:/docker-entrypoint-initdb.d # Place init file(s) here.
#      - /path/to/postgres/data/on/host:/var/lib/postgresql/data # I want to manage volumes manually.

#  apache:
#    image: wodby/php-apache:$APACHE_TAG
#    container_name: "${PROJECT_NAME}_apache"
#    depends_on:
#      - php
#    environment:
#      APACHE_LOG_LEVEL: debug
#      APACHE_BACKEND_HOST: php
#      APACHE_SERVER_ROOT: /var/www/html/web
#    volumes:
#      - ./:/var/www/html
## For macOS users (https://wodby.com/stacks/drupal/docs/local/docker-for-mac/)
##      - ./:/var/www/html:cached # User-guided caching
##      - docker-sync:/var/www/html # Docker-sync
#    labels:
#      - 'traefik.backend=apache'
#      - 'traefik.port=80'
#      - 'traefik.frontend.rule=Host:${PROJECT_BASE_URL}'

#  varnish:
#    image: wodby/drupal-varnish:$VARNISH_TAG
#    container_name: "${PROJECT_NAME}_varnish"
#    depends_on:
#      - nginx
#    environment:
#      VARNISH_SECRET: secret
#      VARNISH_BACKEND_HOST: nginx
#      VARNISH_BACKEND_PORT: 80
#    labels:
#      - 'traefik.backend=varnish'
#      - 'traefik.port=6081'
#      - 'traefik.frontend.rule=Host:varnish.${PROJECT_BASE_URL}'

#  redis:
#    container_name: "${PROJECT_NAME}_redis"
#    image: wodby/redis:$REDIS_TAG

#  adminer:
#    container_name: "${PROJECT_NAME}_adminer"
#    image: wodby/adminer:$ADMINER_TAG
#    environment:
#      ADMINER_SALT: adminer-salt
#    labels:
#      - 'traefik.backend=adminer'
#      - 'traefik.port=9000'
#      - 'traefik.frontend.rule=Host:adminer.${PROJECT_BASE_URL}'

#  pma:
#    image: phpmyadmin/phpmyadmin
#    container_name: "${PROJECT_NAME}_pma"
#    environment:
#      PMA_HOST: $DB_HOST
#      PMA_USER: $DB_USER
#      PMA_PASSWORD: $DB_PASSWORD
#      PHP_UPLOAD_MAX_FILESIZE: 1G
#      PHP_MAX_INPUT_VARS: 1G
#    labels:
#      - 'traefik.backend=pma'
#      - 'traefik.port=80'
#      - 'traefik.frontend.rule=Host:pma.${PROJECT_BASE_URL}'

#  solr:
#    image: wodby/drupal-solr:$SOLR_TAG
#    container_name: "${PROJECT_NAME}_solr"
#    environment:
#      SOLR_HEAP: 1024m
#    labels:
#      - 'traefik.backend=solr'
#      - 'traefik.port=8983'
#      - 'traefik.frontend.rule=Host:solr.${PROJECT_BASE_URL}'

#  nodejs:
#    image: wodby/drupal-node:$DRUPAL_NODE_TAG
#    container_name: "${PROJECT_NAME}_drupal_nodejs"
#    environment:
#       NODE_SERVICE_KEY: node-service-key
#    labels:
#      - 'traefik.backend=nodejs'
#      - 'traefik.port=8080'
#      - 'traefik.frontend.rule=Host:nodejs.${PROJECT_BASE_URL}'
#    volumes:
#      - ./path/to/your/single-page-app:/app
#    command: sh -c 'npm install && npm run start'

#  memcached:
#    container_name: "${PROJECT_NAME}_memcached"
#    image: wodby/memcached:$MEMCACHED_TAG

#  rsyslog:
#    container_name: "${PROJECT_NAME}_rsyslog"
#    image: wodby/rsyslog:$RSYSLOG_TAG

#  athenapdf:
#    image: arachnysdocker/athenapdf-service:$ATHENAPDF_TAG
#    container_name: "${PROJECT_NAME}_athenapdf"
#    environment:
#      WEAVER_AUTH_KEY: weaver-auth-key
#      WEAVER_ATHENA_CMD: "athenapdf -S"
#      WEAVER_MAX_WORKERS: 10
#      WEAVER_MAX_CONVERSION_QUEUE: 50
#      WEAVER_WORKER_TIMEOUT: 90
#      WEAVER_CONVERSION_FALLBACK: "false"

#  node:
#    image: node:alpine
#    container_name: "${PROJECT_NAME}_node"
#    working_dir: /app
#    labels:
#      - 'traefik.backend=node'
#      - 'traefik.port=3000'
#      - 'traefik.frontend.rule=Host:front.${PROJECT_BASE_URL}'
#    expose:
#      - "3000"
#    volumes:
#      - ./path/to/your/single-page-app:/app
#    command: sh -c 'npm install && npm run start'

#  blackfire:
#    image: blackfire/blackfire
#    container_name: "${PROJECT_NAME}_blackfire"
#    environment:
#      BLACKFIRE_SERVER_ID: XXXXX
#      BLACKFIRE_SERVER_TOKEN: YYYYY

#  webgrind:
#    image: wodby/webgrind:$WEBGRIND_TAG
#    container_name: "${PROJECT_NAME}_webgrind"
#    environment:
#      WEBGRIND_PROFILER_DIR: /mnt/files/xdebug/profiler
#    labels:
#      - 'traefik.backend=webgrind'
#      - 'traefik.port=8080'
#      - 'traefik.frontend.rule=Host:webgrind.${PROJECT_BASE_URL}'
#    volumes:
#      - files:/mnt/files

  portainer:
    image: portainer/portainer
    container_name: "${PROJECT_NAME}_portainer"
    command: --no-auth -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - 'traefik.backend=portainer'
      - 'traefik.port=9000'
      - 'traefik.frontend.rule=Host:portainer.${PROJECT_BASE_URL}'

  traefik:
    image: traefik
    container_name: "${PROJECT_NAME}_traefik"
    command: -c /dev/null --web --docker --logLevel=INFO
    ports:
      - '8000:80'
#      - '8080:8080' # Dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
## Docker-sync for macOS users
  docker-sync:
    external: true
## For Xdebug profiler
#  files:

```

### Logs output
```
Attaching to weglot-drupal_nginx, weglot-drupal_mailhog, weglot-drupal_portainer, weglot-drupal_php, weglot-drupal_mariadb, weglot-drupal_traefik
weglot-drupal_nginx | 2018/03/30 14:25:59 [notice] 1#1: using the "epoll" event method
weglot-drupal_nginx | 2018/03/30 14:25:59 [notice] 1#1: nginx/1.13.10
weglot-drupal_nginx | 2018/03/30 14:25:59 [notice] 1#1: built by gcc 6.4.0 (Alpine 6.4.0)
weglot-drupal_nginx | 2018/03/30 14:25:59 [notice] 1#1: OS: Linux 4.9.89-boot2docker
weglot-drupal_nginx | 2018/03/30 14:25:59 [notice] 1#1: getrlimit(RLIMIT_NOFILE): 1048576:1048576
weglot-drupal_nginx | 2018/03/30 14:25:59 [notice] 1#1: start worker processes
weglot-drupal_nginx | 2018/03/30 14:25:59 [notice] 1#1: start worker process 25
weglot-drupal_php | [30-Mar-2018 14:26:00] NOTICE: fpm is running, pid 1
weglot-drupal_php | [30-Mar-2018 14:26:00] NOTICE: ready to handle connections
weglot-drupal_mariadb | Initializing database
weglot-drupal_mariadb |
weglot-drupal_mariadb | PLEASE REMEMBER TO SET A PASSWORD FOR THE MariaDB root USER !
weglot-drupal_mariadb | To do so, start the server, then issue the following commands:
weglot-drupal_mariadb |
weglot-drupal_mariadb | '/usr/bin/mysqladmin' -u root password 'new-password'
weglot-drupal_mariadb | '/usr/bin/mysqladmin' -u root -h  password 'new-password'
weglot-drupal_mariadb |
weglot-drupal_mariadb | Alternatively you can run:
weglot-drupal_mariadb | '/usr/bin/mysql_secure_installation'
weglot-drupal_mariadb |
weglot-drupal_mariadb | which will also give you the option of removing the test
weglot-drupal_mariadb | databases and anonymous user created by default.  This is
weglot-drupal_mariadb | strongly recommended for production servers.
weglot-drupal_mariadb |
weglot-drupal_mariadb | See the MariaDB Knowledgebase at http://mariadb.com/kb or the
weglot-drupal_mariadb | MySQL manual for more instructions.
weglot-drupal_mariadb |
weglot-drupal_mariadb | Please report any problems at http://mariadb.org/jira
weglot-drupal_mariadb |
weglot-drupal_mariadb | The latest information about MariaDB is available at http://mariadb.org/.
weglot-drupal_mariadb | You can find additional information about the MySQL part at:
weglot-drupal_mariadb | http://dev.mysql.com
weglot-drupal_mariadb | Consider joining MariaDB's strong and vibrant community:
weglot-drupal_mariadb | https://mariadb.org/get-involved/
weglot-drupal_portainer | 2018/03/30 14:25:59 Starting Portainer 1.16.4 on :9000
weglot-drupal_mariadb |
weglot-drupal_mariadb | Database initialized
weglot-drupal_mariadb | MySQL init process in progress...
weglot-drupal_mariadb | 2018-03-30 14:26:02 140369006906248 [Note] mysqld (mysqld 10.2.14-MariaDB) starting as process 100 ...
weglot-drupal_mariadb | 2018-03-30 14:26:02 140369006906248 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
weglot-drupal_mariadb | 2018-03-30 14:26:02 140369006906248 [Note] InnoDB: Uses event mutexes
weglot-drupal_mariadb | 2018-03-30 14:26:02 140369006906248 [Note] InnoDB: Compressed tables use zlib 1.2.11
weglot-drupal_mariadb | 2018-03-30 14:26:02 140369006906248 [Note] InnoDB: Using Linux native AIO
weglot-drupal_mariadb | 2018-03-30 14:26:02 140369006906248 [Note] InnoDB: Number of pools: 1
weglot-drupal_mariadb | 2018-03-30 14:26:02 140369006906248 [Note] InnoDB: Using SSE2 crc32 instructions
weglot-drupal_mariadb | 2018-03-30 14:26:02 140369006906248 [Note] InnoDB: Initializing buffer pool, total size = 1G, instances = 4, chunk size = 128M
weglot-drupal_mariadb | 2018-03-30 14:26:02 140369006906248 [Note] InnoDB: Completed initialization of buffer pool
weglot-drupal_mariadb | 2018-03-30 14:26:02 140367532047080 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
weglot-drupal_mariadb | 2018-03-30 14:26:02 140369006906248 [Note] InnoDB: Highest supported file format is Barracuda.
weglot-drupal_mariadb | 2018-03-30 14:26:02 140369006906248 [Note] InnoDB: 128 out of 128 rollback segments are active.
weglot-drupal_mariadb | 2018-03-30 14:26:02 140369006906248 [Note] InnoDB: Creating shared tablespace for temporary tables
weglot-drupal_mariadb | 2018-03-30 14:26:02 140369006906248 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
weglot-drupal_mariadb | 2018-03-30 14:26:02 140369006906248 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
weglot-drupal_mariadb | 2018-03-30 14:26:02 140369006906248 [Note] InnoDB: Waiting for purge to start
weglot-drupal_mariadb | 2018-03-30 14:26:02 140369006906248 [Note] InnoDB: 5.7.21 started; log sequence number 1619994
weglot-drupal_mariadb | 2018-03-30 14:26:02 140367561988840 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
weglot-drupal_mariadb | 2018-03-30 14:26:02 140369006906248 [Note] Plugin 'FEEDBACK' is disabled.
weglot-drupal_mariadb | 2018-03-30 14:26:02 140367561988840 [Note] InnoDB: Buffer pool(s) load completed at 180330 14:26:02
weglot-drupal_mariadb | 2018-03-30 14:26:02 140369006906248 [Warning] 'user' entry 'root@bca2ecaf9b0a' ignored in --skip-name-resolve mode.
weglot-drupal_mariadb | 2018-03-30 14:26:02 140369006906248 [Warning] 'user' entry '@bca2ecaf9b0a' ignored in --skip-name-resolve mode.
weglot-drupal_mariadb | 2018-03-30 14:26:02 140369006906248 [Warning] 'proxies_priv' entry '@% root@bca2ecaf9b0a' ignored in --skip-name-resolve mode.
weglot-drupal_mariadb | 2018-03-30 14:26:02 140369006906248 [Note] Reading of all Master_info entries succeded
weglot-drupal_mariadb | 2018-03-30 14:26:02 140369006906248 [Note] Added new Master_info '' to hash table
weglot-drupal_mariadb | 2018-03-30 14:26:02 140369006906248 [Note] mysqld: ready for connections.
weglot-drupal_mariadb | Version: '10.2.14-MariaDB'  socket: '/var/run/mysqld/mysqld.sock'  port: 0  MariaDB Server
weglot-drupal_mailhog | 2018/03/30 14:25:59 Using in-memory storage
weglot-drupal_mailhog | 2018/03/30 14:25:59 [SMTP] Binding to address: 0.0.0.0:1025
weglot-drupal_mariadb | 2018-03-30 14:26:04 140367551826664 [Warning] 'proxies_priv' entry '@% root@bca2ecaf9b0a' ignored in --skip-name-resolve mode.
weglot-drupal_mariadb | 2018-03-30 14:26:04 140367551826664 [Warning] 'proxies_priv' entry '@% root@bca2ecaf9b0a' ignored in --skip-name-resolve mode.
weglot-drupal_mailhog | 2018/03/30 14:25:59 Serving under http://0.0.0.0:8025/
weglot-drupal_mariadb |
weglot-drupal_mailhog | [HTTP] Binding to address: 0.0.0.0:8025
weglot-drupal_mariadb | 2018-03-30 14:26:04 140367551507176 [Note] mysqld (initiated by: unknown): Normal shutdown
weglot-drupal_mailhog | Creating API v1 with WebPath:
weglot-drupal_mariadb | 2018-03-30 14:26:04 140367561423592 [Note] InnoDB: FTS optimize thread exiting.
weglot-drupal_mailhog | Creating API v2 with WebPath:
weglot-drupal_mailhog | [APIv1] KEEPALIVE /api/v1/events
weglot-drupal_mariadb | 2018-03-30 14:26:04 140367551507176 [Note] Event Scheduler: Purging the queue. 0 events
weglot-drupal_mailhog | [APIv1] KEEPALIVE /api/v1/events
weglot-drupal_mailhog | [APIv1] KEEPALIVE /api/v1/events
weglot-drupal_mariadb | 2018-03-30 14:26:04 140367551507176 [Note] InnoDB: Starting shutdown...
weglot-drupal_mailhog | [APIv1] KEEPALIVE /api/v1/events
weglot-drupal_mariadb | 2018-03-30 14:26:04 140367561988840 [Note] InnoDB: Dumping buffer pool(s) to /var/lib/mysql/ib_buffer_pool
weglot-drupal_mailhog | [APIv1] KEEPALIVE /api/v1/events
weglot-drupal_mariadb | 2018-03-30 14:26:04 140367561988840 [Note] InnoDB: Buffer pool(s) dump completed at 180330 14:26:04
weglot-drupal_mailhog | [APIv1] KEEPALIVE /api/v1/events
weglot-drupal_mariadb | 2018-03-30 14:26:06 140367551507176 [Note] InnoDB: Shutdown completed; log sequence number 1620022
weglot-drupal_mariadb | 2018-03-30 14:26:06 140367551507176 [Note] InnoDB: Removed temporary tablespace data file: "ibtmp1"
weglot-drupal_mariadb | 2018-03-30 14:26:06 140367551507176 [Note] mysqld: Shutdown complete
weglot-drupal_mariadb |
weglot-drupal_mariadb |
weglot-drupal_mariadb | MySQL init process done. Ready for start up.
weglot-drupal_mariadb |
weglot-drupal_mariadb | 2018-03-30 14:26:06 139775056636808 [Note] mysqld (mysqld 10.2.14-MariaDB) starting as process 1 ...
weglot-drupal_mariadb | 2018-03-30 14:26:06 139775056636808 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
weglot-drupal_mariadb | 2018-03-30 14:26:06 139775056636808 [Note] InnoDB: Uses event mutexes
weglot-drupal_mariadb | 2018-03-30 14:26:06 139775056636808 [Note] InnoDB: Compressed tables use zlib 1.2.11
weglot-drupal_mariadb | 2018-03-30 14:26:06 139775056636808 [Note] InnoDB: Using Linux native AIO
weglot-drupal_mariadb | 2018-03-30 14:26:06 139775056636808 [Note] InnoDB: Number of pools: 1
weglot-drupal_mariadb | 2018-03-30 14:26:06 139775056636808 [Note] InnoDB: Using SSE2 crc32 instructions
weglot-drupal_mariadb | 2018-03-30 14:26:06 139775056636808 [Note] InnoDB: Initializing buffer pool, total size = 1G, instances = 4, chunk size = 128M
weglot-drupal_mariadb | 2018-03-30 14:26:06 139775056636808 [Note] InnoDB: Completed initialization of buffer pool
weglot-drupal_mariadb | 2018-03-30 14:26:06 139773581777640 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
weglot-drupal_mariadb | 2018-03-30 14:26:06 139775056636808 [Note] InnoDB: Highest supported file format is Barracuda.
weglot-drupal_mariadb | 2018-03-30 14:26:06 139775056636808 [Note] InnoDB: 128 out of 128 rollback segments are active.
weglot-drupal_mariadb | 2018-03-30 14:26:06 139775056636808 [Note] InnoDB: Creating shared tablespace for temporary tables
weglot-drupal_mariadb | 2018-03-30 14:26:06 139775056636808 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
weglot-drupal_mariadb | 2018-03-30 14:26:06 139775056636808 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
weglot-drupal_mariadb | 2018-03-30 14:26:06 139775056636808 [Note] InnoDB: Waiting for purge to start
weglot-drupal_traefik | time="2018-03-30T14:25:59Z" level=info msg="Using TOML configuration file /dev/null"
weglot-drupal_mariadb | 2018-03-30 14:26:06 139775056636808 [Note] InnoDB: 5.7.21 started; log sequence number 1620022
weglot-drupal_traefik | time="2018-03-30T14:25:59Z" level=warning msg="web provider configuration is deprecated, you should use these options : api, rest provider, ping and metrics"
weglot-drupal_mariadb | 2018-03-30 14:26:06 139773611719400 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
weglot-drupal_traefik | time="2018-03-30T14:25:59Z" level=info msg="Traefik version v1.5.4 built on 2018-03-15_01:35:21PM"
weglot-drupal_mariadb | 2018-03-30 14:26:06 139775056636808 [Note] Plugin 'FEEDBACK' is disabled.
weglot-drupal_traefik | time="2018-03-30T14:25:59Z" level=info msg="
weglot-drupal_mariadb | 2018-03-30 14:26:06 139773611719400 [Note] InnoDB: Buffer pool(s) load completed at 180330 14:26:06
weglot-drupal_mariadb | 2018-03-30 14:26:06 139775056636808 [Note] Server socket created on IP: '0.0.0.0'.
weglot-drupal_traefik | Stats collection is disabled.
weglot-drupal_mariadb | 2018-03-30 14:26:06 139775056636808 [Warning] 'proxies_priv' entry '@% root@bca2ecaf9b0a' ignored in --skip-name-resolve mode.
weglot-drupal_mariadb | 2018-03-30 14:26:06 139775056636808 [Note] Reading of all Master_info entries succeded
weglot-drupal_traefik | Help us improve Traefik by turning this feature on :)
weglot-drupal_mariadb | 2018-03-30 14:26:06 139775056636808 [Note] Added new Master_info '' to hash table
weglot-drupal_traefik | More details on: https://docs.traefik.io/basics/#collected-data
weglot-drupal_traefik | "
weglot-drupal_traefik | time="2018-03-30T14:25:59Z" level=info msg="Preparing server http &{Network: Address::80 TLS:<nil> Redirect:<nil> Auth:<nil> WhitelistSourceRange:[] Compress:false ProxyProtocol:<nil> ForwardedHeaders:0xc4206d8d00} with readTimeout=0s writeTimeout=0s idleTimeout=3m0s"
weglot-drupal_mariadb | 2018-03-30 14:26:06 139775056636808 [Note] mysqld: ready for connections.
weglot-drupal_traefik | time="2018-03-30T14:25:59Z" level=info msg="Preparing server traefik &{Network: Address::8080 TLS:<nil> Redirect:<nil> Auth:<nil> WhitelistSourceRange:[] Compress:false ProxyProtocol:<nil> ForwardedHeaders:0xc4206d8d20} with readTimeout=0s writeTimeout=0s idleTimeout=3m0s"
weglot-drupal_mariadb | Version: '10.2.14-MariaDB'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MariaDB Server
weglot-drupal_traefik | time="2018-03-30T14:25:59Z" level=info msg="Starting provider *docker.Provider {"Watch":true,"Filename":"","Constraints":null,"Trace":false,"DebugLogGeneratedTemplate":false,"Endpoint":"unix:///var/run/docker.sock","Domain":"","TLS":null,"ExposedByDefault":true,"UseBindPortIP":false,"SwarmMode":false}"
weglot-drupal_traefik | time="2018-03-30T14:25:59Z" level=info msg="Starting server on :80"
WARNING: Connection pool is full, discarding connection: 192.168.99.100
weglot-drupal_traefik | time="2018-03-30T14:25:59Z" level=info msg="Starting server on :8080"
weglot-drupal_traefik | time="2018-03-30T14:25:59Z" level=info msg="Server configuration reloaded on :8080"
weglot-drupal_traefik | time="2018-03-30T14:25:59Z" level=info msg="Server configuration reloaded on :80"
weglot-drupal_traefik | time="2018-03-30T14:26:01Z" level=info msg="Server configuration reloaded on :80"
weglot-drupal_traefik | time="2018-03-30T14:26:01Z" level=info msg="Server configuration reloaded on :8080"
```

I have in my /etc/hosts : 
```
127.0.0.1 drupal.docker.localhost
```
