### ISSUE TITLE
Once I add my IP alias for xdebug I can't access my site

### ISSUE THREAD

**Issue by albertski** [wodby/docker4drupal#266]
I am trying to set up docker for xdebug testing.  When I run the command on my local (Not inside docker) `sudo ifconfig lo0 alias 10.254.254.254` I can't access my site anymore from a browser.  Has anyone run into this?

### docker-compose.yml
```
version: "2"

services:
  mariadb:
    image: wodby/mariadb:10.2-3.0.2
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}

    volumes:
      - ./mariadb-init:/docker-entrypoint-initdb.d # Place init .sql file(s) here.

  php:
    image: wodby/drupal-php:7.0-3.3.1
    environment:
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
      DB_HOST: ${DATABASE_HOST}
      DB_USER: ${DATABASE_USER}
      DB_PASSWORD: ${DATABASE_PASSWORD}
      DB_NAME: ${DATABASE_NAME}
      DB_DRIVER: mysql
      PHP_IDE_CONFIG: serverName=Docker
      PHP_XDEBUG: 1
      PHP_XDEBUG_IDEKEY: PHPSTORM
      PHP_XDEBUG_DEFAULT_ENABLE: 1
      PHP_XDEBUG_REMOTE_AUTOSTART: 1
      PHP_XDEBUG_REMOTE_CONNECT_BACK: 0 # This is needed to respect remote.host setting bellow
      PHP_XDEBUG_REMOTE_HOST: "10.254.254.254" # You will also need to 'sudo ifconfig lo0 alias 10.254.254.254'
    volumes:
     - ./:/var/www/html:cached # Docker-sync for macOS users

  nginx:
    image: wodby/drupal-nginx:8-1.13-2.4.2
    depends_on:
      - php
    environment:
      NGINX_STATIC_CONTENT_OPEN_FILE_CACHE: "off"
      NGINX_ERROR_LOG_LEVEL: debug
      NGINX_BACKEND_HOST: php
      NGINX_SERVER_ROOT: /var/www/html/web
    volumes_from:
      - php
    labels:
      - 'traefik.backend=${TRAEFIK_HOST}_nginx_1'
      - 'traefik.port=80'
      - 'traefik.frontend.rule=Host:${TRAEFIK_HOST}.test'
  mailhog:
    image: mailhog/mailhog
    labels:
      - 'traefik.backend=${TRAEFIK_HOST}_mailhog_1'
      - 'traefik.port=8025'
      - 'traefik.frontend.rule=Host:mailhog.${TRAEFIK_HOST}.text'

  adminer:
    image: wodby/adminer:4.3
    environment:
      ADMINER_SALT: adminer-salt
    labels:
      - 'traefik.backend=${TRAEFIK_HOST}_adminer_1'
      - 'traefik.port=9000'
      - 'traefik.frontend.rule=Host:adminer.${TRAEFIK_HOST}.test'
```

### Host OS 
macOS Sierra

### Docker info output
```
Containers: 65
 Running: 12
 Paused: 0
 Stopped: 53
Images: 36
Server Version: 17.12.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 89623f28b87a6004d4b785663257362d1658a729
runc version: b2567b37d7b75eb4cf325b77297b140ea686ce8f
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.60-linuxkit-aufs
Operating System: Docker for Mac
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.952GiB
Name: linuxkit-025000000001
ID: 2G5Z:OG5H:Z7TU:DQ4T:QCMZ:EYBQ:VTEV:WBKC:B7GB:7QFS:G6GP:FOOT
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 139
 Goroutines: 188
 System Time: 2018-03-31T18:49:25.238870168Z
 EventsListeners: 5
HTTP Proxy: docker.for.mac.http.internal:3128
HTTPS Proxy: docker.for.mac.http.internal:3129
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```
