### ISSUE TITLE
Requirements problem on Vanilla install

### ISSUE THREAD

**Issue by abutler3** [wodby/docker4drupal#269]
Using 5.0.4 to build a vanilla Drupal site, I get this screen
![screen shot 2018-04-05 at 9 00 38 am](https://user-images.githubusercontent.com/297967/38370534-f14be33a-38af-11e8-9492-c2250efaa601.png)

### Codebase
Built-in vanilla Drupal
  
### Host OS 
macOS Sierra

### Docker info output
```
# Containers: 6
 Running: 6
 Paused: 0
 Stopped: 0
Images: 13
Server Version: 18.03.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfd04396dc68220d1cecbe686a6cc3aa5ce3667c
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.87-linuxkit-aufs
Operating System: Docker for Mac
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.952GiB
Name: linuxkit-025000000001
ID: 5WLC:7HCL:AXRE:WCPL:PKJZ:CFUB:VYWU:HVGD:SDPF:LGD4:5IMG:ORPN
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 70
 Goroutines: 80
 System Time: 2018-04-05T13:53:16.859260734Z
 EventsListeners: 3
HTTP Proxy: docker.for.mac.http.internal:3128
HTTPS Proxy: docker.for.mac.http.internal:3129
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

### Docker compose file
```yml
# version: "2"

services:
  mariadb:
    image: wodby/mariadb:$MARIADB_TAG
    container_name: "${PROJECT_NAME}_mariadb"
    stop_grace_period: 30s
    environment:
      MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
      MYSQL_DATABASE: $DB_NAME
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASSWORD
    volumes:
      - ./mariadb-init:/docker-entrypoint-initdb.d # Place init .sql file(s) here.
#      - /path/to/mariadb/data/on/host:/var/lib/mysql # I want to manage volumes manually.

  php:
    image: wodby/drupal-php:$PHP_TAG
    container_name: "${PROJECT_NAME}_php"
    environment:
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
      DB_HOST: $DB_HOST
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
      DB_NAME: $DB_NAME
      DB_DRIVER: $DB_DRIVER
#      PHP_XDEBUG: 1
#      PHP_XDEBUG_DEFAULT_ENABLE: 1
#      PHP_XDEBUG_REMOTE_CONNECT_BACK: 0
#      PHP_XDEBUG_REMOTE_HOST: "10.254.254.254"
#      PHP_BLACKFIRE: 1
    volumes:
      - ./:/var/www/html
## For macOS users (https://wodby.com/stacks/drupal/docs/local/docker-for-mac/)
#      - ./:/var/www/html:cached # User-guided caching
#      - docker-sync:/var/www/html # Docker-sync
## For Xdebug profiler files
#      - files:/mnt/files

  nginx:
    image: wodby/drupal-nginx:$NGINX_TAG
    container_name: "${PROJECT_NAME}_nginx"
    depends_on:
      - php
    environment:
      NGINX_STATIC_CONTENT_OPEN_FILE_CACHE: "off"
      NGINX_ERROR_LOG_LEVEL: debug
      NGINX_BACKEND_HOST: php
      NGINX_SERVER_ROOT: /var/www/html/web
#      NGINX_DRUPAL_FILE_PROXY_URL: http://example.com
    volumes:
      - ./:/var/www/html
# For macOS users (https://wodby.com/stacks/drupal/docs/local/docker-for-mac/)
#      - ./:/var/www/html:cached # User-guided caching
#      - docker-sync:/var/www/html # Docker-sync
    labels:
      - 'traefik.backend=nginx'
      - 'traefik.port=80'
      - 'traefik.frontend.rule=Host:${PROJECT_BASE_URL}'

  mailhog:
    image: mailhog/mailhog
    container_name: "${PROJECT_NAME}_mailhog"
    labels:
      - 'traefik.backend=mailhog'
      - 'traefik.port=8025'
      - 'traefik.frontend.rule=Host:mailhog.${PROJECT_BASE_URL}'

#  postgres:
#    image: wodby/postgres:$POSTGRES_TAG
#    container_name: "${PROJECT_NAME}_postgres"
#    stop_grace_period: 30s
#    environment:
#      POSTGRES_PASSWORD: $DB_PASSWORD
#      POSTGRES_DB: $DB_NAME
#      POSTGRES_USER: $DB_USER
#    volumes:
#      - ./postgres-init:/docker-entrypoint-initdb.d # Place init file(s) here.
#      - /path/to/postgres/data/on/host:/var/lib/postgresql/data # I want to manage volumes manually.

#  apache:
#    image: wodby/php-apache:$APACHE_TAG
#    container_name: "${PROJECT_NAME}_apache"
#    depends_on:
#      - php
#    environment:
#      APACHE_LOG_LEVEL: debug
#      APACHE_BACKEND_HOST: php
#      APACHE_SERVER_ROOT: /var/www/html/web
#    volumes:
#      - ./:/var/www/html
## For macOS users (https://wodby.com/stacks/drupal/docs/local/docker-for-mac/)
##      - ./:/var/www/html:cached # User-guided caching
##      - docker-sync:/var/www/html # Docker-sync
#    labels:
#      - 'traefik.backend=apache'
#      - 'traefik.port=80'
#      - 'traefik.frontend.rule=Host:${PROJECT_BASE_URL}'

#  varnish:
#    image: wodby/drupal-varnish:$VARNISH_TAG
#    container_name: "${PROJECT_NAME}_varnish"
#    depends_on:
#      - nginx
#    environment:
#      VARNISH_SECRET: secret
#      VARNISH_BACKEND_HOST: nginx
#      VARNISH_BACKEND_PORT: 80
#    labels:
#      - 'traefik.backend=varnish'
#      - 'traefik.port=6081'
#      - 'traefik.frontend.rule=Host:varnish.${PROJECT_BASE_URL}'

#  redis:
#    container_name: "${PROJECT_NAME}_redis"
#    image: wodby/redis:$REDIS_TAG

#  adminer:
#    container_name: "${PROJECT_NAME}_adminer"
#    image: wodby/adminer:$ADMINER_TAG
#    environment:
#      ADMINER_SALT: adminer-salt
#    labels:
#      - 'traefik.backend=adminer'
#      - 'traefik.port=9000'
#      - 'traefik.frontend.rule=Host:adminer.${PROJECT_BASE_URL}'

  pma:
    image: phpmyadmin/phpmyadmin
    container_name: "${PROJECT_NAME}_pma"
    environment:
      PMA_HOST: $DB_HOST
      PMA_USER: $DB_USER
      PMA_PASSWORD: $DB_PASSWORD
      PHP_UPLOAD_MAX_FILESIZE: 1G
      PHP_MAX_INPUT_VARS: 1G
    labels:
      - 'traefik.backend=pma'
      - 'traefik.port=80'
      - 'traefik.frontend.rule=Host:pma.${PROJECT_BASE_URL}'

#  solr:
#    image: wodby/drupal-solr:$SOLR_TAG
#    container_name: "${PROJECT_NAME}_solr"
#    environment:
#      SOLR_HEAP: 1024m
#    labels:
#      - 'traefik.backend=solr'
#      - 'traefik.port=8983'
#      - 'traefik.frontend.rule=Host:solr.${PROJECT_BASE_URL}'

#  nodejs:
#    image: wodby/drupal-node:$DRUPAL_NODE_TAG
#    container_name: "${PROJECT_NAME}_drupal_nodejs"
#    environment:
#       NODE_SERVICE_KEY: node-service-key
#    labels:
#      - 'traefik.backend=nodejs'
#      - 'traefik.port=8080'
#      - 'traefik.frontend.rule=Host:nodejs.${PROJECT_BASE_URL}'
#    volumes:
#      - ./path/to/your/single-page-app:/app
#    command: sh -c 'npm install && npm run start'

#  memcached:
#    container_name: "${PROJECT_NAME}_memcached"
#    image: wodby/memcached:$MEMCACHED_TAG

#  rsyslog:
#    container_name: "${PROJECT_NAME}_rsyslog"
#    image: wodby/rsyslog:$RSYSLOG_TAG

#  athenapdf:
#    image: arachnysdocker/athenapdf-service:$ATHENAPDF_TAG
#    container_name: "${PROJECT_NAME}_athenapdf"
#    environment:
#      WEAVER_AUTH_KEY: weaver-auth-key
#      WEAVER_ATHENA_CMD: "athenapdf -S"
#      WEAVER_MAX_WORKERS: 10
#      WEAVER_MAX_CONVERSION_QUEUE: 50
#      WEAVER_WORKER_TIMEOUT: 90
#      WEAVER_CONVERSION_FALLBACK: "false"

#  node:
#    image: node:alpine
#    container_name: "${PROJECT_NAME}_node"
#    working_dir: /app
#    labels:
#      - 'traefik.backend=node'
#      - 'traefik.port=3000'
#      - 'traefik.frontend.rule=Host:front.${PROJECT_BASE_URL}'
#    expose:
#      - "3000"
#    volumes:
#      - ./path/to/your/single-page-app:/app
#    command: sh -c 'npm install && npm run start'

#  blackfire:
#    image: blackfire/blackfire
#    container_name: "${PROJECT_NAME}_blackfire"
#    environment:
#      BLACKFIRE_SERVER_ID: XXXXX
#      BLACKFIRE_SERVER_TOKEN: YYYYY

#  webgrind:
#    image: wodby/webgrind:$WEBGRIND_TAG
#    container_name: "${PROJECT_NAME}_webgrind"
#    environment:
#      WEBGRIND_PROFILER_DIR: /mnt/files/xdebug/profiler
#    labels:
#      - 'traefik.backend=webgrind'
#      - 'traefik.port=8080'
#      - 'traefik.frontend.rule=Host:webgrind.${PROJECT_BASE_URL}'
#    volumes:
#      - files:/mnt/files

  portainer:
    image: portainer/portainer
    container_name: "${PROJECT_NAME}_portainer"
    command: --no-auth -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - 'traefik.backend=portainer'
      - 'traefik.port=9000'
      - 'traefik.frontend.rule=Host:portainer.${PROJECT_BASE_URL}'

  traefik:
    image: traefik
    container_name: "${PROJECT_NAME}_traefik"
    command: -c /dev/null --web --docker --logLevel=INFO
    ports:
      - '8000:80'
#      - '8080:8080' # Dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

#volumes:
## Docker-sync for macOS users
#  docker-sync:
#    external: true
## For Xdebug profiler
#  files:

```

### Logs output
```
# Attaching to drzl_drupal8_project_nginx, drzl_drupal8_project_php, drzl_drupal8_project_traefik, drzl_drupal8_project_mailhog, drzl_drupal8_project_mariadb, drzl_drupal8_project_portainer
drzl_drupal8_project_nginx | 2018/04/05 13:44:46 [notice] 1#1: using the "epoll" event method
drzl_drupal8_project_nginx | 2018/04/05 13:44:46 [notice] 1#1: nginx/1.13.10
drzl_drupal8_project_nginx | 2018/04/05 13:44:46 [notice] 1#1: built by gcc 6.4.0 (Alpine 6.4.0) 
drzl_drupal8_project_nginx | 2018/04/05 13:44:46 [notice] 1#1: OS: Linux 4.9.87-linuxkit-aufs
drzl_drupal8_project_nginx | 2018/04/05 13:44:46 [notice] 1#1: getrlimit(RLIMIT_NOFILE): 1048576:1048576
drzl_drupal8_project_nginx | 2018/04/05 13:44:46 [notice] 1#1: start worker processes
drzl_drupal8_project_nginx | 2018/04/05 13:44:46 [notice] 1#1: start worker process 30
drzl_drupal8_project_nginx | 2018/04/05 13:44:46 [notice] 1#1: start worker process 31
drzl_drupal8_project_nginx | 172.21.0.5 - - [05/Apr/2018:13:45:48 +0000] "GET / HTTP/1.1" 302 324 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.1 Safari/605.1.15"
drzl_drupal8_project_nginx | 172.21.0.5 - - [05/Apr/2018:13:45:49 +0000] "GET /core/install.php HTTP/1.1" 200 4136 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.1 Safari/605.1.15"
drzl_drupal8_project_nginx | 2018/04/05 13:45:49 [info] 30#30: *6 client closed connection while waiting for request, client: 172.21.0.5, server: 0.0.0.0:80
drzl_drupal8_project_nginx | 172.21.0.5 - - [05/Apr/2018:13:45:55 +0000] "POST /core/install.php HTTP/1.1" 302 504 "http://drzl.docker.localhost:8000/core/install.php" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.1 Safari/605.1.15"
drzl_drupal8_project_nginx | 172.21.0.5 - - [05/Apr/2018:13:45:55 +0000] "GET /core/install.php?langcode=en HTTP/1.1" 200 2393 "http://drzl.docker.localhost:8000/core/install.php" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.1 Safari/605.1.15"
drzl_drupal8_project_nginx | 172.21.0.5 - - [05/Apr/2018:13:46:04 +0000] "POST /core/install.php?langcode=en HTTP/1.1" 302 588 "http://drzl.docker.localhost:8000/core/install.php?langcode=en" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.1 Safari/605.1.15"
drzl_drupal8_project_nginx | 172.21.0.5 - - [05/Apr/2018:13:46:04 +0000] "GET /core/install.php?langcode=en&profile=standard HTTP/1.1" 200 2868 "http://drzl.docker.localhost:8000/core/install.php?langcode=en" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.1 Safari/605.1.15"
drzl_drupal8_project_nginx | 172.21.0.5 - - [05/Apr/2018:13:50:09 +0000] "GET /core/install.php?langcode=en&profile=standard HTTP/1.1" 200 2868 "http://drzl.docker.localhost:8000/core/install.php?langcode=en" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.1 Safari/605.1.15"
drzl_drupal8_project_nginx | 172.21.0.5 - - [05/Apr/2018:13:50:13 +0000] "GET /core/install.php?langcode=en&profile=standard HTTP/1.1" 200 2868 "http://drzl.docker.localhost:8000/core/install.php?langcode=en&profile=standard" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/11.1 Safari/605.1.15"
drzl_drupal8_project_php | Current version of Drupal 8 is outdated (8.5.0), updating to 8.5.1...
drzl_drupal8_project_php | Complete! Drupal 8 has been successfully updated to 8.5.1
drzl_drupal8_project_php | [05-Apr-2018 13:44:50] NOTICE: fpm is running, pid 1
drzl_drupal8_project_php | [05-Apr-2018 13:44:50] NOTICE: ready to handle connections
drzl_drupal8_project_php | 172.21.0.7 -  05/Apr/2018:13:45:48 +0000 "GET /index.php" 302
drzl_drupal8_project_php | 172.21.0.7 -  05/Apr/2018:13:45:48 +0000 "GET /core/install.php" 200
drzl_drupal8_project_php | 172.21.0.7 -  05/Apr/2018:13:45:55 +0000 "POST /core/install.php" 302
drzl_drupal8_project_php | 172.21.0.7 -  05/Apr/2018:13:45:55 +0000 "GET /core/install.php" 200
drzl_drupal8_project_php | 172.21.0.7 -  05/Apr/2018:13:46:03 +0000 "POST /core/install.php" 302
drzl_drupal8_project_php | 172.21.0.7 -  05/Apr/2018:13:46:04 +0000 "GET /core/install.php" 200
drzl_drupal8_project_php | 172.21.0.7 -  05/Apr/2018:13:50:09 +0000 "GET /core/install.php" 200
drzl_drupal8_project_php | 172.21.0.7 -  05/Apr/2018:13:50:13 +0000 "GET /core/install.php" 200
drzl_drupal8_project_mailhog | 2018/04/05 13:44:45 Using in-memory storage
drzl_drupal8_project_mailhog | 2018/04/05 13:44:45 [SMTP] Binding to address: 0.0.0.0:1025
drzl_drupal8_project_mailhog | [HTTP] Binding to address: 0.0.0.0:8025
drzl_drupal8_project_mailhog | 2018/04/05 13:44:45 Serving under http://0.0.0.0:8025/
drzl_drupal8_project_mailhog | Creating API v1 with WebPath: 
drzl_drupal8_project_mailhog | Creating API v2 with WebPath: 
drzl_drupal8_project_mailhog | [APIv1] KEEPALIVE /api/v1/events
drzl_drupal8_project_mailhog | [APIv1] KEEPALIVE /api/v1/events
drzl_drupal8_project_mailhog | [APIv1] KEEPALIVE /api/v1/events
drzl_drupal8_project_mailhog | [APIv1] KEEPALIVE /api/v1/events
drzl_drupal8_project_mailhog | [APIv1] KEEPALIVE /api/v1/events
drzl_drupal8_project_mailhog | [APIv1] KEEPALIVE /api/v1/events
drzl_drupal8_project_mailhog | [APIv1] KEEPALIVE /api/v1/events
drzl_drupal8_project_mailhog | [APIv1] KEEPALIVE /api/v1/events
drzl_drupal8_project_mailhog | [APIv1] KEEPALIVE /api/v1/events
drzl_drupal8_project_mailhog | [APIv1] KEEPALIVE /api/v1/events
drzl_drupal8_project_mailhog | [APIv1] KEEPALIVE /api/v1/events
drzl_drupal8_project_mailhog | [APIv1] KEEPALIVE /api/v1/events
drzl_drupal8_project_mariadb | Initializing database
drzl_drupal8_project_mariadb | 
drzl_drupal8_project_mariadb | PLEASE REMEMBER TO SET A PASSWORD FOR THE MariaDB root USER !
drzl_drupal8_project_mariadb | To do so, start the server, then issue the following commands:
drzl_drupal8_project_mariadb | 
drzl_drupal8_project_mariadb | '/usr/bin/mysqladmin' -u root password 'new-password'
drzl_drupal8_project_mariadb | '/usr/bin/mysqladmin' -u root -h  password 'new-password'
drzl_drupal8_project_mariadb | 
drzl_drupal8_project_mariadb | Alternatively you can run:
drzl_drupal8_project_mariadb | '/usr/bin/mysql_secure_installation'
drzl_drupal8_project_mariadb | 
drzl_drupal8_project_mariadb | which will also give you the option of removing the test
drzl_drupal8_project_mariadb | databases and anonymous user created by default.  This is
drzl_drupal8_project_mariadb | strongly recommended for production servers.
drzl_drupal8_project_mariadb | 
drzl_drupal8_project_mariadb | See the MariaDB Knowledgebase at http://mariadb.com/kb or the
drzl_drupal8_project_mariadb | MySQL manual for more instructions.
drzl_drupal8_project_mariadb | 
drzl_drupal8_project_mariadb | Please report any problems at http://mariadb.org/jira
drzl_drupal8_project_mariadb | 
drzl_drupal8_project_mariadb | The latest information about MariaDB is available at http://mariadb.org/.
drzl_drupal8_project_mariadb | You can find additional information about the MySQL part at:
drzl_drupal8_project_mariadb | http://dev.mysql.com
drzl_drupal8_project_mariadb | Consider joining MariaDB's strong and vibrant community:
drzl_drupal8_project_mariadb | https://mariadb.org/get-involved/
drzl_drupal8_project_mariadb | 
drzl_drupal8_project_mariadb | Database initialized
drzl_drupal8_project_mariadb | MySQL init process in progress...
drzl_drupal8_project_mariadb | 2018-04-05 13:44:48 140688171891592 [Note] mysqld (mysqld 10.2.14-MariaDB) starting as process 101 ...
drzl_drupal8_project_mariadb | 2018-04-05 13:44:48 140688171891592 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
drzl_drupal8_project_mariadb | 2018-04-05 13:44:48 140688171891592 [Note] InnoDB: Uses event mutexes
drzl_drupal8_project_mariadb | 2018-04-05 13:44:48 140688171891592 [Note] InnoDB: Compressed tables use zlib 1.2.11
drzl_drupal8_project_mariadb | 2018-04-05 13:44:48 140688171891592 [Note] InnoDB: Using Linux native AIO
drzl_drupal8_project_mariadb | 2018-04-05 13:44:48 140688171891592 [Note] InnoDB: Number of pools: 1
drzl_drupal8_project_mariadb | 2018-04-05 13:44:48 140688171891592 [Note] InnoDB: Using SSE2 crc32 instructions
drzl_drupal8_project_mariadb | 2018-04-05 13:44:48 140688171891592 [Note] InnoDB: Initializing buffer pool, total size = 1G, instances = 4, chunk size = 128M
drzl_drupal8_project_mariadb | 2018-04-05 13:44:48 140688171891592 [Note] InnoDB: Completed initialization of buffer pool
drzl_drupal8_project_mariadb | 2018-04-05 13:44:48 140686697032424 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
drzl_drupal8_project_mariadb | 2018-04-05 13:44:48 140688171891592 [Note] InnoDB: Highest supported file format is Barracuda.
drzl_drupal8_project_mariadb | 2018-04-05 13:44:48 140688171891592 [Note] InnoDB: 128 out of 128 rollback segments are active.
drzl_drupal8_project_mariadb | 2018-04-05 13:44:48 140688171891592 [Note] InnoDB: Creating shared tablespace for temporary tables
drzl_drupal8_project_mariadb | 2018-04-05 13:44:48 140688171891592 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
drzl_drupal8_project_mariadb | 2018-04-05 13:44:48 140688171891592 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
drzl_drupal8_project_mariadb | 2018-04-05 13:44:48 140688171891592 [Note] InnoDB: Waiting for purge to start
drzl_drupal8_project_mariadb | 2018-04-05 13:44:48 140688171891592 [Note] InnoDB: 5.7.21 started; log sequence number 1619994
drzl_drupal8_project_mariadb | 2018-04-05 13:44:48 140686726032104 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
drzl_drupal8_project_mariadb | 2018-04-05 13:44:48 140688171891592 [Note] Plugin 'FEEDBACK' is disabled.
drzl_drupal8_project_mariadb | 2018-04-05 13:44:48 140688171891592 [Warning] 'user' entry 'root@dfc3e2341e20' ignored in --skip-name-resolve mode.
drzl_drupal8_project_mariadb | 2018-04-05 13:44:48 140688171891592 [Warning] 'user' entry '@dfc3e2341e20' ignored in --skip-name-resolve mode.
drzl_drupal8_project_mariadb | 2018-04-05 13:44:48 140688171891592 [Warning] 'proxies_priv' entry '@% root@dfc3e2341e20' ignored in --skip-name-resolve mode.
drzl_drupal8_project_mariadb | 2018-04-05 13:44:48 140686726032104 [Note] InnoDB: Buffer pool(s) load completed at 180405 13:44:48
drzl_drupal8_project_mariadb | 2018-04-05 13:44:48 140688171891592 [Note] Reading of all Master_info entries succeded
drzl_drupal8_project_mariadb | 2018-04-05 13:44:48 140688171891592 [Note] Added new Master_info '' to hash table
drzl_drupal8_project_mariadb | 2018-04-05 13:44:48 140688171891592 [Note] mysqld: ready for connections.
drzl_drupal8_project_mariadb | Version: '10.2.14-MariaDB'  socket: '/var/run/mysqld/mysqld.sock'  port: 0  MariaDB Server
drzl_drupal8_project_mariadb | 2018-04-05 13:44:51 140686716812008 [Warning] 'proxies_priv' entry '@% root@dfc3e2341e20' ignored in --skip-name-resolve mode.
drzl_drupal8_project_mariadb | 2018-04-05 13:44:51 140686716812008 [Warning] 'proxies_priv' entry '@% root@dfc3e2341e20' ignored in --skip-name-resolve mode.
drzl_drupal8_project_mariadb | 
drzl_drupal8_project_mariadb | 2018-04-05 13:44:51 140686716492520 [Note] mysqld (initiated by: unknown): Normal shutdown
drzl_drupal8_project_mariadb | 2018-04-05 13:44:51 140686716492520 [Note] Event Scheduler: Purging the queue. 0 events
drzl_drupal8_project_mariadb | 2018-04-05 13:44:51 140686726503144 [Note] InnoDB: FTS optimize thread exiting.
drzl_drupal8_project_mariadb | 2018-04-05 13:44:51 140686716492520 [Note] InnoDB: Starting shutdown...
drzl_drupal8_project_mariadb | 2018-04-05 13:44:51 140686726032104 [Note] InnoDB: Dumping buffer pool(s) to /var/lib/mysql/ib_buffer_pool
drzl_drupal8_project_mariadb | 2018-04-05 13:44:51 140686726032104 [Note] InnoDB: Buffer pool(s) dump completed at 180405 13:44:51
drzl_drupal8_project_mariadb | 2018-04-05 13:44:52 140686716492520 [Note] InnoDB: Shutdown completed; log sequence number 1620022
drzl_drupal8_project_mariadb | 2018-04-05 13:44:52 140686716492520 [Note] InnoDB: Removed temporary tablespace data file: "ibtmp1"
drzl_drupal8_project_mariadb | 2018-04-05 13:44:52 140686716492520 [Note] mysqld: Shutdown complete
drzl_drupal8_project_mariadb | 
drzl_drupal8_project_mariadb | 
drzl_drupal8_project_mariadb | MySQL init process done. Ready for start up.
drzl_drupal8_project_mariadb | 
drzl_drupal8_project_mariadb | 2018-04-05 13:44:52 139722724776840 [Note] mysqld (mysqld 10.2.14-MariaDB) starting as process 1 ...
drzl_drupal8_project_mariadb | 2018-04-05 13:44:52 139722724776840 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
drzl_drupal8_project_mariadb | 2018-04-05 13:44:52 139722724776840 [Note] InnoDB: Uses event mutexes
drzl_drupal8_project_mariadb | 2018-04-05 13:44:52 139722724776840 [Note] InnoDB: Compressed tables use zlib 1.2.11
drzl_drupal8_project_mariadb | 2018-04-05 13:44:52 139722724776840 [Note] InnoDB: Using Linux native AIO
drzl_drupal8_project_mariadb | 2018-04-05 13:44:52 139722724776840 [Note] InnoDB: Number of pools: 1
drzl_drupal8_project_mariadb | 2018-04-05 13:44:52 139722724776840 [Note] InnoDB: Using SSE2 crc32 instructions
drzl_drupal8_project_mariadb | 2018-04-05 13:44:52 139722724776840 [Note] InnoDB: Initializing buffer pool, total size = 1G, instances = 4, chunk size = 128M
drzl_drupal8_project_mariadb | 2018-04-05 13:44:52 139722724776840 [Note] InnoDB: Completed initialization of buffer pool
drzl_drupal8_project_mariadb | 2018-04-05 13:44:52 139721251138280 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
drzl_drupal8_project_mariadb | 2018-04-05 13:44:52 139722724776840 [Note] InnoDB: Highest supported file format is Barracuda.
drzl_drupal8_project_mariadb | 2018-04-05 13:44:52 139722724776840 [Note] InnoDB: 128 out of 128 rollback segments are active.
drzl_drupal8_project_mariadb | 2018-04-05 13:44:52 139722724776840 [Note] InnoDB: Creating shared tablespace for temporary tables
drzl_drupal8_project_mariadb | 2018-04-05 13:44:52 139722724776840 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
drzl_drupal8_project_mariadb | 2018-04-05 13:44:52 139722724776840 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
drzl_drupal8_project_mariadb | 2018-04-05 13:44:52 139722724776840 [Note] InnoDB: Waiting for purge to start
drzl_drupal8_project_mariadb | 2018-04-05 13:44:53 139722724776840 [Note] InnoDB: 5.7.21 started; log sequence number 1620022
drzl_drupal8_project_mariadb | 2018-04-05 13:44:53 139721278917352 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
drzl_drupal8_project_mariadb | 2018-04-05 13:44:53 139721278917352 [Note] InnoDB: Buffer pool(s) load completed at 180405 13:44:53
drzl_drupal8_project_mariadb | 2018-04-05 13:44:53 139722724776840 [Note] Plugin 'FEEDBACK' is disabled.
drzl_drupal8_project_mariadb | 2018-04-05 13:44:53 139722724776840 [Note] Server socket created on IP: '0.0.0.0'.
drzl_drupal8_project_mariadb | 2018-04-05 13:44:53 139722724776840 [Warning] 'proxies_priv' entry '@% root@dfc3e2341e20' ignored in --skip-name-resolve mode.
drzl_drupal8_project_mariadb | 2018-04-05 13:44:53 139722724776840 [Note] Reading of all Master_info entries succeded
drzl_drupal8_project_mariadb | 2018-04-05 13:44:53 139722724776840 [Note] Added new Master_info '' to hash table
drzl_drupal8_project_mariadb | 2018-04-05 13:44:53 139722724776840 [Note] mysqld: ready for connections.
drzl_drupal8_project_mariadb | Version: '10.2.14-MariaDB'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MariaDB Server
drzl_drupal8_project_portainer | 2018/04/05 13:44:46 Starting Portainer 1.16.4 on :9000
drzl_drupal8_project_traefik | time="2018-04-05T13:44:45Z" level=info msg="Using TOML configuration file /dev/null" 
drzl_drupal8_project_traefik | time="2018-04-05T13:44:45Z" level=warning msg="web provider configuration is deprecated, you should use these options : api, rest provider, ping and metrics" 
drzl_drupal8_project_traefik | time="2018-04-05T13:44:45Z" level=info msg="Traefik version v1.5.4 built on 2018-03-15_01:35:21PM" 
drzl_drupal8_project_traefik | time="2018-04-05T13:44:45Z" level=info msg="
drzl_drupal8_project_traefik | Stats collection is disabled.
drzl_drupal8_project_traefik | Help us improve Traefik by turning this feature on :)
drzl_drupal8_project_traefik | More details on: https://docs.traefik.io/basics/#collected-data
drzl_drupal8_project_traefik | " 
drzl_drupal8_project_traefik | time="2018-04-05T13:44:45Z" level=info msg="Preparing server http &{Network: Address::80 TLS:<nil> Redirect:<nil> Auth:<nil> WhitelistSourceRange:[] Compress:false ProxyProtocol:<nil> ForwardedHeaders:0xc4203489e0} with readTimeout=0s writeTimeout=0s idleTimeout=3m0s" 
drzl_drupal8_project_traefik | time="2018-04-05T13:44:45Z" level=info msg="Preparing server traefik &{Network: Address::8080 TLS:<nil> Redirect:<nil> Auth:<nil> WhitelistSourceRange:[] Compress:false ProxyProtocol:<nil> ForwardedHeaders:0xc420348a00} with readTimeout=0s writeTimeout=0s idleTimeout=3m0s" 
drzl_drupal8_project_traefik | time="2018-04-05T13:44:45Z" level=info msg="Starting server on :80" 
drzl_drupal8_project_traefik | time="2018-04-05T13:44:45Z" level=info msg="Starting server on :8080" 
drzl_drupal8_project_traefik | time="2018-04-05T13:44:45Z" level=info msg="Starting provider *docker.Provider {"Watch":true,"Filename":"","Constraints":null,"Trace":false,"DebugLogGeneratedTemplate":false,"Endpoint":"unix:///var/run/docker.sock","Domain":"","TLS":null,"ExposedByDefault":true,"UseBindPortIP":false,"SwarmMode":false}" 
drzl_drupal8_project_traefik | time="2018-04-05T13:44:45Z" level=info msg="Server configuration reloaded on :80" 
drzl_drupal8_project_traefik | time="2018-04-05T13:44:45Z" level=info msg="Server configuration reloaded on :8080" 
drzl_drupal8_project_traefik | time="2018-04-05T13:44:47Z" level=info msg="Server configuration reloaded on :80" 
drzl_drupal8_project_traefik | time="2018-04-05T13:44:47Z" level=info msg="Server configuration reloaded on :8080" 

```
