### ISSUE TITLE
About Xdebug

### ISSUE THREAD

**Issue by walkero-gr** [Wodby/docker4drupal#27]
At the website you mention that if we want to use xdebug, we should uncomment the following line in the compose file:
#    XDEBUG_CONFIG: xdebug.remote_autostart=1

Unfortunately, this line doesn't exist in the compose file. We must place it under the PHP docker?
Can you provide any info how I could use xdebug with an IDE, for example NetBeans?

Thank you again for your help.

**Comment by PavelPrischepa** [comment]
Hi, @walkero-gr 

Thank you for the notice. The option **xdebug.remote_autostart=1** was deprecated. I'll update the doc. 
So, you should set **1** for the environment variable **PHP_XDEBUG_ENABLED** in the php container.

You can use any IDE with XDebug support. I have no experience in Netbeans+Xdebug, so you should try to check the following link:

- http://wiki.netbeans.org/HowToConfigureXDebug
- https://netbeans.org/kb/docs/php/debugging.html

**Comment by walkero-gr** [comment]
Thank you for your fast reply.
Can we use xdebug profiler? Is it possible to add the following parameters to xdebug from the compose file?
xdebug.profiler_enable = 1
xdebug.profiler_output_dir = /var/www/html/.profiler/
xdebug.profiler_output_name = "cachegrind.out.%t-%s"

I tried to add them in the xdebug.ini file manually under the /etc/php5/conf.d folder, but unfortunately no files are created. I tried to restart the containers before I test it.

Any idea?

**Comment by walkero-gr** [comment]
The reason I didn't get any files created by the profiler is that I should chmod to 777 of the output folder. Now it works just fine.

It would be nice though to have the ability to set these parameters through the the compose file, so that when we do any update to the container, the config of xdebug won't change.

**Comment by PavelPrischepa** [comment]
Did you try to specify all options in a line?
`XDEBUG_CONFIG: "profiler_enable = 1 profiler_output_dir = /var/www/html/.profiler/ ..."`

Also, you can override any file by a volume, for example:
```
- ./my-xdebug.conf:/etc/php5/conf.d/xdebug.ini
```

**Comment by walkero-gr** [comment]
Thanks Pavel.. I will try to set it in the compose file, and if it fails I will try the second solution.
Thanks again for your help.

**Comment by walkero-gr** [comment]
Tried the first solution, but unfortunately nothing is added in the xdebug.ini
I also tried with only the following and nothing changed.
`XDEBUG_CONFIG: profiler_enable = 1`
Is there a possibility to have this Enviroment variables disabled ?

**Comment by PavelPrischepa** [comment]
@walkero-gr I've tried the following configuration and it works well for me:
```
  php:
    image: wodby/drupal-php:7.0
    environment:
      PHP_SITE_NAME: dev
      PHP_HOST_NAME: localhost:8000
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
      PHP_XDEBUG_ENABLED: 1
      XDEBUG_CONFIG: "profiler_enable=1 profiler_output_dir=/var/www/html/.profiler/"
    volumes:
      - ./:/var/www/html
```
Be sure, you enabled XDebug via `PHP_XDEBUG_ENABLED: 1`.
