### ISSUE TITLE
wodby/node: sh: gulp: not found

### ISSUE THREAD

**Issue by xdevelx** [wodby/docker4drupal#271]
### Codebase
Built-in mounted codebase Drupal 8 (drupal-composer/drupal-project)
  
### Host OS 
Ubuntu 16.04

### Docker info output

```
Containers: 42
 Running: 7
 Paused: 0
 Stopped: 35
Images: 22
Server Version: 18.03.0-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 275
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: cfd04396dc68220d1cecbe686a6cc3aa5ce3667c
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.13.0-38-generic
Operating System: Ubuntu 16.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 8
Total Memory: 15.65GiB
Name: 
ID: ZLW3:K3UL:QVOB:KIUX:4LMT:WBZ3:FP46:6VXW:2VOU:MBGJ:SXI4:Z2SZ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support
```

### Docker compose file
```

version: "2"

services:
  mariadb:
    image: wodby/mariadb:$MARIADB_TAG
    container_name: "${PROJECT_NAME}_mariadb"
    stop_grace_period: 30s
    environment:
      MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
      MYSQL_DATABASE: $DB_NAME
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASSWORD
#    volumes:
#      - ./mariadb-init:/docker-entrypoint-initdb.d # Place init .sql file(s) here.
#      - /path/to/mariadb/data/on/host:/var/lib/mysql # I want to manage volumes manually.

  php:
    image: wodby/drupal-php:$PHP_TAG
    container_name: "${PROJECT_NAME}_php"
    environment:
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
      DB_HOST: $DB_HOST
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
      DB_NAME: $DB_NAME
      DB_DRIVER: $DB_DRIVER
    volumes:
      - ./:/var/www/html

  nginx:
    image: wodby/drupal-nginx:$NGINX_TAG
    container_name: "${PROJECT_NAME}_nginx"
    depends_on:
      - php
    environment:
      NGINX_STATIC_CONTENT_OPEN_FILE_CACHE: "off"
      NGINX_ERROR_LOG_LEVEL: debug
      NGINX_BACKEND_HOST: php
      NGINX_SERVER_ROOT: /var/www/html/web
#      NGINX_DRUPAL_FILE_PROXY_URL: http://example.com
    volumes:
      - ./:/var/www/html
    labels:
      - 'traefik.backend=nginx'
      - 'traefik.port=80'
      - 'traefik.frontend.rule=Host:${PROJECT_BASE_URL}'

  mailhog:
    image: mailhog/mailhog
    container_name: "${PROJECT_NAME}_mailhog"
    labels:
      - 'traefik.backend=mailhog'
      - 'traefik.port=8025'
      - 'traefik.frontend.rule=Host:mailhog.${PROJECT_BASE_URL}'

  node:
    image: wodby/node
    container_name: "${PROJECT_NAME}_node"
    working_dir: /var/www/html
    labels:
      - 'traefik.backend=node'
      - 'traefik.port=3000'
      - 'traefik.frontend.rule=Host:front.${PROJECT_BASE_URL}'
    expose:
      - "3000"
    volumes:
      - ./:/var/www/html
    tty: true
#    command: sh -c 'npm i -g gulp-cli'



  portainer:
    image: portainer/portainer
    container_name: "${PROJECT_NAME}_portainer"
    command: --no-auth -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - 'traefik.backend=portainer'
      - 'traefik.port=9000'
      - 'traefik.frontend.rule=Host:portainer.${PROJECT_BASE_URL}'

  traefik:
    image: traefik
    container_name: "${PROJECT_NAME}_traefik"
    command: -c /dev/null --web --docker --logLevel=INFO
    ports:
      - '8000:80'
#      - '8080:8080' # Dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock


```

Решил воспользоваться в wodby/docker4drupal nodejs для использования gulp. Изначально использовал контейнер node:alpine - там возникли проблемы с правами в системе , контейнер запускается от root и локальные файлы и папки тоже создает под рутом. Попробовал контейнер wodby/node - там юзер node (uid 1000) как и в ubuntu, c правами стало все норм. Но при попытке установки у пользователя node нет прав для установки глобальных  пакетов (типа **gulp-cli**). Через sudo не могу установить - у node не даже пароля.
Через yarn поставил глобально gulp-cli (поставился в _~/.config/yarn/global/node_modules/gulp-cli/bin/gulp.js_). В консоли (_docker-compose exec node sh_) ввожу 
```
gulp 
sh: gulp: not found
```
 хотя npm, yarn, node команды имеютcя.
C permissions для npm глобальной установки решил - ставлю глобальные пакеты в домашнюю папку в директорию _~/.npm-global_ (взято из https://docs.npmjs.com/getting-started/fixing-npm-permissions), но после установки все равно 
`sh: gulp: not found`
~/.npm-global экспортируется вручную в PATH в ~/.profile, но в alpine linix ~/.profile не прогружается автоматом при старте пользовательского сеанса. После перезагрузки в PATH только _/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin_ (gulp выполняется только после команды `source ~/.profile`).
Как использовать gulp в контейнере wodby/node?

**P.S.** Извиняюсь за русский язык в описании issue.
