### ISSUE TITLE
sshd works only with older PHP tags

### ISSUE THREAD

**Issue by Vacilando** [wodby/docker4drupal#272]
### Works with an old PHP tag e.g.
```
  sshd:
    image: wodby/drupal-php:7.1-2.4.3
    container_name: "${PROJECT_NAME}_sshd"
    command: /usr/sbin/sshd -De
    environment:
      SSH_PUBLIC_KEYS: |-
        ["MYKEY"]
    volumes:
      - ./:/var/www/html
      - ../MYKEYLOCATION:/home/www-data/.ssh/id_rsa
    ports:
      - '2222:22'
    depends_on:
      - php
```

### Does NOT work with a newer tag from docker-compose.yml e.g. "7.1-dev-4.2.5"
```
  sshd:
    image: wodby/drupal-php:$PHP_TAG
    container_name: "${PROJECT_NAME}_sshd"
    command: /usr/sbin/sshd -De
    environment:
      SSH_PUBLIC_KEYS: |-
        ["MYKEY"]
    volumes:
      - ./:/var/www/html
      - ../MYKEYLOCATION:/home/www-data/.ssh/id_rsa
    ports:
      - '2222:22'
    depends_on:
      - php
```

The log message is:

> Could not load host key: /etc/ssh/ssh_host_rsa_key
