### ISSUE TITLE
File Permission on Windows 10 in /files

### ISSUE THREAD

**Issue by joergLin** [wodby/docker4drupal#29]
I'm using the Windows 10 Docker App, getting evertything to run except uploading files via Drupal backend. The first file ever will upload and put in to the subfolder e.g. 2016-08. Afterwards no other file can be uploaded. So i guess it's a problem with file permissions/user id, but i don't find a way to do anything about it, like the chgrp command suggested for Linux envoirement. Is there any trick to do?

**Comment by hrdcdr** [comment]
Hello! It seems to be the problem of docker for windows. The owner group of `sites/default/files` must be `www-data`, but commands like chgrp, chown, chmod do not work in mounted volumes (see docker/for-win#39). As here and now solution you can build your own `drupal-nginx`, `drupal-php` images and replace `www-data` and `nginx` users by `root` in configs to run nginx and php-fpm under the root user.

**Comment by PavelPrischepa** [comment]
I'm going to close the issue due to no activity.

@joergLin btw it might be helpful for you https://github.com/Wodby/docker4drupal/issues/35#issuecomment-253806588

**Comment by codeyy** [comment]
I'm afraid this still doesn't work in Windows 10. I've tried a lot of things, but write permissions are impossible to get when it comes to mounted volumes.

I even ran into [these docker images](https://hub.docker.com/u/meatsack/), which seem to be based on the Wodby images, but they also don't work.

Or am I missing something?

**Comment by joergLin** [comment]
I'm sorry i didn't reply.
The problem was, every file written and folder created by a process in a Docker Container on Windows ends up being owned by root (inside Docker, physicially owned by the user-credentials you set in the Docker settings), no matter which user runs the process. So after user www-data creates a folder, it does not have permission to write into the same folder anymore.
I ended up creating my own base image with nginx+php7 where i made sure everything runs as root, which needed some research. Might be not the best idea, but i currently have a working local Environment on Windows 10, even with XDebug running. From there I deploy to Linux machines via git. I don't have access to the Dockerfiles right now to give some more hints, but it is possible!

**Comment by codeyy** [comment]
Any chance you chould share it, I'm not really good with that part I'm afraid...

**Comment by bahuma20** [comment]
I have exactly the same problem as @joergLin 
I upload an image, it works. I try to upload another image, it doesn't.
So this issue should not be closed... @PavelPrischepa

**Comment by codeyy** [comment]
What @hrdcdr describes is the perfect description of the problem. I wish I had the time and/or the knowledge to make Windows docker images, I'm still hoping someone will share them.

**Comment by artemboyko43** [comment]
My friend have the same problem on Windows 10 :(, 
any news here?

**Comment by joergLin** [comment]
Well, halfway there. Based on the great effort the Wodby-Images provide, I can get the files to upload and stored in files/, but the GD-Library is not able to create the image-styles of jpgs. (PNG works...)
In the php-fpm.conf of the wodby/drupal-php image you can set the php user to root:
```php
user = root
group = root
listen = [::]:9000
listen.owner = root
listen.group = root
```
and allow php to start as root in the docker-entrypoint.sh
```` sh
exec php-fpm --allow-to-run-as-root
````

Didn't have time to try to override this from a simple Dockerfile to share with you and look further into the gd-lib Problem, but maybe someone can use this information as a headstart.

**Comment by webdobe** [comment]
I am dealing with file issues for image styles generating on linux.  I have tried making the directory have same permissions 82:alpine-www-data as the container but no dice.

**Comment by csandanov** [comment]
@webdobe try adding a group with id 82 on your host machine and add your user there

**Comment by lcube45** [comment]
I've struggling with this issue for a while (first upload works but others failed, permissions issue)

Here is my setup 
- windows 10
- docker for windows
- docker compose
- drupal 8

I'm not using wodby image (even if there are really nice), just a simple docker compose file referencing apache:php-7.1 and postgresql:9.6 official image. I'm sharing a host folder to a container (.:/var/www/html).

After opening a shell in the apache/php container everything is executed as root and default permissions are 755. Official documentation seems pretty clear about it... (https://docs.docker.com/docker-for-windows/faqs/#can-i-change-permissions-on-shared-volumes-for-container-specific-deployment-requirements) 

I've been testing a lot of things (unison, docker-sync, run useradd, ...) with no full success on my dev environment.

I did find a simple solution while reading again docker compose reference. It's not perfect, i'm always root which is not perfect but acceptable for dev environment. It's group_add option !!!

https://docs.docker.com/compose/compose-file/compose-file-v2/#group_add

`
version: '2'
services:
  web:
    image: apache:php-7.1
    volumes:
     - .:/var/www/html
    group_add:
     - www-data
`

With this trick i'm adding my current executing user (root) as a member of the www-data group, so now when you're uploading files in drupal no exception raised.

Not perfect but functional

Hope this help

**Comment by LoicLEMEUT** [comment]
Hi,

Thanks for your answer, but it doesn't works for me... I have a strange problem in my Drupal. I use Devel for write this PHP code:

`$directory = rtrim('public://');
echo $directory."<br>";
var_dump(file_exists($directory));
var_dump(is_writable($directory));

echo '<br><br>';

$directory = rtrim('sites/default/files');
echo $directory."<br>";
var_dump(file_exists($directory));
var_dump(is_writable($directory));`

And that's return this:

`public://
bool(true)
bool(false)


sites/default/files
bool(true)
bool(true)`

My public directory is well "sites/default/files".

And I can create folder, create files in folder via Devel. But I have the same problem than https://github.com/wodby/docker4drupal/issues/29#issuecomment-269462755

Need help :) Thanks !

**Comment by LoicLEMEUT** [comment]
I all,

Read these issues...

The file_prepare_directory() function fails to detect write permissions for stream wrappers when using NFS.
https://www.drupal.org/node/2018947

file_prepare_directory() / is_writable() on Linux don't support ACLs
https://www.drupal.org/node/1333390

./sites/default/files directory permission check is incorrect during install AND status report
https://www.drupal.org/node/944582


My problemd is solved thanks to this patch: https://www.drupal.org/files/issues/sites_default_files-944582-120.patch

GL

Enjoy !

**Comment by Max-Zviagintsev** [comment]
LoicLEMEUT, thanks, your patch works!
At the same time, it broke admin interface (Drupal 8.3.6) - "Add field" button disappeared. I'm writing manually /add-field now in the URL field.
Hope they fix this permission issue in the future releases.

**Comment by kevin-coyle** [comment]
A solution that I found works to this is to basically exclude the sites/default/files from the mounted volume and create another named volume. For example:

```
volumes:
  drupal_files:
services:
  php:
    volumes:
      - .:/var/www/html
      - drupal_files:/var/www/html/web/sites/default/files
```

**Comment by florentcm** [comment]
Thanks @LoicLEMEUT ! Your patch is neat!

**Comment by sameronline** [comment]
I finally figured out the easiest and best way to resolve this on windows 10, adding these lines to the php service will resolve the issue

```yaml
  php:
    image: wodby/drupal-php:5.6
    user: root
    command: "php-fpm -R"
    environment:
      PHP_FPM_USER: root
      PHP_FPM_GROUP: root
```

full example of my current php services


```yaml
version: "2"
  php:
    image: wodby/drupal-php:5.6
    # windows 10 user
    user: root
    command: "php-fpm -R"
    environment:
      PHP_FPM_USER: root
      PHP_FPM_GROUP: root
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
      DB_HOST: mariadb
      DB_USER: drupal
      DB_PASSWORD: drupal
      DB_NAME: drupal
      DB_DRIVER: mysql
      PHP_XDEBUG: 1
      PHP_XDEBUG_DEFAULT_ENABLE: 1
      PHP_XDEBUG_REMOTE_CONNECT_BACK: 0
      PHP_XDEBUG_REMOTE_HOST: "10.0.75.1"
      PHP_XDEBUG_PROFILER_OUTPUT_DIR: /mnt/files/xdebug/profiler
      PHP_XDEBUG_TRACE_OUTPUT_DIR: /mnt/files/xdebug/traces
    volumes:
      - .:/var/www/html
## For Xdebug profiler files
      - ./docker-runtime/files:/mnt/files
```

Should not we include this into Windows section at https://wodby.com/stacks/drupal/docs/local/permissions/ ?

**Comment by pedro-p** [comment]
@sameronline thanks for your solution it works for me and for one of my colleagues too.

**Comment by sameronline** [comment]
Another tip (If you don't want to commit these changes to the docker-compose file), simply create a new docker-compose.override.yml and use the following:

```yaml
version: "2"
services:
  php:
    # windows 10 permission fix
    user: root
    command: "php-fpm -R"
    environment:
      PHP_FPM_USER: root
      PHP_FPM_GROUP: root
```

This way you could easily isolate the fix to your local machine only (after you gitignore docker-compose.override.yml)
