### ISSUE TITLE
More Multisite Questions

### ISSUE THREAD

**Issue by SummittDweller** [wodby/docker4drupal#299]
I now have a D4D local/dev environment fronted by Traefik with single Portainer and Mailhog containers to manage a combined Drupal 7 and Drupal 8 pair of "default" sites.  I'd like to introduce Drupal multisite capabilities into at least the D8 portion of the environment.  

From Issue #69 I see the recommended way to introduce multisite is to create multiple *mariadb* containers, one for each site, and point each site's *settings.php* file to its own database host/container.  So, do I also need a separate PHP container for each site?  I'm asking because in the latest D4D environment the *php* container includes env variables that reference database credentials, and the *php* container depends on *mariadb* too.  

My other thought... perhaps I should just stick with a single *mariadb* and *php* pair of containers, and vary the database table name "prefix" for each site.  But might I see a significant performance hit by doing so? 

In essence, I'm looking for any available and current multisite advice I can find from the community.  Has anyone got a working multisite instance in Drupal 8 that they would care to share?  Is there an online discussion apart from this Issues queue that might help?  Thanks in advance.

**Comment by SummittDweller** [comment]
OK, I've given up on the notion of having a single *mariadb* and *php* pair coupled with prefixing table names for each site...I tried but could not make it work, probably because I'm also trying to mix a combination of a Drupal 8 "vanilla" site with some existing codebase sites.

Anyway, I have multisite working per recommendations in Issue #6 now, but I'm __still interested in how/if I might streamline things a bit more?__  The only drawback at this point is that I'm not really using Drupal's "multisite" capability, each of my Drupal 8 sites now has it's own *mariadb*, *php*, and *nginx* containers.   The whole thing currently looks like this from `docker ps`:

```
CONTAINER ID        IMAGE                             COMMAND                  CREATED             STATUS              PORTS                                                              NAMES
32d3f8073830        traefik                           "/traefik -c /dev/nu…"   42 minutes ago      Up 42 minutes       0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp, 0.0.0.0:8080->8080/tcp   ss_traefik_1
9111fe4de602        wodby/drupal-nginx:8-1.13-4.1.0   "/docker-entrypoint.…"   42 minutes ago      Up 42 minutes       80/tcp                                                             wieting_nginx
69ea3e5e9cea        wodby/drupal-php:7.1-dev-4.4.2    "/docker-entrypoint.…"   42 minutes ago      Up 42 minutes       9000/tcp                                                           wieting_php
5acbb5d9cfa8        wodby/mariadb:10.2-3.1.3          "/docker-entrypoint.…"   42 minutes ago      Up 42 minutes       3306/tcp                                                           wieting_mariadb
00c8d282645a        wodby/drupal-nginx:8-1.13-4.1.0   "/docker-entrypoint.…"   42 minutes ago      Up 42 minutes       80/tcp                                                             d8_nginx
59a0306438a9        wodby/drupal:8-7.1-4.4.4          "/docker-entrypoint.…"   42 minutes ago      Up 42 minutes       9000/tcp                                                           d8_php
a9862f84c72e        wodby/mariadb:10.2-3.1.3          "/docker-entrypoint.…"   42 minutes ago      Up 42 minutes       3306/tcp                                                           d8_mariadb
8c20b8b1f3c3        mailhog/mailhog                   "MailHog"                42 minutes ago      Up 42 minutes       1025/tcp, 8025/tcp                                                 mailhog
8f178f8f879a        portainer/portainer               "/portainer --no-aut…"   42 minutes ago      Up 42 minutes       9000/tcp                                                           portainer
```

Where the *d8_* containers make up my "vanilla" Drupal 8 'default' site, *wieting_* containers make up my existing codebase site, and *traefik*, *portainer*, and *mailhog* all act in support of the entire stack.  I turned off my Drupal 7 build temporarily but will return to it later in the week.

**Comment by csandanov** [comment]
Drupal's multisite should be implemented the same way you would do it without docker. You don't need any additional containers unless you want to use different db servers for every site. If you try to use multiple codebases it's not really a Drupal's multisite feature, it's just running multiple Drupal sites that may or may not share some resources (e.g. db server, mailhog), if that's the case see how to [run multiple projects with d4d](https://wodby.com/stacks/drupal/docs/local/multiple-projects/).

**Comment by SummittDweller** [comment]
Thanks.  I'm currently doing OK running multiple projects with D4D.  I'd prefer to leverage multi-site properly but still can't get my head around how this can be done in D4D.

I think my confusion can be summed up in the following config from one of my project's docker-compose.yml file...

```
services:
  mariadb:
    image: wodby/mariadb:$MARIADB_TAG
    container_name: "${PROJECT_NAME}_mariadb"
    stop_grace_period: 30s
    environment:
      MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
      MYSQL_DATABASE: $DB_NAME
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASSWORD
    volumes:
      - ./mariadb-init:/docker-entrypoint-initdb.d     # Place init .sql file(s) here.
#      - /path/to/mariadb/data/on/host:/var/lib/mysql # I want to manage volumes manually.

  php:
    image: wodby/drupal-php:$PHP_TAG
    container_name: "${PROJECT_NAME}_php"
    environment:
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
      DB_HOST: "${PROJECT_NAME}_mariadb"
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
      DB_NAME: $DB_NAME
      DB_DRIVER: $DB_DRIVER
```

So, a *mariadb* container spins up a single $DB_NAME database and populates that single DB with the contents of any SQL in *./mariadb-init*.  It then has a corresponding *php* container which references the *mariadb* container, as DB_HOST, and that single database, as DB_NAME.

Ideally, I'd expect to need a single *mariadb* container that spawns and populates multiple databases, with a single *php* container that references and leverages the one *mariadb*.  Is that possible in D4D?  If so, how would it be configured?

**Comment by SummittDweller** [comment]
OK, perhaps I see how this can be done.  If I modify the start of each script in /mariadb-init so that they each create and use a different database, something like...

```
CREATE DATABASE IF NOT EXISTS NewDB;
GRANT ALL ON NewDB.* TO 'DB_USER'@'%' IDENTIFIED BY 'DB_PASSWORD';
USE NewDB;
...remainder of script...
```
Is this likely to work?

**Comment by SummittDweller** [comment]
The approach mentioned above IS working, with a couple of minor issues yet to be ironed out.  In any case, I'm going with the Drupal multi-site approach using one *mariadb* and one *php* container while tweaking my *.sql scripts to spawn multiple databases.

Ping me in this thread if you're interested in seeing how I did this.

**Comment by SummittDweller** [comment]
Actually, I never did get this approach working properly because I found it impossible to create/manage TLS certs for a single "stack" servicing multiple domains.  What I ended up doing in the end is creating more of a "multi-stack" deployment than a "multi-site".  Each site has its own mariadb, php, and nginx containers.  There is a lot of redundancy, but it's not hard to manage they way I have it setup.  Sorry I can't offer any constructive assistance with the multi-site approach.

**Comment by chucklor** [comment]
Thanks!

**Comment by mpgeek** [comment]
I was able to get the single-container pair (one _php_ and one _mariadb_ container) working for multisite. As pointed out by @csandanov, it really is just like any other environment in the setup. I did have issues with subomains pointing to the same container, but taking a cue from https://github.com/containous/traefik/issues/361, the missing piece for me was to use a subdomain regex in the traefik label property for the `nginx` container:

```
nginx:
    image: wodby/nginx:$NGINX_TAG
   [ ... nginx stuff ... ]
    labels:
      - 'traefik.backend=nginx'
      - 'traefik.port=80'
      - 'traefik.frontend.rule=HostRegexp:{subdomain:[a-z]+}.${PROJECT_BASE_URL}'

  [ ... more nginx stuff ... ]
```
This necessarily means i don't get a site at the root domain, but there's probably some more regex trickery that could produce that if it was needed. This along with drush aliases make it really easy to use as if it were any other server, and it's very prod-like for us.
