### ISSUE TITLE
Hybrid Workflow - Managing composer.json

### ISSUE THREAD

**Issue by SummittDweller** [wodby/docker4drupal#301]
So, I have a bit of a "hybrid" development workflow that creates a pair of Drupal 7 (d7) multi-site and Drupal 8 (d8) multi-site "stacks" (each stack has it's own _php_, _mariadb_ and _nginx_ containers) all under a _Traefik_ and _Portainer_ umbrella of "management" containers.

The d7 and d8 stacks are built using D4D's "vanilla" approach...each creating a "default" site from scratch with it's own _composer.json_, then I import each of the multi-site DBs using the slick _mariadb-init_ directory.  It works wonderfully and I get a fresh body of code every time I spin it up.

To maintain my customizations (I have quite a few module and library additions to make beyond the "vanilla" provisions, some of them are custom modules pulled from my GitHub repos) I have a customized _composer.json_ file that I drop in to replace the D4D vanilla copy in my _php_ container like so...

```
  php:
    image: wodby/drupal-php:$PHP_TAG
    container_name: "${PROJECT_NAME}_php"
    environment:
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail 
      DB_HOST: $DB_HOST
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
      DB_NAME: $DB_NAME
      DB_DRIVER: $DB_DRIVER
    volumes:
      - ./:/var/www/html
      - ./resources/composer.json:/var/www/html/composer.json   
```
The problem is that when I first spin up this new stack the "vanilla" _composer.json_ file is frequently still in use when Docker tries to rsync my custom copy and I get this...

```
Drupal 7 not found in /var/www/html - copying now...
rsync: rename "/var/www/html/.composer.json.LPDGFl" -> "composer.json": Resource busy (16)
```
This is easy to work around, I just use _Portainer_ to re-start each each _php_ container and do a quick `docker exec dx_php composer update` command, but I'd like to make the build fully automatic if possible.  Any suggestions?
