### ISSUE TITLE
sudo must be owned by uid 0 and have the setuid bit set

### ISSUE THREAD

**Issue by BuchuBaron** [wodby/docker4drupal#303]
The drupal4docker stack was working and I build a site on it.  After a machine reboot, the mariadb, nginx and php containers failed to start, with the "/usr/bin/sudo must be owned by uid 0 and have the setuid bit set" error.

I had changed the ownership of the /var/www/html volume on the host before the problem, so set it back to root.  The containers came up, but more fiddling with the volume caused them to fail at the next restart.  I cannot see how ownership of that volume could affect those containers.  

Now I cannot get the full stack to start again.

**`docker info`**
```
Containers: 15
 Running: 4
 Paused: 0
Images: 16
Server Version: 18.05.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 773c489c9c1b21a6d78b5c538cd395416ec50f88
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.13.0-43-generic
Operating System: Ubuntu 16.04.4 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.696GiB
Name: SugarBird
ID: X7IA:V6WR:XZTW:UU4Z:X6EH:3FTD:SPPP:ZINW:YYBG:C6E4:C2GJ:FJ4E
Docker Root Dir: /var/lib/docker
WARNING: No swap limit support
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Contents of your `docker-compose.yml`**
```
version: "2"

services:
  mariadb:
    image: wodby/mariadb:$MARIADB_TAG
    container_name: "${PROJECT_NAME}_mariadb"
#    stop_grace_period: 30s
    environment:
      MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
      MYSQL_DATABASE: $DB_NAME
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASSWORD
    volumes:
      - db_data:/var/lib/mysql # I want to manage volumes manually.
#      - ./mariadb-init:/docker-entrypoint-initdb.d # Place init .sql file(s) here.

  php:
    image: wodby/drupal-php:$PHP_TAG
    container_name: "${PROJECT_NAME}_php"
    environment:
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
      DB_HOST: $DB_HOST
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
      DB_NAME: $DB_NAME
      DB_DRIVER: $DB_DRIVER
    volumes:
      - codebase:/var/www/html

  nginx:
    image: wodby/drupal-nginx:$NGINX_TAG
    container_name: "${PROJECT_NAME}_nginx"
    depends_on:
      - php
    environment:
      NGINX_STATIC_CONTENT_OPEN_FILE_CACHE: "off"
      NGINX_ERROR_LOG_LEVEL: debug
      NGINX_BACKEND_HOST: php
      NGINX_SERVER_ROOT: /var/www/html/web
    volumes:
      - codebase:/var/www/html
    labels:
      - 'traefik.backend=nginx'
      - 'traefik.port=80'
      - 'traefik.frontend.rule=Host:${PROJECT_BASE_URL}'

  mailhog:
    image: mailhog/mailhog
    container_name: "${PROJECT_NAME}_mailhog"
    labels:
      - 'traefik.backend=mailhog'
      - 'traefik.port=8025'
      - 'traefik.frontend.rule=Host:mailhog.${PROJECT_BASE_URL}'

  redis:
    container_name: "${PROJECT_NAME}_redis"
    image: wodby/redis:$REDIS_TAG

  portainer:
    image: portainer/portainer
    container_name: "${PROJECT_NAME}_portainer"
    command: --no-auth -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - 'traefik.backend=portainer'
      - 'traefik.port=9000'
      - 'traefik.frontend.rule=Host:portainer.${PROJECT_BASE_URL}'

  traefik:
    image: traefik
    container_name: "${PROJECT_NAME}_traefik"
    command: -c /dev/null --web --docker --logLevel=INFO
    ports:
      - '8000:80'
#      - '8080:8080' # Dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  db_data:
  codebase:
```

**Contents of your `.env`**
```
### PROJECT SETTINGS

PROJECT_NAME=thecured
PROJECT_BASE_URL=thecured.co.za

DB_NAME=xxxxxxxxxxx
DB_USER=xxxxxxxxxx
DB_PASSWORD=xxxxxxxx
DB_ROOT_PASSWORD=xxxxxxxxxxxxxxxx
DB_HOST=mariadb
DB_DRIVER=mysql

### --- MARIADB ----

MARIADB_TAG=10.2-3.1.2
#MARIADB_TAG=10.1-3.1.3

### --- VANILLA DRUPAL ----
### [DRUPAL_VERSION]-[PHP_VERSION]-[STABILITY_TAG]

DRUPAL_TAG=8-7.1-4.2.6
#DRUPAL_TAG=8-7.0-4.2.6

### --- PHP ----

#PHP_TAG=7.1-dev-4.2.5
PHP_TAG=7.0-dev-4.2.5

### --- NGINX ----
### [DRUPAL_VERSION]-[NGINX_VERSION]-[STABILITY_TAG]

NGINX_TAG=8-1.14
#NGINX_TAG=7-1.13-4.0.3

### --- SOLR ---
### [DRUPAL_VERSION]-[SOLR_VERSION]-[STABILITY_TAG]

SOLR_TAG=8-6.6-2.4.0
#SOLR_TAG=8-6.5-2.4.0

### --- REDIS ---

REDIS_TAG=4.0-2.1.5
#REDIS_TAG=3.2-2.1.5

### --- POSTGRESQL ----

POSTGRES_TAG=10.1-1.3.0
#POSTGRES_TAG=9.6-1.3.0

### OTHERS

ADMINER_TAG=4.3-1.1.0
APACHE_TAG=2.4-3.0.5
ATHENAPDF_TAG=2.10.0
DRUPAL_NODE_TAG=1.0-1.0.0
MEMCACHED_TAG=1.4-2.0.0
RSYSLOG_TAG=latest
VARNISH_TAG=4.1-2.3.0
WEBGRIND_TAG=1.5-1.3.0
```

**Logs output `docker-compose logs`**
```
Attaching to thecured_nginx, thecured_php, thecured_portainer, thecured_redis, thecured_traefik, thecured_mailhog, thecured_mariadb
ESC[35mthecured_redis |ESC[0m 1:C 11 Jun 07:28:47.550 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
ESC[35mthecured_redis |ESC[0m 1:C 11 Jun 07:28:47.550 # Redis version=4.0.8, bits=64, commit=00000000, modified=0, pid=1, just started
ESC[35mthecured_redis |ESC[0m 1:C 11 Jun 07:28:47.551 # Configuration loaded
ESC[35mthecured_redis |ESC[0m 1:M 11 Jun 07:28:47.555 * Running mode=standalone, port=6379.
ESC[35mthecured_redis |ESC[0m 1:M 11 Jun 07:28:47.555 # WARNING: The TCP backlog setting of 511 cannot be enforced because /proc/sys/net/core/so
maxconn is set to the lower value of 128.
ESC[35mthecured_redis |ESC[0m 1:M 11 Jun 07:28:47.555 # Server initialized
ESC[35mthecured_redis |ESC[0m 1:M 11 Jun 07:28:47.555 # WARNING overcommit_memory is set to 0! Background save may fail under low memory conditi
on. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for 
this to take effect.
ESC[35mthecured_redis |ESC[0m 1:M 11 Jun 07:28:47.555 # WARNING you have Transparent Huge Pages (THP) support enabled in your kernel. This will 
create latency and memory usage issues with Redis. To fix this issue run the command 'echo never > /sys/kernel/mm/transparent_hugepage/enabled' 
as root, and add it to your /etc/rc.local in order to retain the setting after a reboot. Redis must be restarted after THP is disabled.
ESC[35mthecured_redis |ESC[0m 1:M 11 Jun 07:28:47.555 * Ready to accept connections
ESC[36mthecured_nginx |ESC[0m sudo: /usr/bin/sudo must be owned by uid 0 and have the setuid bit set
ESC[33mthecured_php |ESC[0m sudo: /usr/bin/sudo must be owned by uid 0 and have the setuid bit set
ESC[32mthecured_portainer |ESC[0m 2018/06/11 07:28:48 Starting Portainer 1.16.5 on :9000
ESC[31mthecured_traefik |ESC[0m time="2018-06-11T07:28:47Z" level=info msg="Using TOML configuration file /dev/null" 
ESC[31mthecured_traefik |ESC[0m time="2018-06-11T07:28:47Z" level=warning msg="web provider configuration is deprecated, you should use these op
tions : api, rest provider, ping and metrics" 
ESC[34mthecured_mailhog |ESC[0m 2018/06/11 07:28:46 Using in-memory storage
ESC[31mthecured_traefik |ESC[0m time="2018-06-11T07:28:47Z" level=info msg="Traefik version v1.5.4 built on 2018-03-15_01:35:21PM" 
ESC[34mthecured_mailhog |ESC[0m 2018/06/11 07:28:46 [SMTP] Binding to address: 0.0.0.0:1025
ESC[36;1mthecured_mariadb |ESC[0m sudo: /usr/bin/sudo must be owned by uid 0 and have the setuid bit set
ESC[31mthecured_traefik |ESC[0m time="2018-06-11T07:28:47Z" level=info msg="
ESC[34mthecured_mailhog |ESC[0m [HTTP] Binding to address: 0.0.0.0:8025
ESC[31mthecured_traefik |ESC[0m Stats collection is disabled.
ESC[34mthecured_mailhog |ESC[0m 2018/06/11 07:28:46 Serving under http://0.0.0.0:8025/
ESC[31mthecured_traefik |ESC[0m Help us improve Traefik by turning this feature on :)
ESC[34mthecured_mailhog |ESC[0m Creating API v1 with WebPath: 
ESC[31mthecured_traefik |ESC[0m More details on: https://docs.traefik.io/basics/#collected-data
ESC[31mthecured_traefik |ESC[0m " 
ESC[31mthecured_traefik |ESC[0m time="2018-06-11T07:28:47Z" level=info msg="Preparing server http &{Network: Address::80 TLS:<nil> Redirect:<nil> Auth:<nil> WhitelistSourceRange:[] Compress:false ProxyProtocol:<nil> ForwardedHeaders:0xc4206dff80} with readTimeout=0s writeTimeout=0s idleTimeout=3m0s" 
ESC[31mthecured_traefik |ESC[0m time="2018-06-11T07:28:47Z" level=info msg="Preparing server traefik &{Network: Address::8080 TLS:<nil> Redirect:<nil> Auth:<nil> WhitelistSourceRange:[] Compress:false ProxyProtocol:<nil> ForwardedHeaders:0xc4206dffa0} with readTimeout=0s writeTimeout=0s idleTimeout=3m0s" 
ESC[31mthecured_traefik |ESC[0m time="2018-06-11T07:28:47Z" level=info msg="Starting server on :80" 
ESC[31mthecured_traefik |ESC[0m time="2018-06-11T07:28:47Z" level=info msg="Starting provider *docker.Provider {"Watch":true,"Filename":"","Constraints":null,"Trace":false,"DebugLogGeneratedTemplate":false,"Endpoint":"unix:///var/run/docker.sock","Domain":"","TLS":null,"ExposedByDefault"
ESC[31mthecured_traefik |ESC[0m time="2018-06-11T07:28:47Z" level=info msg="Starting provider *docker.Provider {"Watch":true,"Filename":"","Constraints":null,"Trace":false,"DebugLogGeneratedTemplate":false,"Endpoint":"unix:///var/run/docker.sock","Domain":"","TLS":null,"ExposedByDefault":true,"UseBindPortIP":false,"SwarmMode":false}" 
ESC[31mthecured_traefik |ESC[0m time="2018-06-11T07:28:47Z" level=info msg="Starting server on :8080" 
ESC[31mthecured_traefik |ESC[0m time="2018-06-11T07:28:48Z" level=info msg="Server configuration reloaded on :8080" 
ESC[31mthecured_traefik |ESC[0m time="2018-06-11T07:28:48Z" level=info msg="Server configuration reloaded on :80" 
ESC[31mthecured_traefik |ESC[0m time="2018-06-11T07:28:50Z" level=info msg="Server configuration reloaded on :80" 
ESC[31mthecured_traefik |ESC[0m time="2018-06-11T07:28:50Z" level=info msg="Server configuration reloaded on :8080" 
ESC[31mthecured_traefik |ESC[0m time="2018-06-11T07:28:51Z" level=info msg="Skipping same configuration for provider docker" 
ESC[31mthecured_traefik |ESC[0m time="2018-06-11T07:28:51Z" level=info msg="Skipping same configuration for provider docker" 
ESC[31mthecured_traefik |ESC[0m time="2018-06-11T07:38:52Z" level=warning msg="A new release has been found: 1.6.3. Please consider updating." 
ESC[34mthecured_mailhog |ESC[0m Creating API v2 with WebPath: 
ESC[34mthecured_mailhog |ESC[0m [APIv1] KEEPALIVE /api/v1/events

```
