### ISSUE TITLE
MariaDB Volume Permission Issues

### ISSUE THREAD

**Issue by elkrammer** [wodby/docker4drupal#307]
Hey Chingis,

First of all I wanted to thank you for your hard work on this project - it's been a life savior for me and it has saved me hundreds of hours. Everything works really well and your documentation is superb.

I'm having trouble with my MariaDB volume permissions.
The first time I create the image everything works fine and I'm able to import my DBs and generate data to the mariadb volume without any problems.
However as soon as I try to rebuild the image I start getting permission errors.

Right now the only error I have at hand is:
PermissionError: [Errno 13] Permission denied: '/home/user/projects/cc_panel/apps/test/dbdata/performance_schema'
But the other errors I've gotten are all similar - permission denied with files or dirs inside my mariadb volume.

This is what the permissions on my db volume look like:
```
~/projects/cc_panel/apps/test/dbdata ❯ ls -ltrha
total 331M
drwx------ 2       100       101 4.0K Jul  2 11:45 performance_schema
-rw-rw---- 1       100       101    0 Jul  2 11:45 multi-master.info
drwx------ 2       100       101 4.0K Jul  2 11:45 mysql
-rw-rw---- 1       100       101 128M Jul  2 11:56 ib_logfile1
-rw-rw---- 1       100       101   52 Jul  2 18:45 aria_log_control
-rw-rw---- 1       100       101  16K Jul  2 18:45 aria_log.00000001
drwxr-xr-x 7 user user 4.0K Jul  2 18:45 ..
-rw-rw---- 1       100       101  24K Jul  2 18:50 tc.log
-rw-rw---- 1       100       101    2 Jul  2 18:50 c4b7c227ce2a.pid
drwxr-xr-x 5       100       101 4.0K Jul  2 18:50 .
drwx------ 2       100       101  68K Jul  2 18:51 app
-rw-rw---- 1       100       101  74M Jul  2 19:00 ibdata1
-rw-rw---- 1       100       101 128M Jul  2 19:00 ib_logfile0
```

**Output of `docker info`**
```
Containers: 28
 Running: 9
 Paused: 0
 Stopped: 19
Images: 198
Server Version: 18.05.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: false
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 773c489c9c1b21a6d78b5c538cd395416ec50f88
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871
init version: 949e6fa
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.17.2-1-ARCH
Operating System: Arch Linux
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.654GiB
Name: undercroft
ID: D6HW:MTXG:RVNT:LZSQ:YFRV:KY45:KL3L:KXCC:TKDY:XGN5:X5FF:XHU3
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

**Contents of your `docker-compose.yml`**
```
services:
  mariadb:
    image: wodby/mariadb:$MARIADB_TAG
    container_name: "${PROJECT_NAME}_mariadb"
    stop_grace_period: 30s
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
      MYSQL_DATABASE: $DB_NAME
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASSWORD
    volumes:
      - ./dbdata:/var/lib/mysql # I want to manage volumes manually.
```

Any thoughts?
Thanks for your help!
