### ISSUE TITLE
"Multiple projects" setup not working with PMA

### ISSUE THREAD

**Issue by omcandido** [wodby/docker4drupal#309]
**Issue**
I have several sites in my host machine. I use traefik to manage the routing as described [here](https://wodby.com/stacks/drupal/docs/local/multiple-projects/). I can browse the sites correctly, however, PhpMyAdmin is not working as expected. If I browse, say pma.site1.docker.localhost, it takes me to the pma page of another site (eg. pma.site3.docker.localhost).

I use the same .yml structure for all sites. Is there anything I'm missing in the pma settings? Can anyone reproduce this behaviour?

**Output of `docker info`**
```
Containers: 31                                                                  
 Running: 28                                                                    
 Paused: 0                                                                      
 Stopped: 3                                                                     
Images: 18                                                                      
Server Version: 18.03.1-ce                                                      
Storage Driver: overlay2                                                        
 Backing Filesystem: extfs                                                      
 Supports d_type: true                                                          
 Native Overlay Diff: true                                                      
Logging Driver: json-file                                                       
Cgroup Driver: cgroupfs                                                         
Plugins:                                                                        
 Volume: local                                                                  
 Network: bridge host macvlan null overlay                                      
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog  
Swarm: inactive                                                                 
Runtimes: runc                                                                  
Default Runtime: runc                                                           
Init Binary: docker-init                                                        
containerd version: 773c489c9c1b21a6d78b5c538cd395416ec50f88                    
runc version: 4fc53a81fb7c994640722ac585fa9ca548971871                          
init version: 949e6fa                                                           
Security Options:                                                               
 seccomp                                                                        
  Profile: default                                                              
Kernel Version: 4.9.87-linuxkit-aufs                                            
Operating System: Docker for Windows                                            
OSType: linux                                                                   
Architecture: x86_64                                                            
CPUs: 2                                                                         
Total Memory: 1.934GiB                                                          
Name: linuxkit-00155d0ba210                                                     
ID: 6DAE:U3VZ:UET2:FYSW:SHGU:HFJS:HCVV:GK2X:HPAB:2J2Y:KIDP:CZKE                 
Docker Root Dir: /var/lib/docker                                                
Debug Mode (client): false                                                      
Debug Mode (server): true                                                       
 File Descriptors: 250                                                          
 Goroutines: 221                                                                
 System Time: 2018-07-09T13:15:57.570589Z                                       
 EventsListeners: 3                                                             
Registry: https://index.docker.io/v1/                                           
Labels:                                                                         
Experimental: false                                                             
Insecure Registries:                                                            
 127.0.0.0/8                                                                    
Live Restore Enabled: false                                                     
```

**Contents of your `docker-compose.yml`**
```
version: "2"

services:
  mariadb:
    image: wodby/mariadb:$MARIADB_TAG
    container_name: "${PROJECT_NAME}_mariadb"
    stop_grace_period: 30s
    environment:
      MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
      MYSQL_DATABASE: $DB_NAME
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASSWORD
    volumes:
      - ./mariadb-init:/docker-entrypoint-initdb.d # Place init .sql file(s) here.
#      - /path/to/mariadb/data/on/host:/var/lib/mysql # I want to manage volumes manually.

  php:
    image: wodby/drupal-php:$PHP_TAG
    container_name: "${PROJECT_NAME}_php"
    environment:
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
      DB_HOST: $DB_HOST
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
      DB_NAME: $DB_NAME
      DB_DRIVER: $DB_DRIVER
## Read instructions at https://wodby.com/stacks/drupal/docs/local/xdebug/
#      PHP_XDEBUG: 1
#      PHP_XDEBUG_DEFAULT_ENABLE: 1
#      PHP_XDEBUG_REMOTE_CONNECT_BACK: 0
#      PHP_IDE_CONFIG: serverName=my-ide
#      PHP_XDEBUG_REMOTE_HOST: host.docker.internal # Docker 18.03+ & Linux/Mac/Win
#      PHP_XDEBUG_REMOTE_HOST: 172.17.0.1 # Linux, Docker < 18.03
#      PHP_XDEBUG_REMOTE_HOST: 10.254.254.254 # macOS, Docker < 18.03
#      PHP_XDEBUG_REMOTE_HOST: 10.0.75.1 # Windows, Docker < 18.03
    volumes:
      - ./:/var/www/html
## For macOS users (https://wodby.com/stacks/drupal/docs/local/docker-for-mac/)
#      - ./:/var/www/html:cached # User-guided caching
#      - docker-sync:/var/www/html # Docker-sync
## For Xdebug profiler files
#      - files:/mnt/files

  nginx:
    image: wodby/drupal-nginx:$NGINX_TAG
    container_name: "${PROJECT_NAME}_nginx"
    depends_on:
      - php
    environment:
#      NGINX_PAGESPEED: "on"
      NGINX_STATIC_CONTENT_OPEN_FILE_CACHE: "off"
      NGINX_ERROR_LOG_LEVEL: debug
      NGINX_BACKEND_HOST: php
      NGINX_SERVER_ROOT: /var/www/html
#      NGINX_DRUPAL_FILE_PROXY_URL: http://example.com
    volumes:
      - ./:/var/www/html
# For macOS users (https://wodby.com/stacks/drupal/docs/local/docker-for-mac/)
#      - ./:/var/www/html:cached # User-guided caching
#      - docker-sync:/var/www/html # Docker-sync
    labels:
      - 'traefik.backend=erasmusintern_dumped_nginx_1'
      - 'traefik.port=80'
      - 'traefik.frontend.rule=Host:${PROJECT_BASE_URL}'

  mailhog:
    image: mailhog/mailhog
    container_name: "${PROJECT_NAME}_mailhog"
    labels:
      - 'traefik.backend=mailhog'
      - 'traefik.port=8025'
      - 'traefik.frontend.rule=Host:mailhog.${PROJECT_BASE_URL}'


  pma:
    image: phpmyadmin/phpmyadmin
    container_name: "${PROJECT_NAME}_pma"
    environment:
      PMA_HOST: $DB_HOST
      PMA_USER: $DB_USER
      PMA_PASSWORD: $DB_PASSWORD
      PHP_UPLOAD_MAX_FILESIZE: 1G
      PHP_MAX_INPUT_VARS: 1G
    labels:
      - 'traefik.backend=pma'
      - 'traefik.port=80'
      - 'traefik.frontend.rule=Host:pma.${PROJECT_BASE_URL}'

  portainer:
    image: portainer/portainer
    container_name: "${PROJECT_NAME}_portainer"
    command: --no-auth -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - 'traefik.backend=portainer'
      - 'traefik.port=9000'
      - 'traefik.frontend.rule=Host:portainer.${PROJECT_BASE_URL}'
```
