### ISSUE TITLE
Xdebug "gateway timeout" on apache

### ISSUE THREAD

**Issue by ChristopheCaron** [wodby/docker4drupal#328]
***Codebase***
mounted codebase

**Describe your issue**
I use xdebug and after a 30 seconds break point , my browser displays "gateway timeout"
which apache /php parameters I have to edit to avoid this ?

**Contents of your `docker-compose.yml`**
```
Standad docker composer from docker4drupal
```

**Contents of your `.env`**
```
Standad .env from docker4drupal
```

**Comment by ChristopheCaron** [comment]
I solve my issue with the following environnement variables on apache : 

```
apache:
    image: wodby/apache:$APACHE_TAG
[....]
    environment:
      APACHE_TIMEOUT: 6000
      APACHE_FCGI_PROXY_TIMEOUT: 6000
```
