### ISSUE TITLE
Nginx strips "X-Accel-Buffering: no" header

### ISSUE THREAD

**Issue by AllaKurochka** [wodby/docker4drupal#335]
I have blocks which are displayed via BigPipe. 
By default BigPipe sets a "X-Accel-Buffering: no" header, which automatically disables fastcgi_buffering and gzip in Nginx >= 1.5.6 (my project works with NGINX_TAG=8-1.14-4.1.0). But for some reason this header is not being sent and as a result BigPipe doesn't work correctly. I'm sure it's not the Drupal issue. I checked with debugger - headers are sent, but nginx somehow strips this header. 
Why might this happen?

**Contents of the `docker-compose.yml`**
```
...
php:
    build:
      context: ./docker/custom-drupal-php
      args:
        BASE_IMAGE_TAG: $PHP_VERSION
        LOCAL_USER_ID: $LOCAL_USER_ID
        LOCAL_GROUP_ID: $LOCAL_GROUP_ID
    container_name: "${PROJECT_NAME}_php"
    environment:
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
      DB_HOST: $DB_HOST
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
      DB_NAME: $DB_NAME
      DB_DRIVER: $DB_DRIVER
      PHP_XDEBUG: 1
      PHP_XDEBUG_DEFAULT_ENABLE: 1
    volumes:
      - ./:/var/www/html
    networks:
      - custom-network

nginx:
    image: wodby/drupal-nginx:$NGINX_TAG
    container_name: "${PROJECT_NAME}_nginx"
    depends_on:
      - php
    environment:
      NGINX_STATIC_CONTENT_OPEN_FILE_CACHE: "off"
      NGINX_ERROR_LOG_LEVEL: debug
      NGINX_BACKEND_HOST: php
      NGINX_SERVER_ROOT: /var/www/html/web
    volumes:
      - ./:/var/www/html
    labels:
      - 'traefik.backend=nginx'
      - 'traefik.port=80'
      - 'traefik.frontend.rule=Host:${PROJECT_BASE_URL}'
    networks:
      - custom-network
...
```

**Contents of the `.env`**
```
ENV=dev
PROJECT_NAME=name
PROJECT_BASE_URL=site.docker.localhost

DB_NAME=db_name
DB_USER=db_user
DB_PASSWORD=db_password
DB_ROOT_PASSWORD=password
DB_HOST=mariadb
DB_DRIVER=mysql

MARIADB_TAG=10.2-3.1.3
DRUPAL_TAG=8-7.1-4.4.4
PHP_TAG=7.1-dev-4.4.2
NGINX_TAG=8-1.14-4.1.0
HTTP_ROOT=/var/www/html/web
...
```
