### ISSUE TITLE
Xdebug not configured for PHP 7.3 on Mac

### ISSUE THREAD

**Issue by dawillcox** [wodby/docker4drupal#357]
***Codebase***
Mounted codebase, I think. (Drupal in a dir on my mac, mounted to the container.)

**Describe the bug**
Running with PhpStorm on Mac.
Had PHP_TAG=7.3-dev-macos-4.11.0 set, xdebug wasn't enabled in the php container.
Meaning there was no [xdebug] section anywhere in the php initialization files.

Changing to 7.1 worked.

**Output of `docker info`**
```
Containers: 33
 Running: 6
 Paused: 0
 Stopped: 27
Images: 27
Server Version: 18.09.1
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: active
 NodeID: j4503t8yp4yej8zox4qp53zfn
 Is Manager: true
 ClusterID: m31hhmsnvolo4kj38sxb8szp6
 Managers: 1
 Nodes: 1
 Default Address Pool: 10.0.0.0/8  
 SubnetSize: 24
 Orchestration:
  Task History Retention Limit: 5
 Raft:
  Snapshot Interval: 10000
  Number of Old Snapshots to Retain: 0
  Heartbeat Tick: 1
  Election Tick: 3
 Dispatcher:
  Heartbeat Period: 5 seconds
 CA Configuration:
  Expiry Duration: 3 months
  Force Rotate: 0
 Autolock Managers: false
 Root Rotation In Progress: false
 Node Address: 192.168.65.2
 Manager Addresses:
  192.168.65.2:2377
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9754871865f7fe2f4e74d43e2fc7ccd237edcbce
runc version: 96ec2177ae841256168fcf76954f7177af9446eb
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.125-linuxkit
Operating System: Docker for Mac
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 1.952GiB
Name: linuxkit-025000000001
ID: HENH:TGVN:CMHZ:FWCY:FII7:64NN:APKE:NV32:Q4CW:Y7EK:C2UI:2DSK
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
HTTP Proxy: gateway.docker.internal:3128
HTTPS Proxy: gateway.docker.internal:3129
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine
```

**Contents of your `docker-compose.yml`**
```
    image: wodby/drupal-php:$PHP_TAG
    container_name: "${PROJECT_NAME}_php"
    environment:
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
      DB_HOST: $DB_HOST
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
      DB_NAME: $DB_NAME
      DB_DRIVER: $DB_DRIVER
      PHP_FPM_USER: wodby
      PHP_FPM_GROUP: wodby
      COLUMNS: 80 # Set 80 columns for docker exec -it.
## Read instructions at https://wodby.com/stacks/drupal/docs/local/xdebug/
      PHP_XDEBUG: 1
      PHP_XDEBUG_DEFAULT_ENABLE: 1
      PHP_XDEBUG_REMOTE_CONNECT_BACK: 0
      PHP_IDE_CONFIG: serverName=PhpStorm
      PHP_XDEBUG_REMOTE_HOST: host.docker.internal # Docker 18.03+ Mac/Win
      PHP_XDEBUG_REMOTE_LOG: /tmp/php-my-idexdebug.log
    volumes:
      - ./:/var/www/html:cached # User-guided caching
```

**Contents of your `.env`**
(This is with it working. The bug was when `PHP_TAG=7.3-dev-macos-4.11.0` was set.)
```
### Documentation available at https://wodby.com/docs/stacks/drupal/local
### Changelog can be found at https://github.com/wodby/docker4drupal/releases
### Images tags format explained at https://github.com/wodby/docker4drupal#images-tags

### PROJECT SETTINGS

PROJECT_NAME=my_drupal8_project
PROJECT_BASE_URL=drupal.docker.localhost

DB_NAME=drupal
DB_USER=drupal
DB_PASSWORD=drupal
DB_ROOT_PASSWORD=password
DB_HOST=mariadb
DB_DRIVER=mysql

### --- MARIADB ----

MARIADB_TAG=10.1-3.3.15
#MARIADB_TAG=10.3-3.3.15
#MARIADB_TAG=10.2-3.3.15

### --- VANILLA DRUPAL ----

DRUPAL_TAG=8-4.11.0
#DRUPAL_TAG=7-4.11.0

### --- PHP ----

# Linux (uid 1000 gid 1000)

#PHP_TAG=7.2-dev-4.11.0
#PHP_TAG=7.3-dev-4.11.0
#PHP_TAG=7.1-dev-4.11.0
#PHP_TAG=5.6-dev-4.11.0

# macOS (uid 501 gid 20)

#PHP_TAG=7.3-dev-macos-4.11.0
#PHP_TAG=7.2-dev-macos-4.11.0
PHP_TAG=7.1-dev-macos-4.11.0
#PHP_TAG=5.6-dev-macos-4.11.0

### --- NGINX ----

NGINX_TAG=1.15-5.3.2
#NGINX_TAG=1.14-5.3.2

NGINX_VHOST_PRESET=drupal8
#NGINX_VHOST_PRESET=drupal7
#NGINX_VHOST_PRESET=drupal6

### --- SOLR ---

SOLR_CONFIG_SET="search_api_solr_8.x-2.3"
#SOLR_CONFIG_SET="search_api_solr_8.x-1.2"
#SOLR_CONFIG_SET="search_api_solr_7.x-1.14"

SOLR_TAG=7.5-3.0.7
#SOLR_TAG=7.4-3.0.7
#SOLR_TAG=7.3-3.0.7
#SOLR_TAG=7.2-3.0.7
#SOLR_TAG=7.1-3.0.7
#SOLR_TAG=6.6-3.0.7
#SOLR_TAG=5.5-3.0.7
#SOLR_TAG=5.4-3.0.7

### --- ELASTICSEARCH ---

ELASTICSEARCH_TAG=6.2-3.0.3
#ELASTICSEARCH_TAG=6.1-3.0.3
#ELASTICSEARCH_TAG=6.0-3.0.3
#ELASTICSEARCH_TAG=5.6-3.0.3
#ELASTICSEARCH_TAG=5.5-3.0.3
#ELASTICSEARCH_TAG=5.4-3.0.3

### --- KIBANA ---

KIBANA_TAG=6.2-3.0.3
#KIBANA_TAG=6.1-3.0.3
#KIBANA_TAG=6.0-3.0.3
#KIBANA_TAG=5.6-3.0.3
#KIBANA_TAG=5.5-3.0.3
#KIBANA_TAG=5.4-3.0.3

### --- REDIS ---

REDIS_TAG=4-3.0.3
#REDIS_TAG=5-3.0.3

### --- NODE ---

NODE_TAG=10-0.10.0
#NODE_TAG=8-0.10.0
#NODE_TAG=6-0.10.0

### --- VARNISH ---

VARNISH_TAG=4.1-4.1.2
#VARNISH_TAG=6.0-4.1.2

### --- POSTGRESQL ----

POSTGRES_TAG=11-1.5.0
#POSTGRES_TAG=10-1.5.0
#POSTGRES_TAG=9.6-1.5.0
#POSTGRES_TAG=9.5-1.5.0
#POSTGRES_TAG=9.4-1.5.0
#POSTGRES_TAG=9.3-1.5.0

### OTHERS

ADMINER_TAG=4.6-3.4.1
APACHE_TAG=2.4-4.0.3
ATHENAPDF_TAG=2.10.0
DRUPAL_NODE_TAG=1.0-2.0.0
MEMCACHED_TAG=1-2.2.1
OPENSMTPD_TAG=6.0-1.4.0
RSYSLOG_TAG=latest
WEBGRIND_TAG=1.5-1.8.0
XHPROF_TAG=1.2.0
```

**Logs output `docker-compose logs`**
Logs were way too big, and I don't have a log from when the problem happened.
```
```
