### ISSUE TITLE
Making docker4drupal work with nginx-proxy

### ISSUE THREAD

**Issue by badri** [Wodby/docker4drupal#36]
hi guys,
This setup is working great for me, except I'm not able to integrate with [Nginx Proxy](https://github.com/jwilder/nginx-proxy). I have the nginx-proxy container(s) running, and the following configuration for my nginx service:

```
  nginx:
    image: wodby/drupal-nginx
    environment:
      NGINX_SERVER_NAME: localhost
      NGINX_UPSTREAM_NAME: php
      VIRTUAL_HOST: mydrupalsite.dev
#      NGINX_DOCROOT: public # Relative path inside the /var/www/html/ directory.
      DRUPAL_VERSION: 7 # Allowed: 7, 8.
    volumes_from:
      - php
    ports:
      - "8003:80"

```
Any help would be appreciated :)

**Comment by PavelPrischepa** [comment]
Hi @badri 
nginx-proxy works well for me

Here is my output of `docker-compose logs -f nginx-proxy`, it may helps:
```
Attaching to nginx-proxy
nginx-proxy    | forego     | starting nginx.1 on port 5000
nginx-proxy    | forego     | starting dockergen.1 on port 5100
nginx-proxy    | dockergen.1 | 2016/09/08 11:42:22 Error inspecting container: ccdd5b26d4e9304a907e2906fee736187534ca643506dc5039a2092504717260: No such container: ccdd5b26d4e9304a907e2906fee736187534ca643506dc5039a2092504717260
nginx-proxy    | dockergen.1 | 2016/09/08 11:42:22 Generated '/etc/nginx/conf.d/default.conf' from 6 containers
nginx-proxy    | dockergen.1 | 2016/09/08 11:42:22 Watching docker events
nginx-proxy    | dockergen.1 | 2016/09/08 11:42:22 Contents of /etc/nginx/conf.d/default.conf did not change. Skipping notification 'nginx -s reload'
nginx-proxy    | nginx.1    | mydrupalsite.dev 172.19.0.1 - - [08/Sep/2016:11:42:35 +0000] "GET / HTTP/1.1" 200 26017 "-" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/52.0.2743.116 Chrome/52.0.2743.116 Safari/537.36"
```

**Comment by badri** [comment]
Hi
Can you please share your docker compose configuration?

On 08-Sep-2016 5:21 PM, "Pavel Prischepa" <notifications@github.com> wrote:

Hi @badri <https://github.com/badri>
nginx-proxy works well for me

Here is my output of docker-compose logs -f nginx-proxy, it may helps:

Attaching to nginx-proxy
nginx-proxy    | forego     | starting nginx.1 on port 5000
nginx-proxy    | forego     | starting dockergen.1 on port 5100
nginx-proxy    | dockergen.1 | 2016/09/08 11:42:22 Error inspecting
container: ccdd5b26d4e9304a907e2906fee736187534ca643506dc5039a2092504717260:
No such container:
ccdd5b26d4e9304a907e2906fee736187534ca643506dc5039a2092504717260
nginx-proxy    | dockergen.1 | 2016/09/08 11:42:22 Generated
'/etc/nginx/conf.d/default.conf' from 6 containers
nginx-proxy    | dockergen.1 | 2016/09/08 11:42:22 Watching docker events
nginx-proxy    | dockergen.1 | 2016/09/08 11:42:22 Contents of
/etc/nginx/conf.d/default.conf did not change. Skipping notification
'nginx -s reload'
nginx-proxy    | nginx.1    | mydrupalsite.dev 172.19.0.1 - -
[08/Sep/2016:11:42:35 +0000] "GET / HTTP/1.1" 200 26017 "-"
"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like
Gecko) Ubuntu Chromium/52.0.2743.116 Chrome/52.0.2743.116
Safari/537.36"

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/Wodby/docker4drupal/issues/36#issuecomment-245573851>,
or mute the thread

**Comment by PavelPrischepa** [comment]
@badri Sure.
```
version: "2"

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  mariadb:
    image: wodby/drupal-mariadb
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
#    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci # The simple way to override the mariadb config.
    volumes:
      - ./docker-runtime/mariadb:/var/lib/mysql
#      - ./docker-runtime/mariadb-init:/docker-entrypoint-initdb.d # Place init .sql file(s) here.

  php:
    image: wodby/drupal-php:7.0 # Allowed: 7.0, 5.6.
    environment:
      PHP_SITE_NAME: dev
      PHP_HOST_NAME: localhost:8000
      PHP_DOCROOT: web # Relative path inside the /var/www/html/ directory.
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
      PHP_XDEBUG_ENABLED: 0 # Set 1 to enable.
    volumes:
      - ./:/var/www/html

  nginx:
    image: wodby/drupal-nginx
    environment:
      VIRTUAL_HOST: mydrupalsite.dev
      NGINX_SERVER_NAME: localhost
      NGINX_UPSTREAM_NAME: php
      NGINX_DOCROOT: web # Relative path inside the /var/www/html/ directory.
      DRUPAL_VERSION: 8 # Allowed: 7, 8.
    volumes_from:
      - php
    ports:
      - "8000:80"
```

**Comment by PavelPrischepa** [comment]
I'm going to close the issue due to no activity.

**Comment by bender-r** [comment]
@PavelPrischepa 
I copied the configuration and changed the VIRTUAL_HOST subdomain,mydomain.com
run docker-compose up -d
subdomain,mydomain.com works

For the second site, i added a new folder, copy the file docker-compose.yml with 
```
  nginx:
    environment:
      VIRTUAL_HOST: subdomain2,mydomain.com
    ports:
      - "7000:80"
```
run docker-compose up -d

error
> ERROR: for nginx-proxy  Cannot create container for service nginx-proxy: Conflict. The name "/nginx-proxy" is already in use by container f2e44e2e89a8226f44369cfeb618665ad6ef060bdab5646b5629dd3ad507fe51. You have to remove (or rename) that container to be able to reuse that name.
ERROR: Encountered errors while bringing up the project.

I deleted a row    **container_name: nginx-proxy**
run docker-compose up -d

error

> ERROR: for nginx-proxy  Cannot start service nginx-proxy: driver failed programming external connectivity on endpoint c0995be03327_kafedraf_nginx-proxy_1 (1e49c586d072a5654484967b38cc19fed6a872f41e8a8df701f7b59a6591ed2b): Bind for 0.0.0.0:80 failed: port is already allocated
> ERROR: Encountered errors while bringing up the project.

What I missed or where the error?
