### ISSUE TITLE
Failed installation to mounted codebase on Windows 10

### ISSUE THREAD

**Issue by nexusstar** [wodby/docker4drupal#374]
***Codebase***
Mounted clean codebase from drupal-composer/drupal-project 

**Describe your issue**

Installation fails right after entering database credentials. 

It shows *Page not Found* page for `install.php` as next step. 

I checked inside the PHP and Nginx containers the files are all there and all are owned by `root`. 

The strange thing is that the database was populated with some basic tables and `settings.php` file was populated.

If I create some basic PHP file inside the container root folder it too could not be accessed. 
**But if I clear 'settings.php` file the first screen of Drupal installation pops up**

**Output of `docker info`**
```
Containers: 12
 Running: 12
 Paused: 0
 Stopped: 0
Images: 13
Server Version: 18.09.2
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9754871865f7fe2f4e74d43e2fc7ccd237edcbce
runc version: 09c8266bf2fcf9519a651b04ae54c967b9ab86ec
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.125-linuxkit
Operating System: Docker for Windows
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.934GiB
Name: linuxkit-00155d0a1420
ID: JJFV:FVX3:HQMC:LWJK:2YKW:ZQWZ:IPGY:YLFZ:RFOK:OTRY:EVO6:TIEQ
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 96
 Goroutines: 109
 System Time: 2019-04-05T11:37:35.7915408Z
 EventsListeners: 2
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine
```

**Contents of your `docker-compose.yml`**
```
version: "3"

services:
  mariadb:
    image: wodby/mariadb:$MARIADB_TAG
    container_name: "${PROJECT_NAME}_mariadb"
    stop_grace_period: 30s
    environment:
      MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
      MYSQL_DATABASE: $DB_NAME
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASSWORD

  php:
    image: wodby/drupal-php:$PHP_TAG
    container_name: "${PROJECT_NAME}_php"
    user: root
    command: "php-fpm -R"
    environment:
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
      DB_HOST: $DB_HOST
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
      DB_NAME: $DB_NAME
      DB_DRIVER: $DB_DRIVER
      PHP_FPM_USER: root
      PHP_FPM_GROUP: root
      COLUMNS: 80 # Set 80 columns for docker exec -it.

    volumes:
      - ./:/var/www/html

  nginx:
    image: wodby/nginx:$NGINX_TAG
    container_name: "${PROJECT_NAME}_nginx"
    depends_on:
      - php
    environment:
      NGINX_STATIC_OPEN_FILE_CACHE: "off"
      NGINX_ERROR_LOG_LEVEL: debug
      NGINX_BACKEND_HOST: php
      NGINX_SERVER_ROOT: /var/www/html/web
      NGINX_VHOST_PRESET: $NGINX_VHOST_PRESET

    volumes:
      - ./:/var/www/html

    labels:
      - 'traefik.backend=${PROJECT_NAME}_nginx'
      - 'traefik.port=80'
      - 'traefik.frontend.rule=Host:${PROJECT_BASE_URL}'
```

**Contents of your `.env`**
```
### --- MARIADB ----

MARIADB_TAG=10.1-3.4.4
#MARIADB_TAG=10.3-3.4.4
#MARIADB_TAG=10.2-3.4.4

### --- VANILLA DRUPAL ----

DRUPAL_TAG=8-4.12.9
#DRUPAL_TAG=7-4.12.9

### --- PHP ----

# Linux (uid 1000 gid 1000)

#PHP_TAG=7.2-dev-4.12.5
PHP_TAG=7.3-dev-4.12.5
#PHP_TAG=7.1-dev-4.12.5
#PHP_TAG=5.6-dev-4.12.5

# macOS (uid 501 gid 20)

#PHP_TAG=7.3-dev-macos-4.12.5
#PHP_TAG=7.2-dev-macos-4.12.5
#PHP_TAG=7.1-dev-macos-4.12.5
#PHP_TAG=5.6-dev-macos-4.12.5

### --- NGINX ----

NGINX_TAG=1.15-5.3.6
#NGINX_TAG=1.14-5.3.6

NGINX_VHOST_PRESET=drupal8
#NGINX_VHOST_PRESET=drupal7
#NGINX_VHOST_PRESET=drupal6
```

**Logs output `docker-compose logs`**
```
nginx_1    | 2019/04/05 11:25:34 [notice] 1#1: using the "epoll" event method
nginx_1    | 2019/04/05 11:25:34 [notice] 1#1: nginx/1.15.10
nginx_1    | 2019/04/05 11:25:34 [notice] 1#1: built by gcc 6.4.0 (Alpine 6.4.0)
nginx_1    | 2019/04/05 11:25:34 [notice] 1#1: OS: Linux 4.9.125-linuxkit
nginx_1    | 2019/04/05 11:25:34 [notice] 1#1: getrlimit(RLIMIT_NOFILE): 1048576:1048576
nginx_1    | 2019/04/05 11:25:34 [notice] 1#1: start worker processes
nginx_1    | 2019/04/05 11:25:34 [notice] 1#1: start worker process 38
nginx_1    | 2019/04/05 11:25:34 [notice] 1#1: start worker process 39
nginx_1    | 172.22.0.6 - - [05/Apr/2019:11:27:11 +0000] "GET / HTTP/1.1" 302 324 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:67.0) Gecko/20100101 Firefox/67.0"
nginx_1    | 172.22.0.6 - - [05/Apr/2019:11:27:14 +0000] "GET /core/install.php HTTP/1.1" 200 4143 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:67.0) Gecko/20100101
Firefox/67.0"
nginx_1    | 2019/04/05 11:27:14 [info] 38#38: *1 client 172.22.0.6 closed keepalive connection
nginx_1    | 2019/04/05 11:27:15 [info] 38#38: *4 client 172.22.0.6 closed keepalive connection
nginx_1    | 2019/04/05 11:27:15 [info] 39#39: *6 client 172.22.0.6 closed keepalive connection
nginx_1    | 2019/04/05 11:27:15 [info] 39#39: *5 client 172.22.0.6 closed keepalive connection
nginx_1    | 2019/04/05 11:27:15 [info] 38#38: *7 client 172.22.0.6 closed keepalive connection
nginx_1    | 2019/04/05 11:27:15 [info] 38#38: *8 client 172.22.0.6 closed keepalive connection (104: Connection reset by peer)
nginx_1    | 2019/04/05 11:27:15 [info] 38#38: *9 client 172.22.0.6 closed keepalive connection
nginx_1    | 2019/04/05 11:27:15 [info] 38#38: *15 client closed connection while waiting for request, client: 172.22.0.6, server: 0.0.0.0:80
nginx_1    | 2019/04/05 11:27:15 [info] 38#38: *16 client closed connection while waiting for request, client: 172.22.0.6, server: 0.0.0.0:80
nginx_1    | 2019/04/05 11:27:15 [info] 38#38: *17 client closed connection while waiting for request, client: 172.22.0.6, server: 0.0.0.0:80
nginx_1    | 2019/04/05 11:27:15 [info] 39#39: *10 client 172.22.0.6 closed keepalive connection
nginx_1    | 2019/04/05 11:27:15 [info] 39#39: *13 client 172.22.0.6 closed keepalive connection
nginx_1    | 2019/04/05 11:27:15 [info] 39#39: *11 client 172.22.0.6 closed keepalive connection
nginx_1    | 2019/04/05 11:27:15 [info] 39#39: *14 client 172.22.0.6 closed keepalive connection
nginx_1    | 2019/04/05 11:27:15 [info] 39#39: *12 client 172.22.0.6 closed keepalive connection
nginx_1    | 2019/04/05 11:27:15 [info] 38#38: *18 client closed connection while waiting for request, client: 172.22.0.6, server: 0.0.0.0:80
nginx_1    | 2019/04/05 11:27:15 [info] 38#38: *19 client closed connection while waiting for request, client: 172.22.0.6, server: 0.0.0.0:80
nginx_1    | 2019/04/05 11:27:15 [info] 38#38: *20 client closed connection while waiting for request, client: 172.22.0.6, server: 0.0.0.0:80
nginx_1    | 2019/04/05 11:27:15 [info] 38#38: *21 client closed connection while waiting for request, client: 172.22.0.6, server: 0.0.0.0:80
nginx_1    | 172.22.0.6 - - [05/Apr/2019:11:27:23 +0000] "POST /core/install.php HTTP/1.1" 302 464 "http://morphe.localhost/core/install.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:67.0) Gecko/20100101 Firefox/67.0"
nginx_1    | 172.22.0.6 - - [05/Apr/2019:11:27:24 +0000] "GET /core/install.php?langcode=en HTTP/1.1" 200 2970 "http://morphe.localhost/core/install.php" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:67.0) Gecko/20100101 Firefox/67.0"
nginx_1    | 172.22.0.6 - - [05/Apr/2019:11:27:28 +0000] "POST /core/install.php?langcode=en HTTP/1.1" 302 548 "http://morphe.localhost/core/install.php?langcode=en" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:67.0) Gecko/20100101 Firefox/67.0"
nginx_1    | 172.22.0.6 - - [05/Apr/2019:11:27:29 +0000] "GET /core/install.php?langcode=en&profile=standard HTTP/1.1" 200 4235 "http://morphe.localhost/core/install.php?langcode=en" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:67.0) Gecko/20100101 Firefox/67.0"
nginx_1    | 172.22.0.6 - - [05/Apr/2019:11:28:10 +0000] "POST /core/install.php?langcode=en&profile=standard HTTP/1.1" 302 636 "http://morphe.localhost/core/install.php?langcode=en&profile=standard" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:67.0) Gecko/20100101 Firefox/67.0"
nginx_1    | 172.22.0.6 - - [05/Apr/2019:11:28:11 +0000] "GET /core/install.php?langcode=en&profile=standard&id=1&op=start HTTP/1.1" 302 420 "http://morphe.localhost/core/install.php?langcode=en&profile=standard" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:67.0) Gecko/20100101 Firefox/67.0"
nginx_1    | 172.22.0.6 - - [05/Apr/2019:11:28:12 +0000] "GET /core/install.php/ HTTP/1.1" 404 718 "http://morphe.localhost/core/install.php?langcode=en&profile=standard" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:67.0) Gecko/20100101 Firefox/67.0"
nginx_1    | 172.22.0.6 - - [05/Apr/2019:11:34:09 +0000] "GET /some.php HTTP/1.1" 404 118 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:67.0) Gecko/20100101 Firefox/67.0"
nginx_1    | 172.22.0.6 - - [05/Apr/2019:11:34:09 +0000] "GET /favicon.ico HTTP/1.1" 200 43 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:67.0) Gecko/20100101 Firefox/67.0"
nginx_1    | 2019/04/05 11:34:09 [info] 38#38: *30 client 172.22.0.6 closed keepalive connection
nginx_1    | 172.22.0.6 - - [05/Apr/2019:11:34:20 +0000] "GET /index.php HTTP/1.1" 200 1310 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:67.0) Gecko/20100101 Firefox/67.0"
```
