### ISSUE TITLE
Xdebug stops working after updating

### ISSUE THREAD

**Issue by devkinetic** [wodby/docker4drupal#391]
***Codebase***
mounted

**Describe the bug**
I updated docker 4 drupal env and docker-compose to the latest release. After doing so I cannot get xdebug to work, the log is attached at the bottom. I'm using phpstorm. If set `PHP_XDEBUG_REMOTE_CONNECT_BACK: 0` i can connect once, and then it will hang forever, it always ends up at the index.php file. Previous to this, xdebug worked out of the box with the same config, i also see that the `IDEKEY` by default is `wodby` vs the older `my-ide`. I tried setting `PHP_XDEBUG_IDEKEY: PHPSTORM` which showed up in phpinfo() but had no further effect.

**Output of `docker info`**
```
'Containers: 217
 Running: 7
 Paused: 0
 Stopped: 210
Images: 117
Server Version: 18.09.2
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 9754871865f7fe2f4e74d43e2fc7ccd237edcbce
runc version: 09c8266bf2fcf9519a651b04ae54c967b9ab86ec
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 4.9.125-linuxkit
Operating System: Docker for Mac
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 3.855GiB
Name: linuxkit-025000000001
ID: WHFR:W5BW:HRV4:JPBG:SPGA:NHO4:N2YO:U7WE:FCOX:P3Y7:2ZNA:PMJ5
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 83
 Goroutines: 99
 System Time: 2019-07-24T21:48:00.196311848Z
 EventsListeners: 3
HTTP Proxy: gateway.docker.internal:3128
HTTPS Proxy: gateway.docker.internal:3129
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
Product License: Community Engine
```

**Contents of your `docker-compose.yml`**
```
version: "3"

services:
  mariadb:
    image: wodby/mariadb:$MARIADB_TAG
    container_name: "${PROJECT_NAME}_mariadb"
    stop_grace_period: 30s
    environment:
      MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
      MYSQL_DATABASE: $DB_NAME
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASSWORD

  php:
    image: wodby/drupal-php:$PHP_TAG
    container_name: "${PROJECT_NAME}_php"
    environment:
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
      PHP_UPLOAD_MAX_FILESIZE: 100M
      PHP_POST_MAX_SIZE: 100M
      DB_HOST: $DB_HOST
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
      DB_NAME: $DB_NAME
      DB_DRIVER: $DB_DRIVER
      PHP_FPM_USER: wodby
      PHP_FPM_GROUP: wodby
      COLUMNS: 80 # Set 80 columns for docker exec -it.
      PHP_XDEBUG: 1
      PHP_XDEBUG_DEFAULT_ENABLE: 1
      PHP_XDEBUG_IDEKEY: PHPSTORM
      PHP_XDEBUG_REMOTE_HOST: host.docker.internal  # Docker 18.03+ Mac/Win
      PHP_XDEBUG_REMOTE_PORT: 9071
      PHP_XDEBUG_REMOTE_LOG: /tmp/php-xdebug.log
    volumes:
      - ./:/var/www/html:cached # User-guided caching

  nginx:
    image: wodby/nginx:$NGINX_TAG
    container_name: "${PROJECT_NAME}_nginx"
    depends_on:
      - php
    environment:
      NGINX_STATIC_OPEN_FILE_CACHE: "off"
      NGINX_CLIENT_MAX_BODY_SIZE: 100m
      NGINX_CLIENT_BODY_TIMEOUT: 120s
      NGINX_ERROR_LOG_LEVEL: debug
      NGINX_BACKEND_HOST: php
      NGINX_SERVER_ROOT: /var/www/html/web
      NGINX_VHOST_PRESET: $NGINX_VHOST_PRESET
    volumes:
      - ./:/var/www/html:cached # User-guided caching
    labels:
      - 'traefik.backend=${PROJECT_NAME}_nginx'
      - 'traefik.port=80'
      - 'traefik.frontend.rule=Host:${PROJECT_BASE_URL}'

  mailhog:
    image: mailhog/mailhog
    container_name: "${PROJECT_NAME}_mailhog"
    labels:
      - 'traefik.backend=${PROJECT_NAME}_mailhog'
      - 'traefik.port=8025'
      - 'traefik.frontend.rule=Host:mailhog.${PROJECT_BASE_URL}'



  pma:
    image: phpmyadmin/phpmyadmin
    container_name: "${PROJECT_NAME}_pma"
    environment:
      PMA_HOST: $DB_HOST
      PMA_USER: $DB_USER
      PMA_PASSWORD: $DB_PASSWORD
      PHP_UPLOAD_MAX_FILESIZE: 1G
      PHP_MAX_INPUT_VARS: 1G
    labels:
      - 'traefik.backend=${PROJECT_NAME}_pma'
      - 'traefik.port=80'
      - 'traefik.frontend.rule=Host:pma.${PROJECT_BASE_URL}'

  solr:
    image: wodby/solr:$SOLR_TAG
    container_name: "${PROJECT_NAME}_solr"
    environment:
      SOLR_DEFAULT_CONFIG_SET: $SOLR_CONFIG_SET
      SOLR_HEAP: 1024m
    labels:
      - 'traefik.backend=${PROJECT_NAME}_solr'
      - 'traefik.port=8983'
      - 'traefik.frontend.rule=Host:solr.${PROJECT_BASE_URL}'
    volumes:
      - './solr:/opt/docker-solr/configsets/${SOLR_CONFIG_SET}'
```

**Contents of your `.env`**
```
### --- PROJECT SETTINGS ---

PROJECT_NAME=XXX
PROJECT_BASE_URL=XXXXXX

### --- DATABASE ---

DB_NAME=drupal
DB_USER=drupal
DB_PASSWORD=drupal
DB_ROOT_PASSWORD=password
#localhost or mariadb
DB_HOST=mariadb
DB_DRIVER=mysql

### --- MARIADB ----

MARIADB_TAG=10.3-3.6.1
#MARIADB_TAG=10.3-3.6.1
#MARIADB_TAG=10.1-3.6.1

### --- VANILLA DRUPAL ----

DRUPAL_TAG=8-4.14.4
#DRUPAL_TAG=7-4.14.4

### --- PHP ----

# macOS (uid 501 gid 20)
PHP_TAG=7.2-dev-macos-4.13.2

### --- NGINX ----

NGINX_TAG=1.15-5.2.1
NGINX_VHOST_PRESET=drupal8

### --- SOLR ---

SOLR_CONFIG_SET=drupal-6.5-solr-7.x
SOLR_TAG=7.4

### --- ELASTICSEARCH ---

ELASTICSEARCH_TAG=7-5.0.0

### --- KIBANA ---

KIBANA_TAG=7-5.0.0

### --- REDIS ---

REDIS_TAG=4-3.1.1

### --- NODE ---

NODE_TAG=12-0.19.0

### --- VARNISH ---

VARNISH_TAG=6.0-4.3.1

### --- POSTGRESQL ----

POSTGRES_TAG=11-1.7.1

### OTHERS

ADMINER_TAG=4-3.6.3
APACHE_TAG=2.4-4.1.1
ATHENAPDF_TAG=2.10.0
DRUPAL_NODE_TAG=1.0-2.0.0
MEMCACHED_TAG=1-2.3.1
OPENSMTPD_TAG=6.0-1.5.1
RSYSLOG_TAG=latest
WEBGRIND_TAG=1.5-1.11.2
XHPROF_TAG=1.4.2
```

**XDEBUG Logs**
```
[85] Log opened at 2019-07-24 21:39:57
[85] I: Checking remote connect back address.
[85] I: Checking header 'HTTP_X_FORWARDED_FOR'.
[85] I: Remote address found, connecting to 192.168.16.1:9071.
[85] W: Creating socket for '192.168.16.1:9071', poll success, but error: Operation in progress (29).
[85] E: Could not connect to client. :-(
```
