### ISSUE TITLE
Mariadb container can't start with volume

### ISSUE THREAD

**Issue by TheWorldNode** [wodby/docker4drupal#397]
Configured volume for mariadb service, to save the data, but faced the problem, when I try 

`docker-compose up -d`

Mariadb container starts, I see it "done", but after it instantly exites with the error in logs

```
Initializing database,
2019-08-25 18:45:52 0 [ERROR] InnoDB: The Auto-extending innodb_system data file './ibdata1' is of a different size 0 pages than specified in the .cnf file: initial 640 pages, max 655360 (relevant if non-zero) pages!,
2019-08-25 18:45:52 0 [ERROR] InnoDB: Plugin initialization aborted with error Generic error,
2019-08-25 18:45:52 0 [ERROR] Plugin 'InnoDB' init function returned error.,
2019-08-25 18:45:52 0 [ERROR] Plugin 'InnoDB' registration as a STORAGE ENGINE failed.,
2019-08-25 18:45:52 0 [ERROR] Unknown/unsupported storage engine: InnoDB,
2019-08-25 18:45:52 0 [ERROR] Aborting,
,
,
Installation of system tables failed!  Examine the logs in,
/var/lib/mysql/ for more information.,
,
The problem could be conflicting information in an external,
my.cnf files. You can ignore these by doing:,
,
    shell> /usr/bin/mysql_install_db --defaults-file=~/.my.cnf,
,
You can also try to start the mysqld daemon with:,
,
    shell> /usr/bin/mysqld --skip-grant-tables --general-log &,
,
and use the command line tool /usr/bin/mysql,
to connect to the mysql database and look at the grant tables:,
,
    shell> /usr/bin/mysql -u root mysql,
    mysql> show tables;,
,
Try 'mysqld --help' if you have problems with paths.  Using,
--general-log gives you a log in /var/lib/mysql/ that may be helpful.,
,
The latest information about mysql_install_db is available at,
https://mariadb.com/kb/en/installing-system-tables-mysql_install_db,
You can find the latest source at https://downloads.mariadb.org and,
the maria-discuss email list at https://launchpad.net/~maria-discuss,
,
Please check all of the above before submitting a bug report,
at http://mariadb.org/jira,
,
```

My docker-compose.yml

```
mariadb:
    image: wodby/mariadb:$MARIADB_TAG
    container_name: "${PROJECT_NAME}_mariadb"
    stop_grace_period: 30s
    environment:
      MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
      MYSQL_DATABASE: $DB_NAME
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASSWORD
    volumes:
      - ./local/mysql:/var/lib/mysql # Use bind mount
```

Using windows 10 and Hyper-V virtualization
