### ISSUE TITLE
elasticsearch vm.max_map_count

### ISSUE THREAD

**Issue by batkor** [wodby/docker4drupal#399]
**Elasticsearch**
ElasticSearch not run.

**Env file default**
```
### --- ELASTICSEARCH ---

ELASTICSEARCH_TAG=6.2-3.0.3
#ELASTICSEARCH_TAG=6.1-3.0.3
#ELASTICSEARCH_TAG=6.0-3.0.3
#ELASTICSEARCH_TAG=5.6-3.0.3
#ELASTICSEARCH_TAG=5.5-3.0.3
#ELASTICSEARCH_TAG=5.4-3.0.3

### --- KIBANA ---

KIBANA_TAG=6.2-3.0.4
#KIBANA_TAG=6.1-3.0.4
#KIBANA_TAG=6.0-3.0.4
#KIBANA_TAG=5.6-3.0.4
#KIBANA_TAG=5.5-3.0.4
#KIBANA_TAG=5.4-3.0.4
```

**Contents of your `docker-compose.yml`**
```
  elasticsearch:
    image: wodby/elasticsearch:$ELASTICSEARCH_TAG
    environment:
      ES_JAVA_OPTS: "-Xms500m -Xmx500m"
    ulimits:
      memlock:
        soft: -1
        hard: -1

  kibana:
    image: wodby/kibana:$KIBANA_TAG
    depends_on:
      - elasticsearch
    labels:
      - 'traefik.backend=${PROJECT_NAME}_kibana'
      - 'traefik.port=5601'
      - 'traefik.frontend.rule=Host:kibana.php.docker.localhost'
```
**docker-composer up log**
```
elasticsearch_1  | [2019-09-01T08:22:49,647][INFO ][o.e.b.BootstrapChecks    ] [8aa35522-45d1-4678-b464-1b8e6e82d87f] bound or publishing to a non-loopback address, enforcing bootstrap checks
elasticsearch_1  | ERROR: [1] bootstrap checks failed
elasticsearch_1  | [1]: max virtual memory areas vm.max_map_count [65530] is too low, increase to at least [262144]
elasticsearch_1  | [2019-09-01T08:22:49,678][INFO ][o.e.n.Node               ] [8aa35522-45d1-4678-b464-1b8e6e82d87f] stopping ...
elasticsearch_1  | [2019-09-01T08:22:49,765][INFO ][o.e.n.Node               ] [8aa35522-45d1-4678-b464-1b8e6e82d87f] stopped
elasticsearch_1  | [2019-09-01T08:22:49,766][INFO ][o.e.n.Node               ] [8aa35522-45d1-4678-b464-1b8e6e82d87f] closing ...
elasticsearch_1  | [2019-09-01T08:22:49,807][INFO ][o.e.n.Node               ] [8aa35522-45d1-4678-b464-1b8e6e82d87f] closed
```
Add docker-composer.yml `sysctls` options
```
 elasticsearch:
    image: wodby/elasticsearch:$ELASTICSEARCH_TAG
    sysctls:
      vm.max_map_count: 262144
    environment:
      ES_JAVA_OPTS: "-Xms500m -Xmx500m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
```
After run docker-compose getted error
```
ERROR: for elasticsearch  Cannot start service elasticsearch: OCI runtime create failed: sysctl "vm.max_map_count" is not in a separate kernel namespace: unknown

```
