### ISSUE TITLE
wodby.settings.php: No such file or directory

### ISSUE THREAD

**Issue by FlxAlbroscheit** [wodby/docker4drupal#405]
***Codebase***
Mounted codebase

**Describe your issue**

Got stuck in a problem ever since I played around with my docker4drupal containers. When I run "docker-compose up" I get the error message from php container "/docker-entrypoint.sh: line 13: /var/www/conf/wodby.settings.php: No such file or directory" (wodby/drupal-php:7.2-dev-4.12.9). As a result, the php (and nginx) container fails to start so I can not "docker exec my_project_php" anything. Choosing PHP 7.3 in .env had no effects either.

Before the problem started I added a custom Dockerfile to my repository and run "docker build -f Dockerfile ." so it seems like the script of inside php's parent Dockerfile (https://github.com/wodby/php/blob/master/7/Dockerfile) was not executed. Removing the troublesome container + php-image and running "docker-compose up" again had no effects. So how can I "re-run" the initial install script?

This problem may be related to wodby/drupal-php. Thank you very much.

**Output of `docker info`**
```
Client:
 Debug Mode: false

Server:
 Containers: 10
  Running: 1
  Paused: 0
  Stopped: 9
 Images: 29
 Server Version: 19.03.2
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc version: 425e105d5a03fabd737a126ad93d62a9eeede87f
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.2.11-100.fc29.x86_64
 Operating System: Fedora 29 (Twenty Nine)
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 7.415GiB
 Name: localhost.localdomain
 ID: UAFM:CC7J:UNIF:LXF2:DR2G:WV7U:7BRA:USTW:YZYG:TUVD:7P25:XZFT
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

```

**Contents of your `docker-compose.yml`**
Same as in latest release, but modified the volume for php
```
  php:
    image: wodby/drupal-php:$PHP_TAG
    container_name: "${PROJECT_NAME}_php"
    environment:
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
      DB_HOST: $DB_HOST
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
      DB_NAME: $DB_NAME
      DB_DRIVER: $DB_DRIVER
      PHP_FPM_USER: wodby
      PHP_FPM_GROUP: wodby
      COLUMNS: 80 # Set 80 columns for docker exec -it.
    volumes:
      - ./:/var/www/
```

**Contents of your `.env`**
```
...
MARIADB_TAG=10.3-3.6.3
PHP_TAG=7.2-dev-4.12.9
NGINX_TAG=1.17-5.6.7
NGINX_VHOST_PRESET=drupal7
...
```

**Logs output `docker-compose logs`**
```
my_project_php | /docker-entrypoint.sh: line 13: /var/www/conf/wodby.settings.php: No such file or directory
...
my_project_nginx | nginx: [emerg] host not found in upstream "php:9000" in /etc/nginx/upstream.conf:2
my_project_nginx exited with code 1

```
