### ISSUE TITLE
Traefik v2 https support

### ISSUE THREAD

**Issue by 2dareis2do** [wodby/docker4drupal#407]
I am am trying to up the latest version of docker4drupal to work with Traefik v2. I had it working previously with v1.x of Traefik but am struggling to transition to configure v2.

I have tried to follow the lets encrypt guidelines on traefik website but there seems to be some issue with generating the certificate on a dev environment. 

Any guidelines on how to achieve this would be welcome.

**Comment by MenkaHosting** [comment]
https://blog.containo.us/traefik-2-0-docker-101-fc2893944b9d

**Comment by dhaley** [comment]
Hi, has anyone gotten a self-signed TLS cert to work with Traefik 2.0?

I'm looking for the easiest way to set up and maintain this for a dev environment.  

Here is my setup:


### docker-compose.yml

```
nginx:
  image: wodby/nginx:$NGINX_TAG
  container_name: "${PROJECT_NAME}_nginx"
  depends_on:
    - php
  environment:
    NGINX_STATIC_OPEN_FILE_CACHE: "off"
    NGINX_ERROR_LOG_LEVEL: debug
    NGINX_BACKEND_HOST: php
    NGINX_SERVER_ROOT: /var/www/html/web
    NGINX_VHOST_PRESET: $NGINX_VHOST_PRESET
  volumes:
    - ./:/var/www/html
    - docker-sync-unison:/var/www/common # Docker-sync for macOS users
  labels:
    - "traefik.http.routers.${PROJECT_NAME}_nginx.rule=Host(`${PROJECT_BASE_URL}`)"
    - "traefik.http.routers.${PROJECT_NAME}_nginx.tls=true"
    - "traefik.http.routers.${PROJECT_NAME}_nginx.tls.options=default"
```

### traefik.yml

Place it separately from your projects and start with **docker-compose -f traefik.yml up**

```
version: '3'

services:
  traefik:
    image: traefik:v2.0
    command:
      - "--api.insecure=true"
      - "--providers.docker"
      - "--log.level=DEBUG"
    networks:
      - "xxxx"
    ports:
      - '80:80'
      - '8080:8080'
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./certs:/certs/     # per cbeier at https://github.com/wodby/docker4drupal/issues/50
      - ./conf/dyn_conf.toml:/etc/traefik/conf/dyn_conf.toml:ro


networks:
  xxxx:
    external:
      name: xxxx_default
```

### dyn_conf.toml

```
# Dynamic configuration

[[tls.certificates]]
  certFile = "/certs/cert.pem"
  keyFile = "/certs/key.pem"
```


I've tried following the instructions here:

https://docs.traefik.io/https/tls/#user-defined

and here:

https://docs.traefik.io/migration/v1-to-v2/#tls-configuration-is-now-dynamic-per-router

Please advise if anyone has gotten this working with either user defined certs or Lets Encrypt:

**Comment by dmitrymenshikov** [comment]
### To enable https you need to do only 2 steps

1. Enable automatic cetrifs generation

```
services:
  traefik:
    image: "traefik:v2.0.0"
    command:
      # add these lines
      - --entrypoints.websecure.address=:443
      - --certificatesresolvers.le.acme.email=my@email.com
      - --certificatesresolvers.le.acme.storage=/acme.json
      - --certificatesresolvers.le.acme.tlschallenge=true
    ports:
      # add 443 port
      - "443:443"
```
my@email.com - change on yours email address

2. Enable automatic certifs generation for container (e.g. nginx)

 ```
 nginx:
    image: wodby/nginx:$NGINX_TAG
    container_name: "${PROJECT_NAME}_nginx"
    depends_on:
      - php
    environment:
      NGINX_STATIC_OPEN_FILE_CACHE: "off"
      NGINX_ERROR_LOG_LEVEL: debug
      NGINX_BACKEND_HOST: php
      NGINX_SERVER_ROOT: /var/www/html/web
      NGINX_VHOST_PRESET: $NGINX_VHOST_PRESET
    volumes:
      - ./:/var/www/html
    labels:
      - "traefik.http.routers.${PROJECT_NAME}_nginx.rule=Host(`${PROJECT_BASE_URL}`)"
     # add these lines
      - "traefik.http.routers.${PROJECT_NAME}_nginx.tls.certresolver=le"
      - "traefik.http.routers.${PROJECT_NAME}_nginx.entrypoints=websecure"
```

Complete.

**Comment by jcisio** [comment]
Could you explain it? I use it for local development so no LE ACME for me. I use mkcert to generate certificates and Traefik works with both http and https. However it shows the website in http, and the "404 page not found" error in https. How to setup to redirect https traffic to the other containers (Apache, phpMyAdmin etc.) on port 80 so that Traefik does the TLS termination here?

**Comment by divined** [comment]
docker-compose.yml
```yaml
  nginx:
    image: wodby/nginx:$NGINX_TAG
    container_name: "${PROJECT_NAME}_nginx"
    depends_on:
      - php
    environment:
      NGINX_STATIC_OPEN_FILE_CACHE: "off"
      NGINX_CLIENT_MAX_BODY_SIZE: 10G
      NGINX_ERROR_LOG_LEVEL: debug
      NGINX_BACKEND_HOST: php
      NGINX_VHOST_PRESET: php
      NGINX_SERVER_ROOT: /var/www/html/public
      NGINX_STATIC_EXT_REGEX: css|cur|js|htc|ico|xml|otf|ttf|eot|woff|woff2|svg|mp4|svgz|ogg|ogv|pdf|pptx?|zip|tgz|gz|rar|bz2|doc|xls|exe|tar|mid|midi|wav|bmp|rtf|txt|map
    volumes:
      - ./:/var/www/html
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${PROJECT_NAME}_nginx.entrypoints=http"
      - "traefik.http.routers.${PROJECT_NAME}_nginx.rule=Host(`${PROJECT_NAME}.localhost`)"
      - "traefik.http.middlewares.${PROJECT_NAME}_nginx-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.${PROJECT_NAME}_nginx.middlewares=${PROJECT_NAME}_nginx-https-redirect"
      - "traefik.http.routers.${PROJECT_NAME}_nginx-secure.entrypoints=https"
      - "traefik.http.routers.${PROJECT_NAME}_nginx-secure.rule=Host(`${PROJECT_NAME}.localhost`)"
      - "traefik.http.routers.${PROJECT_NAME}_nginx-secure.tls=true"
      - "traefik.http.routers.${PROJECT_NAME}_nginx-secure.service=${PROJECT_NAME}_nginx"
      - "traefik.http.services.${PROJECT_NAME}_nginx.loadbalancer.server.port=80"
```
traefik.yml
```yaml
api:
  dashboard: true

log:
  level: DEBUG
  filePath: "debug.log"
  format: json

accessLog:
  filePath: "access.log"
  bufferingSize: 100

entryPoints:
  http:
    address: ":80"
  https:
    address: ":443"

providers:
  file:
    filename: /traefik.dynamic.yml
    watch: true
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
```
traefik.dynamic.yml
```yaml
tls:
  stores:
    default:
      defaultCertificate:
        certFile: /certs/localhost+5.pem
        keyFile: /certs/localhost+5-key.pem
  certificates:
    - certFile: /certs/localhost+5.pem
      keyFile: /certs/localhost+5-key.pem
```
certificates are generated by mkcert ${PROJECT_NAME}.localhost, varnish.${PROJECT_NAME}.localhost traefik.localhost and localhost.

Need to replace ${PROJECT_NAME} to your project name.

**Comment by kevinquillen** [comment]
Can folks actually explain the examples beyond just pasting code above? The setup for v1 was pretty simple but v2 is not working at all.

> However it shows the website in http, and the "404 page not found" error in https.

This is exactly my experience. I was looking here, which a handful of places on the net keep referencing: https://containo.us/blog/traefik-2-0-docker-101-fc2893944b9d/

I found that article confusing, the blog post links to multiple files in git and each one is slightly different.

To get HTTP -> HTTPS redirection working, I finally stumbled upon [this post](https://chriswiegman.com/2019/10/serving-your-docker-apps-with-https-and-traefik-2/). Adapting that, I was finally able to get a self signed certificate and https redirection working.

Here is what I have:

```
  apache:
    image: wodby/apache:$APACHE_TAG
    container_name: "${PROJECT_NAME}_apache"
    environment:
      APACHE_LOG_LEVEL: debug
      APACHE_BACKEND_HOST: php
      APACHE_VHOST_PRESET: php
      APACHE_DOCUMENT_ROOT: /var/www/html/docroot
    volumes:
      - ./:/var/www/html:cached # User-guided caching
    labels:
      - traefik.http.middlewares.${PROJECT_NAME}_apache_https.redirectscheme.scheme=https
      - traefik.http.routers.${PROJECT_NAME}_apache.entrypoints=web
      - traefik.http.routers.${PROJECT_NAME}_apache.rule=Host(`${PROJECT_BASE_URL}`)
      - traefik.http.routers.${PROJECT_NAME}_apache.middlewares=${PROJECT_NAME}_apache_https@docker
      - traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https
      - traefik.http.routers.${PROJECT_NAME}_apache_https.rule=Host(`${PROJECT_BASE_URL}`)
      - traefik.http.routers.${PROJECT_NAME}_apache_https.tls=true
      - traefik.http.routers.${PROJECT_NAME}_apache_https.entrypoints=websecure

  traefik:
    image: traefik:v2.0
    container_name: "${PROJECT_NAME}_traefik"
    command:
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --providers.docker
      - --providers.file.directory=/etc/traefik/dynamic_conf
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./tools/certs:/tools/certs
      - ./tools/traefik/config.yml:/etc/traefik/dynamic_conf/conf.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock
```

traefik config.yml:

```
tls:
  certificates:
    - certFile: /tools/certs/cert.crt
      keyFile: /tools/certs/cert.key
```

Note that the labels in each service are _very_ particular about format, and double check you have no spelling errors. The apache labels are important, as it describes the entrypoints and what to do with them.

This was a lot harder to figure out than I was expecting, and depending on where you look on the internet there are various write ups on what to do. Nothing worked except for the blog post above. The contanious one is confusing and was of no help whatsoever.

This answer was helpful: https://stackoverflow.com/a/60072381/295112

IMO it would be super helpful for docker4drupal to come with HTTPS enabled and redirecting by default since that is how all production applications are running these days anyway. It shouldn't take hours to figure out how to make it happen (blaming traefik not d4d maintainers) and it seems we are not the only ones.

**Comment by mradcliffe** [comment]
Unfortunately I haven't had luck with getting the http to https redirect to work.

I keep getting `field not found redirectscheme` and when commenting out the first line, I also then get `middleware \"docker4drupal_apache_https@docker\" does not exist"`.

Otherwise the configuration worked for https and http.

**Comment by mradcliffe** [comment]
I think the issue for me ended up being `- traefik.http.routers.${PROJECT_NAME}_apache.middlewares=${PROJECT_NAME}_apache_https@docker`, and removing `@docker` from the end. Then Kevin's configuration worked for me.

**Comment by Mykola-Veryha** [comment]
https://docs.traefik.io/user-guides/docker-compose/acme-tls/

**Comment by MrUpsidown** [comment]
> It helped me. There are enough instructions to understand how to configure that
> 
> https://docs.traefik.io/user-guides/docker-compose/acme-tls/
> 

That page mentions:

For the TLS challenge you will need:
- A publicly accessible host allowing connections on port 443 with docker & docker-compose installed.

Are we not talking about local dev environments here??
So this is unrelated + again, everyone, please stop just dumping code here without any further explanation.

**Comment by MrUpsidown** [comment]
On an older Traefik version on a LOCAL development environment, on macOS, I got HTTPS working the following way:

**docker-compose.yml**:

```
  traefik:
    image: traefik:v1.7.16-alpine
    container_name: "${PROJECT_NAME}_traefik"
    command: -c /dev/null --web --docker --logLevel=INFO --defaultEntryPoints='https' --entryPoints="Name:https Address::443 TLS:/certs/mysite_cert.pem,/certs/mysite_cert-key.pem" --entryPoints="Name:http Address::80 Redirect.EntryPoint:https"
    ports:
      - '8000:80'
      - '443:443'
    volumes:
      - ./certs:/certs/
      - /var/run/docker.sock:/var/run/docker.sock
```

`mysite_cert.pem` and `mysite_cert-key.pem` needs to be adjusted to your own certificates naming.

I generated self-signed certificates using mkcert, see: https://github.com/FiloSottile/mkcert/blob/master/README.md

I placed the certificates in a `certs` folder, at the project root (where docker-compose.yml file is).
There is no redirection. Only direct access on HTTPS, but it works and is sufficient for my needs. 

Note that I was still getting errors with the above settings until I restarted Docker desktop then all went fine.

**Comment by SegaWeb** [comment]
Hello everyone

Can anyone drop a complete example of a working configuration for traefik 2? I tried everything, and I still can't configure it.

The maximum that was achieved is that an empty acme.json file appears and, accordingly, the certificate is not valid in the browser

**Comment by mradcliffe** [comment]
I can't post a full example because there's a lot of information that's not relevant in the YAML file, but I can post the relevant sections for my apache, mailhog, adminer, and traefik service definitions.
 
1. Generate a self-signed certificate with openssl in a `certs/` directory (default.crt, default.key) within docker4drupal directory.
2. Create the following traefik.yml file in the docker4drupal directory.
```
tls:
  certificates:
    - certFile: /certs/default.crt
      keyFile: /certs/default.key
```
3. Configure the traefik service in docker-compose.yml
```
  traefik:
    image: traefik:v2.1
    container_name: "${PROJECT_NAME}_traefik"
    command:
      - --entrypoints.db.address=:5432
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --api.insecure=true
      - --providers.docker
      - --providers.file.directory=/etc/traefik/dynamic_conf
    ports:
      - '80:80'
      - '443:443'
      - '8080:8080' # Dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/etc/traefik/dynamic_conf/conf.yml:ro
      - ./certs:/certs
```
4. Add the labels to relevant services in docker-compose.yml
```
  postgresql:
    labels:
      - "traefik.tcp.services.postgresql.loadbalancer.server.port=5432"
      - "traefik.tcp.routers.${PROJECT_NAME}_db.entrypoints=db"
      - "traefik.tcp.routers.${PROJECT_NAME}_db.rule=HostSNI(`${PROJECT_BASE_URL}`)"
      - "traefik.tcp.routers.${PROJECT_NAME}_db.service=postgresql"

  apache:
    labels:
      - "traefik.http.middlewares.${PROJECT_NAME}_apache_https.redirectscheme.scheme=https"
      - "traefik.http.routers.${PROJECT_NAME}_apache.entrypoints=web"
      - "traefik.http.routers.${PROJECT_NAME}_apache.middlewares=${PROJECT_NAME}_apache_https"
      - "traefik.http.routers.${PROJECT_NAME}_apache.rule=Host(`${PROJECT_BASE_URL}`)"
      - "traefik.http.routers.${PROJECT_NAME}_apache_https.rule=Host(`${PROJECT_BASE_URL}`)"
      - "traefik.http.routers.${PROJECT_NAME}_apache_https.tls=true"
      - "traefik.http.routers.${PROJECT_NAME}_apache_https.entrypoints=websecure"

  adminer:
    labels:
      - "traefik.http.routers.${PROJECT_NAME}_adminer.rule=Host(`admin.${PROJECT_BASE_URL}`)"

  mailhog:
    labels:
      - "traefik.http.services.${PROJECT_NAME}_mailhog.loadbalancer.server.port=8025"
      - "traefik.http.routers.${PROJECT_NAME}_mailhog.rule=Host(`mail.${PROJECT_BASE_URL}`)"
```

**Comment by o771e** [comment]
This post must be pinned somehow.

**Comment by artemvd** [comment]
for me solution from @dmitrymenshikov worked locally. I don't need automatic redirect. No other things are required. Tested on Drupal 9

**Comment by 2dareis2do** [comment]
When using cert resolvers with '.internal' domain I seemed to have an issue with the cert resolvers. @kevinquillen answer worked for me, albeit switching from nginx to apache. 

Not sure it there is any update on this as this is quite an old thread now but had issues adding a self signed cert when  updating from 3 to 3.7 or specifically to traefik v2?

**Comment by deakjahn** [comment]
A few years have passed again, and none of the above was helpful in its entirety, although I coul finally come up with a full solution.

1. Add a `certs` folder, create a key and a certificate. I used the following:

`openssl req -x509 -newkey rsa:4096 -keyout key.pem -out cert.pem -sha512 -days 3650 -nodes -subj "/C=XX/ST=XXX/L=XXX/O=XXX/OU=XXX/CN=teszt.local" -addext "subjectAltName=DNS:teszt.local,IP:127.0.0.1"`

The various entries are up to you, the important part is the **CN** and the **subjectAltName.** Make sure you use the local domain you want to use for the development.

2. At least on Windows, a `.crt` is needed to add to the certificates recognized by the system. You can convert the above with:

`openssl x509 -outform der -in cert.pem -out cert.crt`

Install it among your certificates, user or computer, among the Trusted Root Cert Authorities.

3. Have a `traefik.yml` with the following:

```
tls:
  stores:
    default:
      defaultCertificate:
        certFile: /certs/cert.pem
        keyFile: /certs/key.pem
  certificates:
    - certFile: /certs/cert.pem
      keyFile: /certs/key.pem
```

Note that the file has to be standalone! If you already have a `traefik.yml` with other settings, you can't place this inside the same file. This needs to be a separate, dynamic conf file for the certificate and nothing else. I have all my other Traefik settings in the main `compose.yml` (see next), so this worked for me.

4. Modifications for the main compose file:

```
  traefik:
    image: traefik:v2.0
    container_name: "${PROJECT_NAME}_traefik"
    command:
      - --entrypoints.db.address=:${DB_PORT}
      - --entrypoints.web.address=:${PROJECT_PORT}
      - --entrypoints.websecure.address=:443
      - --api.insecure=true
      - --providers.docker
      - --providers.file.directory=/etc/traefik/dynamic_conf
    labels:
      # middleware redirect
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      # global redirect to https
      - "traefik.http.routers.redirs.rule=hostregexp(`{host:.+}`)"
      - "traefik.http.routers.redirs.entrypoints=web"
      - "traefik.http.routers.redirs.middlewares=redirect-to-https"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080" # Dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/etc/traefik/dynamic_conf/conf.yml:ro
      - ./certs:/certs/
```

Entrypoints, settings come here, leaving `traefik.yml` only for the certificate. The `providers.file˙ together with the volume make Traefik recognize the cert config file.

```
  nginx:
    ...
    labels:
      - "traefik.http.routers.${PROJECT_NAME}_nginx.rule=Host(`${PROJECT_BASE_URL}`)"
      - "traefik.http.routers.${PROJECT_NAME}_nginx.entrypoints=websecure"
      - "traefik.http.routers.${PROJECT_NAME}_nginx.tls=true"
```
