### ISSUE TITLE
Usage of ngrok

### ISSUE THREAD

**Issue by timdiels1** [wodby/docker4drupal#424]
***Codebase***
Mounted codebase

**Describe your issue**
I would like to use ngrok to use webhook urls for payment providers.
To try using ngrok, I added the following snippet to docker-compose.yml
But not sure about the service and the port...
```
  ngrok:
    image: nginx
    container_name: "${PROJECT_NAME}_ngrok"
    volumes:
      - ./ngrok:/code/
    #command: /code/ngrok http <APP SERVICE>:<APP PORT> --subdomain=<RESERVED DOMAIN> -config=/code/ngrok.conf
    command: /code/ngrok http php:8080 -config=/code/ngrok.conf
    links:
      - php
    ports:
      - 4040:4040
```
**Output of `docker info`**
```
Client:
 Debug Mode: false

Server:
 Containers: 18
  Running: 10
  Paused: 0
  Stopped: 8
 Images: 40
 Server Version: 19.03.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: b34a5c8af56e510852c35414db4c1f4fa6172339
 runc version: 3e425f80a8c931f88e6d94a8c831b9d5aa481657
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.9.184-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 3
 Total Memory: 7.787GiB
 Name: docker-desktop
 ID: RD7F:TR5W:5ZDR:23LD:U3U7:O2TE:FXXZ:BZ55:U3PY:I4OP:T2PO:A6L4
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 140
  Goroutines: 152
  System Time: 2020-03-03T20:15:05.92638Z
  EventsListeners: 17
 HTTP Proxy: gateway.docker.internal:3128
 HTTPS Proxy: gateway.docker.internal:3129
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: true
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

**Contents of your `docker-compose.yml`**
```
version: "3"

services:
  mariadb:
    image: wodby/mariadb:$MARIADB_TAG
    container_name: "${PROJECT_NAME}_mariadb"
    stop_grace_period: 30s
    environment:
      MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
      MYSQL_DATABASE: $DB_NAME
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASSWORD
    ports:
      - 3306

  php:
    image: wodby/drupal-php:$PHP_TAG
    container_name: "${PROJECT_NAME}_php"
    environment:
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
      DB_HOST: $DB_HOST
      DB_PORT: $DB_PORT
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
      DB_NAME: $DB_NAME
      DB_DRIVER: $DB_DRIVER
      PHP_FPM_USER: wodby
      PHP_FPM_GROUP: wodby
      COLUMNS: 80 # Set 80 columns for docker exec -it.
    volumes:
      - ./../:/var/www/html:cached # User-guided caching

  nginx:
    image: wodby/nginx:$NGINX_TAG
    container_name: "${PROJECT_NAME}_nginx"
    depends_on:
      - php
    environment:
      NGINX_STATIC_OPEN_FILE_CACHE: "off"
      NGINX_ERROR_LOG_LEVEL: debug
      NGINX_BACKEND_HOST: php
      NGINX_SERVER_ROOT: /var/www/html/web
      NGINX_VHOST_PRESET: $NGINX_VHOST_PRESET
    volumes:
      - ./../:/var/www/html:cached # User-guided caching
    labels:
      - "traefik.http.routers.${PROJECT_NAME}_nginx.rule=Host(`${PROJECT_BASE_URL}`)"

  mailhog:
    image: mailhog/mailhog
    container_name: "${PROJECT_NAME}_mailhog"
    labels:
      - "traefik.http.services.${PROJECT_NAME}_mailhog.loadbalancer.server.port=8025"
      - "traefik.http.routers.${PROJECT_NAME}_mailhog.rule=Host(`mailhog.${PROJECT_BASE_URL}`)"

  pma:
    image: phpmyadmin/phpmyadmin
    container_name: "${PROJECT_NAME}_pma"
    environment:
      PMA_HOST: $DB_HOST
      PMA_USER: $DB_USER
      PMA_PASSWORD: $DB_PASSWORD
      PHP_UPLOAD_MAX_FILESIZE: 1G
      PHP_MAX_INPUT_VARS: 1G
    labels:
      - "traefik.http.routers.${PROJECT_NAME}_pma.rule=Host(`pma.${PROJECT_BASE_URL}`)"

  drupal-node:
    image: wodby/drupal-node:$DRUPAL_NODE_TAG
    container_name: "${PROJECT_NAME}_drupal_nodejs"
    environment:
      NODE_SERVICE_KEY: node-service-key
      NODE_BACKEND_PORT: 8080
      NODE_BACKEND_HOST: drupal-node
      NODE_DEBUG: 1
    labels:
      - "traefik.http.routers.${PROJECT_NAME}_drupal_node.rule=Host(`drupal_node.${PROJECT_BASE_URL}`)"

  node:
    image: wodby/node:$NODE_TAG
    container_name: "${PROJECT_NAME}_node"
    working_dir: /var/www/html
    labels:
      - "traefik.http.services.${PROJECT_NAME}_node.loadbalancer.server.port=3000"
      - "traefik.http.routers.${PROJECT_NAME}_node.rule=Host(`node.${PROJECT_BASE_URL}`)"
    expose:
      - "3000"
    volumes:
      - ./../:/var/www/html
    command: sh -c 'npm install'

  portainer:
    image: portainer/portainer
    container_name: "${PROJECT_NAME}_portainer"
    command: --no-auth -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.http.routers.${PROJECT_NAME}_portainer.rule=Host(`portainer.${PROJECT_BASE_URL}`)"

  traefik:
    image: traefik:v2.0
    container_name: "${PROJECT_NAME}_traefik"
    command: --api.insecure=true --providers.docker
    ports:
      - '8000:80'
      - '8080:8080' # Dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  ngrok:
    image: nginx
    container_name: "${PROJECT_NAME}_ngrok"
    volumes:
      - ./ngrok:/code/
    #command: /code/ngrok http <APP SERVICE>:<APP PORT> --subdomain=<RESERVED DOMAIN> -config=/code/ngrok.conf
    command: /code/ngrok http php:8080 -config=/code/ngrok.conf
    links:
      - php
    ports:
      - 4040:4040
```

**Contents of your `.env`**
```
### Documentation available at https://wodby.com/docs/stacks/drupal/local
### Changelog can be found at https://github.com/wodby/docker4drupal/releases
### Images tags format explained at https://github.com/wodby/docker4drupal#images-tags

### PROJECT SETTINGS

PROJECT_NAME=***
PROJECT_BASE_URL=***.docker.localhost

DB_NAME=gyldenore
DB_USER=drupal
DB_PASSWORD=drupal
DB_ROOT_PASSWORD=password
DB_HOST=mariadb
DB_PORT=3306
DB_DRIVER=mysql

### --- MARIADB ----

MARIADB_TAG=10.4-3.7.6
#MARIADB_TAG=10.3-3.7.6
#MARIADB_TAG=10.2-3.7.6
#MARIADB_TAG=10.1-3.7.6

### --- VANILLA DRUPAL ----

DRUPAL_TAG=8-4.17.2
#DRUPAL_TAG=7-4.17.2

### --- PHP ----

# Linux (uid 1000 gid 1000)

PHP_TAG=7.3-dev-4.15.1
#PHP_TAG=7.2-dev-4.15.1
#PHP_TAG=7.4-dev-4.15.1

# macOS (uid 501 gid 20)

#PHP_TAG=7.3-dev-macos-4.15.1
#PHP_TAG=7.2-dev-macos-4.15.1
#PHP_TAG=7.4-dev-macos-4.15.1

### --- NGINX ----

NGINX_TAG=1.17-5.8.6
#NGINX_TAG=1.16-5.8.6

NGINX_VHOST_PRESET=drupal8
#NGINX_VHOST_PRESET=drupal7
#NGINX_VHOST_PRESET=drupal6

### --- SOLR ---

SOLR_CONFIG_SET="search_api_solr_8.x-3.2"
#SOLR_CONFIG_SET="search_api_solr_8.x-2.7"
#SOLR_CONFIG_SET="search_api_solr_8.x-1.2"
#SOLR_CONFIG_SET="search_api_solr_7.x-1.14"

SOLR_TAG=8-4.4.0
#SOLR_TAG=7-4.4.0
#SOLR_TAG=6-4.4.0
#SOLR_TAG=5-4.4.0

### --- ELASTICSEARCH ---

ELASTICSEARCH_TAG=7-5.4.0
#ELASTICSEARCH_TAG=6-5.4.0

### --- KIBANA ---

KIBANA_TAG=7-5.4.0
#KIBANA_TAG=6-5.4.0

### --- REDIS ---

REDIS_TAG=4-3.2.2
#REDIS_TAG=5-3.2.2

### --- NODE ---

NODE_TAG=12-dev-0.33.1
#NODE_TAG=10-dev-0.33.1
#NODE_TAG=8-dev-0.33.1

### --- VARNISH ---

VARNISH_TAG=6.0-4.4.4
#VARNISH_TAG=4.1-4.4.4

### --- POSTGRESQL ----

POSTGRES_TAG=12-1.9.1
#POSTGRES_TAG=11-1.9.1
#POSTGRES_TAG=10-1.9.1
#POSTGRES_TAG=9.6-1.9.1
#POSTGRES_TAG=9.5-1.9.1
#POSTGRES_TAG=9.4-1.9.1

### OTHERS

ADMINER_TAG=4-3.9.3
APACHE_TAG=2.4-4.2.3
ATHENAPDF_TAG=2.10.0
DRUPAL_NODE_TAG=1.0-2.0.0
MEMCACHED_TAG=1-2.4.1
OPENSMTPD_TAG=6.0-1.6.3
RSYSLOG_TAG=latest
SELENIUM_CHROME_TAG=3.141
WEBGRIND_TAG=1-1.14.2
XHPROF_TAG=2.1.2

```

**Comment by devkinetic** [comment]
You can get ngrok to work, and this happens through traefik, but your run into issues with cookies and sessions being set to the internal url vs the ngrok url. I haven't solved this yet in D4D but it seems they did this in lando. I'm pretty sure it has something to do with exposing the applications as localhost in traefik and not as name.docker.localhost. If we could get this worked out it would be awesome.

**Comment by timdiels1** [comment]
Ok after some more trying i got this to work with the following:

```yml
ngrok:
    image: wernight/ngrok
    container_name: "${PROJECT_NAME}_ngrok"
    ports:
      - '4040:4040' # http://localhost:4040/
    environment:
      NGROK_PORT: nginx:80
      NGROK_AUTH: $NGROK_AUTH
      NGROK_REGION: 'eu'
    links:
      - nginx
```

Make sure to add NGROK_AUTH in your .env file with the correct token.
You could also change the region and use it as a env variable.
