### ISSUE TITLE
Mounted volumes are missing

### ISSUE THREAD

**Issue by KevinBriand** [wodby/docker4drupal#430]
***Codebase***
Mounted codebase

**Describe your issue**
I installed Drupal using [drupal-projet](https://github.com/drupal-composer/drupal-project), then cloned docker4drupal. Changed the docker-compose.yml file, mainly to use apache instead of nginx. At this point my folder looks like this:

```
username@machinename:/mnt/c/devhome/drupal_local$ ll
total 384
drwxrwxrwx 1 username username   4096 Apr  6 18:13 ./
drwxrwxrwx 1 username username   4096 Apr  6 16:35 ../
-rwxrwxrwx 1 username username    357 Apr  5 19:18 .editorconfig*
-rwxrwxrwx 1 username username    762 Apr  6 18:08 .env*
-rwxrwxrwx 1 username username   3858 Apr  5 19:18 .gitattributes*
-rwxrwxrwx 1 username username     20 Mar 31 20:10 .gitignore*
drwxrwxrwx 1 username username   4096 Apr  6 18:32 .idea/
-rwxrwxrwx 1 username username    678 Mar 31 20:10 .travis.yml*
-rwxrwxrwx 1 username username  18046 Mar 31 20:02 LICENSE*
-rwxrwxrwx 1 username username   1076 Mar 31 20:10 LICENSE.md*
-rwxrwxrwx 1 username username    128 Mar 31 20:10 Makefile*
-rwxrwxrwx 1 username username   8792 Mar 31 20:10 README.md*
-rwxrwxrwx 1 username username   2370 Mar 31 20:02 composer.json*
-rwxrwxrwx 1 username username 329155 Apr  5 19:18 composer.lock*
drwxrwxrwx 1 username username   4096 Apr  6 16:35 docker/
-rwxrwxrwx 1 username username   3116 Apr  6 18:13 docker-compose.yml*
-rwxrwxrwx 1 username username   2682 Apr  4 13:53 docker.mk*
drwxrwxrwx 1 username username   4096 Apr  6 16:35 drush/
-rwxrwxrwx 1 username username    321 Mar 31 20:02 load.environment.php*
-rwxrwxrwx 1 username username    481 Mar 31 20:02 phpunit.xml.dist*
drwxrwxrwx 1 username username   4096 Apr  6 16:35 scripts/
drwxrwxrwx 1 username username   4096 Apr  6 16:35 tests/
drwxrwxrwx 1 username username   4096 Apr  6 16:36 vendor/
drwxrwxrwx 1 username username   4096 Apr  6 16:36 web/
```

All containers are running, but the mounted volumes are missing in PHP and apache containers. And therefore I get a '404 Not Found'.

```
docker exec -ti -e COLUMNS=237 -e LINES=63 58292d350139 bash
wodby@php.container:/var/www/html $ ls
wodby@php.container:/var/www/html $
```

I should have all my Drupal files shared but it is empty. I have no idea what I did wrong.

**Output of `docker info`**
```
Client:
 Debug Mode: false

Server:
 Containers: 7
  Running: 7
  Paused: 0
  Stopped: 0
 Images: 7
 Server Version: 19.03.8
 Storage Driver: overlay2
  Backing Filesystem: <unknown>
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.76-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 1.92GiB
 Name: docker-desktop
 ID: U6EA:U44E:HAAA:6R4A:AO4F:OH3S:UO6K:JQQJ:BUYG:5BA2:2BBP:A4RA
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 91
  Goroutines: 96
  System Time: 2020-04-06T16:17:59.97518551Z
  EventsListeners: 4
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

**Contents of your `docker-compose.yml`**
```
version: "3"

# @see https://github.com/wodby/docker4drupal

services:
  mariadb:
    image: wodby/mariadb:$MARIADB_TAG
    container_name: "${PROJECT_NAME}_mariadb"
    stop_grace_period: 30s
    environment:
      MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
      MYSQL_DATABASE: $DB_NAME
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASSWORD
      MYSQL_MAX_ALLOWED_PACKET: 512M
      MYSQL_WAIT_TIMEOUT: 600
    #    volumes:
    #      - ./mariadb-init:/docker-entrypoint-initdb.d # Place init .sql file(s) here.
    #      - /path/to/mariadb/data/on/host:/var/lib/mysql # Use bind mount
    # Open MySQL port for IDE connection.
    ports:
      - 3306:3306

  php:
    image: wodby/drupal-php:$PHP_TAG
    container_name: "${PROJECT_NAME}_php"
    environment:
      # @see https://github.com/wodby/php#environment-variables
      PHP_MAX_INPUT_TIME: 120
      PHP_MAX_EXECUTION_TIME: 300
      PHP_MAX_INPUT_VARS: 5000
      PHP_DISPLAY_ERRORS: "On"
      PHP_MEMORY_LIMIT: 1024M
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
      DB_HOST: $DB_HOST
      DB_PORT: $DB_PORT
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
      DB_NAME: $DB_NAME
      DB_DRIVER: $DB_DRIVER
      PHP_FPM_USER: wodby
      PHP_FPM_GROUP: wodby
      COLUMNS: 80 # Set 80 columns for docker exec -it.
      ## Read instructions at https://wodby.com/docs/stacks/php/local/#xdebug
      PHP_XDEBUG: 1
      PHP_XDEBUG_IDEKEY: PHPSTORM
      PHP_XDEBUG_REMOTE_AUTOSTART: 0
      PHP_XDEBUG_REMOTE_CONNECT_BACK: 0
      PHP_XDEBUG_PROFILER_ENABLE_TRIGGER: 1
      PHP_XDEBUG_REMOTE_HOST: host.docker.internal
    volumes:
      - ./:/var/www/html

  mailhog:
    image: mailhog/mailhog
    container_name: "${PROJECT_NAME}_mailhog"
    labels:
      - "traefik.http.services.${PROJECT_NAME}_mailhog.loadbalancer.server.port=8025"
      - "traefik.http.routers.${PROJECT_NAME}_mailhog.rule=Host(`mailhog.${PROJECT_BASE_URL}`)"

  apache:
    image: wodby/apache:$APACHE_TAG
    container_name: "${PROJECT_NAME}_apache"
    depends_on:
      - php
    environment:
      APACHE_LOG_LEVEL: debug
      APACHE_BACKEND_HOST: php
      APACHE_VHOST_PRESET: php
      APACHE_DOCUMENT_ROOT: $APACHE_DOCUMENT_ROOT
      APACHE_FCGI_PROXY_TIMEOUT: 600
    volumes:
      - ./:/var/www/html
    labels:
      - "traefik.http.routers.${PROJECT_NAME}_apache.rule=Host(`${PROJECT_BASE_URL}`)"

  rsyslog:
    container_name: "${PROJECT_NAME}_rsyslog"
    image: wodby/rsyslog:$RSYSLOG_TAG

  portainer:
    image: portainer/portainer
    container_name: "${PROJECT_NAME}_portainer"
    command: --no-auth -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.http.routers.${PROJECT_NAME}_portainer.rule=Host(`portainer.${PROJECT_BASE_URL}`)"

  traefik:
    image: traefik:v2.0
    container_name: "${PROJECT_NAME}_traefik"
    command: --api.insecure=true --providers.docker
    ports:
      - '8000:80'
      - '8080:8080' # Dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  ## For Xdebug profiler
  files:

```

**Contents of your `.env`**
```
### Documentation available at https://wodby.com/docs/stacks/drupal/local
### Changelog can be found at https://github.com/wodby/docker4drupal/releases
### Images tags format explained at https://github.com/wodby/docker4drupal#images-tags

### PROJECT SETTINGS
PROJECT_NAME=drupaldev
PROJECT_BASE_URL=drupal.docker.localhost

### --- APACHE ----
# APACHE_TAG=2.4-4.2.4
APACHE_TAG=2.4-4.0.6
APACHE_DOCUMENT_ROOT=/var/www/html/web

### --- MARIADB ----
MARIADB_TAG=10.4-3.8.1
DB_NAME=drupal
DB_USER=drupal
DB_PASSWORD=drupal
DB_ROOT_PASSWORD=password
DB_HOST=mariadb
DB_PORT=3306
DB_DRIVER=mysql

### --- VANILLA DRUPAL ----
#DRUPAL_TAG=8-4.17.5
#DRUPAL_TAG=7-4.17.5

### --- PHP ----
# PHP_TAG=7.3-dev-4.15.2
PHP_TAG=7.3-dev-4.12.8

### OTHERS
RSYSLOG_TAG=latest

```

**Logs output `docker-compose logs`**
```
Attaching to drupaldev_apache, drupaldev_rsyslog, drupaldev_portainer, drupaldev_php, drupaldev_traefik, drupaldev_mariadb, drupaldev_mailhog
drupaldev_portainer | 2020/04/06 16:14:26 server: Reverse tunnelling enabled
drupaldev_portainer | 2020/04/06 16:14:26 server: Fingerprint b6:2a:03:96:63:b7:10:03:ad:1e:e4:60:6d:c5:c5:fb
drupaldev_portainer | 2020/04/06 16:14:26 server: Listening on 0.0.0.0:8000...
drupaldev_portainer | 2020/04/06 16:14:26 Starting Portainer 1.23.2 on :9000
drupaldev_portainer | 2020/04/06 16:14:26 [DEBUG] [chisel, monitoring] [check_interval_seconds: 10.000000] [message: starting tunnel management process]
drupaldev_apache | AH00112: Warning: DocumentRoot [/var/www/html/web] does not exist
drupaldev_apache | [Mon Apr 06 16:14:26.290594 2020] [ssl:info] [pid 1:tid 140069816093544] AH01887: Init: Initializing (virtual) servers for SSL
drupaldev_apache | [Mon Apr 06 16:14:26.290610 2020] [ssl:info] [pid 1:tid 140069816093544] AH01876: mod_ssl/2.4.39 compiled against Server: Apache/2.4.39, Library: OpenSSL/1.1.1b
drupaldev_apache | [Mon Apr 06 16:14:26.290621 2020] [http2:debug] [pid 1:tid 140069816093544] mod_http2.c(112): AH03089: initializing post config dry run
drupaldev_apache | AH00112: Warning: DocumentRoot [/var/www/html/web] does not exist
drupaldev_apache | [Mon Apr 06 16:14:26.292537 2020] [ssl:warn] [pid 1:tid 140069816093544] AH01873: Init: Session Cache is not configured [hint: SSLSessionCache]
drupaldev_apache | [Mon Apr 06 16:14:26.292546 2020] [ssl:info] [pid 1:tid 140069816093544] AH01887: Init: Initializing (virtual) servers for SSL
drupaldev_apache | [Mon Apr 06 16:14:26.292550 2020] [ssl:info] [pid 1:tid 140069816093544] AH01876: mod_ssl/2.4.39 compiled against Server: Apache/2.4.39, Library: OpenSSL/1.1.1b
WARNING: Connection pool is full, discarding connection: 0.0.0.0
drupaldev_apache | [Mon Apr 06 16:14:26.292560 2020] [http2:info] [pid 1:tid 140069816093544] AH03090: mod_http2 (v1.14.1, feats=CHPRIO+SHA256+INVHD+DWINS, nghttp2 1.35.1), initializing...
drupaldev_apache | [Mon Apr 06 16:14:26.292614 2020] [ldap:debug] [pid 1:tid 140069816093544] util_ldap.c(2988): AH01316: LDAP merging Shared Cache conf: shm=0x55a7121221b0 rmm=0x55a712122208 for VHOST: default
WARNING: Connection pool is full, discarding connection: 0.0.0.0
drupaldev_apache | [Mon Apr 06 16:14:26.292696 2020] [ldap:info] [pid 1:tid 140069816093544] AH01318: APR LDAP: Built with OpenLDAP LDAP SDK
WARNING: Connection pool is full, discarding connection: 0.0.0.0
drupaldev_apache | [Mon Apr 06 16:14:26.292704 2020] [ldap:info] [pid 1:tid 140069816093544] AH01319: LDAP: SSL support available
drupaldev_apache | [Mon Apr 06 16:14:26.293310 2020] [proxy_http2:info] [pid 1:tid 140069816093544] AH03349: mod_proxy_http2 (v1.14.1, nghttp2 1.35.1), initializing...
drupaldev_apache | [Mon Apr 06 16:14:26.294242 2020] [mpm_event:notice] [pid 1:tid 140069816093544] AH00489: Apache/2.4.39 (Unix) OpenSSL/1.1.1b configured -- resuming normal operations
drupaldev_apache | [Mon Apr 06 16:14:26.294252 2020] [mpm_event:info] [pid 1:tid 140069816093544] AH00490: Server built: Apr  2 2019 23:39:26
drupaldev_apache | [Mon Apr 06 16:14:26.294260 2020] [core:notice] [pid 1:tid 140069816093544] AH00094: Command line: 'httpd -D FOREGROUND'
drupaldev_apache | [Mon Apr 06 16:14:26.294262 2020] [core:debug] [pid 1:tid 140069816093544] log.c(1571): AH02639: Using SO_REUSEPORT: yes (1)
drupaldev_apache | [Mon Apr 06 16:14:26.295168 2020] [proxy:debug] [pid 21:tid 140069816093544] proxy_util.c(1934): AH00925: initializing worker proxy:reverse shared
drupaldev_apache | [Mon Apr 06 16:14:26.295306 2020] [proxy:debug] [pid 21:tid 140069816093544] proxy_util.c(1991): AH00927: initializing worker proxy:reverse local
drupaldev_apache | [Mon Apr 06 16:14:26.295315 2020] [proxy:debug] [pid 27:tid 140069816093544] proxy_util.c(1934): AH00925: initializing worker proxy:reverse shared
drupaldev_apache | [Mon Apr 06 16:14:26.295321 2020] [proxy:debug] [pid 27:tid 140069816093544] proxy_util.c(1991): AH00927: initializing worker proxy:reverse local
drupaldev_apache | [Mon Apr 06 16:14:26.295331 2020] [proxy:debug] [pid 27:tid 140069816093544] proxy_util.c(2026): AH00930: initialized pool in child 27 for (*) min=0 max=61 smax=61
drupaldev_apache | [Mon Apr 06 16:14:26.295336 2020] [proxy:debug] [pid 27:tid 140069816093544] proxy_util.c(1934): AH00925: initializing worker fcgi://php:9000/ shared
drupaldev_apache | [Mon Apr 06 16:14:26.295339 2020] [proxy:debug] [pid 27:tid 140069816093544] proxy_util.c(1991): AH00927: initializing worker fcgi://php:9000/ local
drupaldev_apache | [Mon Apr 06 16:14:26.295344 2020] [proxy:debug] [pid 27:tid 140069816093544] proxy_util.c(2026): AH00930: initialized pool in child 27 for (php) min=0 max=61 smax=61
drupaldev_apache | [Mon Apr 06 16:14:26.295465 2020] [proxy:debug] [pid 21:tid 140069816093544] proxy_util.c(2026): AH00930: initialized pool in child 21 for (*) min=0 max=61 smax=61
drupaldev_apache | [Mon Apr 06 16:14:26.295516 2020] [proxy:debug] [pid 21:tid 140069816093544] proxy_util.c(1934): AH00925: initializing worker fcgi://php:9000/ shared
drupaldev_apache | [Mon Apr 06 16:14:26.295573 2020] [proxy:debug] [pid 21:tid 140069816093544] proxy_util.c(1991): AH00927: initializing worker fcgi://php:9000/ local
drupaldev_apache | [Mon Apr 06 16:14:26.295736 2020] [proxy:debug] [pid 21:tid 140069816093544] proxy_util.c(2026): AH00930: initialized pool in child 21 for (php) min=0 max=61 smax=61
drupaldev_apache | [Mon Apr 06 16:14:26.296259 2020] [proxy:debug] [pid 22:tid 140069816093544] proxy_util.c(1934): AH00925: initializing worker proxy:reverse shared
drupaldev_apache | [Mon Apr 06 16:14:26.296287 2020] [proxy:debug] [pid 22:tid 140069816093544] proxy_util.c(1991): AH00927: initializing worker proxy:reverse local
drupaldev_apache | [Mon Apr 06 16:14:26.296303 2020] [proxy:debug] [pid 22:tid 140069816093544] proxy_util.c(2026): AH00930: initialized pool in child 22 for (*) min=0 max=61 smax=61
drupaldev_apache | [Mon Apr 06 16:14:26.296310 2020] [proxy:debug] [pid 22:tid 140069816093544] proxy_util.c(1934): AH00925: initializing worker fcgi://php:9000/ shared
drupaldev_apache | [Mon Apr 06 16:14:26.296315 2020] [proxy:debug] [pid 22:tid 140069816093544] proxy_util.c(1991): AH00927: initializing worker fcgi://php:9000/ local
drupaldev_apache | [Mon Apr 06 16:14:26.296325 2020] [proxy:debug] [pid 22:tid 140069816093544] proxy_util.c(2026): AH00930: initialized pool in child 22 for (php) min=0 max=61 smax=61
drupaldev_apache | [Mon Apr 06 16:14:26.296426 2020] [mpm_event:debug] [pid 27:tid 140069804243728] event.c(2314): AH02471: start_threads: Using epoll (wakeable)
drupaldev_apache | [Mon Apr 06 16:14:26.296858 2020] [mpm_event:debug] [pid 21:tid 140069804243728] event.c(2314): AH02471: start_threads: Using epoll (wakeable)
drupaldev_apache | [Mon Apr 06 16:14:26.297356 2020] [mpm_event:debug] [pid 22:tid 140069804243728] event.c(2314): AH02471: start_threads: Using epoll (wakeable)
drupaldev_mailhog | [HTTP] Binding to address: 0.0.0.0:8025
drupaldev_mailhog | 2020/04/06 16:14:24 Using in-memory storage
drupaldev_mailhog | 2020/04/06 16:14:24 [SMTP] Binding to address: 0.0.0.0:1025
drupaldev_mailhog | 2020/04/06 16:14:24 Serving under http://0.0.0.0:8025/
drupaldev_mailhog | Creating API v1 with WebPath:
drupaldev_mailhog | Creating API v2 with WebPath:
drupaldev_mailhog | [APIv1] KEEPALIVE /api/v1/events
drupaldev_mailhog | [APIv1] KEEPALIVE /api/v1/events
drupaldev_mailhog | [APIv1] KEEPALIVE /api/v1/events
drupaldev_mailhog | [APIv1] KEEPALIVE /api/v1/events
drupaldev_mailhog | [APIv1] KEEPALIVE /api/v1/events
drupaldev_traefik | time="2020-04-06T16:14:25Z" level=info msg="Configuration loaded from flags."
drupaldev_mariadb | Initializing database
drupaldev_mariadb |
drupaldev_mariadb |
drupaldev_mariadb | PLEASE REMEMBER TO SET A PASSWORD FOR THE MariaDB root USER !
drupaldev_mariadb | To do so, start the server, then issue the following commands:
drupaldev_mariadb |
drupaldev_mariadb | '/usr/bin/mysqladmin' -u root password 'new-password'
drupaldev_mariadb | '/usr/bin/mysqladmin' -u root -h  password 'new-password'
drupaldev_mariadb |
drupaldev_mariadb | Alternatively you can run:
drupaldev_mariadb | '/usr/bin/mysql_secure_installation'
drupaldev_mariadb |
drupaldev_mariadb | which will also give you the option of removing the test
drupaldev_mariadb | databases and anonymous user created by default.  This is
drupaldev_mariadb | strongly recommended for production servers.
drupaldev_mariadb |
drupaldev_mariadb | See the MariaDB Knowledgebase at http://mariadb.com/kb or the
drupaldev_mariadb | MySQL manual for more instructions.
drupaldev_mariadb |
drupaldev_mariadb | Please report any problems at http://mariadb.org/jira
drupaldev_mariadb |
drupaldev_mariadb | The latest information about MariaDB is available at http://mariadb.org/.
drupaldev_mariadb | You can find additional information about the MySQL part at:
drupaldev_mariadb | http://dev.mysql.com
drupaldev_mariadb | Consider joining MariaDB's strong and vibrant community:
drupaldev_mariadb | https://mariadb.org/get-involved/
drupaldev_mariadb |
drupaldev_mariadb | Database initialized
drupaldev_mariadb | MySQL init process in progress...
drupaldev_mariadb | 2020-04-06 16:14:28 0 [Note] mysqld (mysqld 10.4.12-MariaDB) starting as process 103 ...
drupaldev_mariadb | 2020-04-06 16:14:28 0 [Note] InnoDB: Using Linux native AIO
drupaldev_mariadb | 2020-04-06 16:14:28 0 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
drupaldev_mariadb | 2020-04-06 16:14:28 0 [Note] InnoDB: Uses event mutexes
drupaldev_mariadb | 2020-04-06 16:14:28 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
drupaldev_mariadb | 2020-04-06 16:14:28 0 [Note] InnoDB: Number of pools: 1
drupaldev_mariadb | 2020-04-06 16:14:28 0 [Note] InnoDB: Using SSE2 crc32 instructions
drupaldev_mariadb | 2020-04-06 16:14:28 0 [Note] mysqld: O_TMPFILE is not supported on /tmp (disabling future attempts)
drupaldev_mariadb | 2020-04-06 16:14:28 0 [Note] InnoDB: Initializing buffer pool, total size = 128M, instances = 1, chunk size = 128M
drupaldev_mariadb | 2020-04-06 16:14:28 0 [Note] InnoDB: Completed initialization of buffer pool
drupaldev_mariadb | 2020-04-06 16:14:28 0 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
drupaldev_mariadb | 2020-04-06 16:14:28 0 [Note] InnoDB: 128 out of 128 rollback segments are active.
drupaldev_mariadb | 2020-04-06 16:14:28 0 [Note] InnoDB: Creating shared tablespace for temporary tables
drupaldev_mariadb | 2020-04-06 16:14:28 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
drupaldev_mariadb | 2020-04-06 16:14:28 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
drupaldev_mariadb | 2020-04-06 16:14:28 0 [Note] InnoDB: Waiting for purge to start
drupaldev_mariadb | 2020-04-06 16:14:28 0 [Note] InnoDB: 10.4.12 started; log sequence number 60979; transaction id 21
drupaldev_mariadb | 2020-04-06 16:14:28 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
drupaldev_mariadb | 2020-04-06 16:14:28 0 [Note] Plugin 'FEEDBACK' is disabled.
drupaldev_mariadb | 2020-04-06 16:14:28 0 [Warning] 'user' entry 'root@db942f9a5fd1' ignored in --skip-name-resolve mode.
drupaldev_mariadb | 2020-04-06 16:14:28 0 [Warning] 'user' entry '@db942f9a5fd1' ignored in --skip-name-resolve mode.
drupaldev_mariadb | 2020-04-06 16:14:28 0 [Warning] 'proxies_priv' entry '@% root@db942f9a5fd1' ignored in --skip-name-resolve mode.
drupaldev_mariadb | 2020-04-06 16:14:28 0 [Note] InnoDB: Buffer pool(s) load completed at 200406 16:14:28
drupaldev_mariadb | 2020-04-06 16:14:28 0 [Note] Reading of all Master_info entries succeeded
drupaldev_mariadb | 2020-04-06 16:14:28 0 [Note] Added new Master_info '' to hash table
drupaldev_mariadb | 2020-04-06 16:14:28 0 [Note] mysqld: ready for connections.
drupaldev_mariadb | Version: '10.4.12-MariaDB'  socket: '/var/run/mysqld/mysqld.sock'  port: 0  MariaDB Server
drupaldev_mariadb | 2020-04-06 16:14:38 10 [Warning] 'proxies_priv' entry '@% root@db942f9a5fd1' ignored in --skip-name-resolve mode.
drupaldev_mariadb |
drupaldev_mariadb | 2020-04-06 16:14:38 0 [Note] mysqld (initiated by: unknown): Normal shutdown
drupaldev_mariadb | 2020-04-06 16:14:38 0 [Note] Event Scheduler: Purging the queue. 0 events
drupaldev_mariadb | 2020-04-06 16:14:38 0 [Note] InnoDB: FTS optimize thread exiting.
drupaldev_mariadb | 2020-04-06 16:14:38 0 [Note] InnoDB: Starting shutdown...
drupaldev_mariadb | 2020-04-06 16:14:38 0 [Note] InnoDB: Dumping buffer pool(s) to /var/lib/mysql/ib_buffer_pool
drupaldev_mariadb | 2020-04-06 16:14:38 0 [Note] InnoDB: Buffer pool(s) dump completed at 200406 16:14:38
drupaldev_mariadb | 2020-04-06 16:14:40 0 [Note] InnoDB: Shutdown completed; log sequence number 60988; transaction id 24
drupaldev_mariadb | 2020-04-06 16:14:40 0 [Note] InnoDB: Removed temporary tablespace data file: "ibtmp1"
drupaldev_mariadb | 2020-04-06 16:14:40 0 [Note] mysqld: Shutdown complete
drupaldev_mariadb |
drupaldev_mariadb |
drupaldev_mariadb | MySQL init process done. Ready for start up.
drupaldev_mariadb |
drupaldev_mariadb | 2020-04-06 16:14:40 0 [Note] mysqld (mysqld 10.4.12-MariaDB) starting as process 1 ...
drupaldev_mariadb | 2020-04-06 16:14:40 0 [Note] InnoDB: Using Linux native AIO
drupaldev_mariadb | 2020-04-06 16:14:40 0 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
drupaldev_mariadb | 2020-04-06 16:14:40 0 [Note] InnoDB: Uses event mutexes
drupaldev_mariadb | 2020-04-06 16:14:40 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
drupaldev_mariadb | 2020-04-06 16:14:40 0 [Note] InnoDB: Number of pools: 1
drupaldev_mariadb | 2020-04-06 16:14:40 0 [Note] InnoDB: Using SSE2 crc32 instructions
drupaldev_mariadb | 2020-04-06 16:14:40 0 [Note] mysqld: O_TMPFILE is not supported on /tmp (disabling future attempts)
drupaldev_mariadb | 2020-04-06 16:14:40 0 [Note] InnoDB: Initializing buffer pool, total size = 128M, instances = 1, chunk size = 128M
drupaldev_mariadb | 2020-04-06 16:14:40 0 [Note] InnoDB: Completed initialization of buffer pool
drupaldev_mariadb | 2020-04-06 16:14:40 0 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
drupaldev_mariadb | 2020-04-06 16:14:40 0 [Note] InnoDB: 128 out of 128 rollback segments are active.
drupaldev_mariadb | 2020-04-06 16:14:40 0 [Note] InnoDB: Creating shared tablespace for temporary tables
drupaldev_mariadb | 2020-04-06 16:14:40 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
drupaldev_mariadb | 2020-04-06 16:14:40 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
drupaldev_mariadb | 2020-04-06 16:14:40 0 [Note] InnoDB: 10.4.12 started; log sequence number 60988; transaction id 21
drupaldev_mariadb | 2020-04-06 16:14:40 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
drupaldev_mariadb | 2020-04-06 16:14:40 0 [Note] Plugin 'FEEDBACK' is disabled.
drupaldev_mariadb | 2020-04-06 16:14:40 0 [Note] Server socket created on IP: '0.0.0.0'.
drupaldev_mariadb | 2020-04-06 16:14:40 0 [Warning] 'proxies_priv' entry '@% root@db942f9a5fd1' ignored in --skip-name-resolve mode.
drupaldev_mariadb | 2020-04-06 16:14:40 0 [Note] InnoDB: Buffer pool(s) load completed at 200406 16:14:40
drupaldev_mariadb | 2020-04-06 16:14:40 0 [Note] Reading of all Master_info entries succeeded
drupaldev_mariadb | 2020-04-06 16:14:40 0 [Note] Added new Master_info '' to hash table
drupaldev_mariadb | 2020-04-06 16:14:40 0 [Note] mysqld: ready for connections.
drupaldev_mariadb | Version: '10.4.12-MariaDB'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MariaDB Server
drupaldev_php | [06-Apr-2020 16:14:25] NOTICE: fpm is running, pid 1
drupaldev_php | [06-Apr-2020 16:14:25] NOTICE: ready to handle connections
```
