### ISSUE TITLE
Cleanup the specific volumes for macOS in docker-compose.yml

### ISSUE THREAD

**Issue by devkinetic** [wodby/docker4drupal#433]
**Is your feature request related to a problem? Please describe.**
We have developers on macOS and Linux, I run into issues explaining how to swap volumes when on macOS, when performance is bad.

**Describe the solution you'd like**
Per https://docs.docker.com/docker-for-mac/osxfs/ documentation:
> The osxfs documentation has more details about the guarantees provided by consistent and cached. On Linux, where full consistency comes for free, cached behaves identically to consistent.

Therefore it is safe to place `:cached` on a mount for macOS and have it backwards compatible with Linux.

**Describe alternatives you've considered**
- A script that can be run that detects and handles OS version and swaps the yml, but then i have a diff in my repo i have to constantly ignore.
- Migrate macOS volumes to a docker-compose.override.yml... meh, it is still an extra step.

**Additional context**
Update the values to:

```yaml
php:
  volumes:
    - ./:/var/www/html:cached
nginx:
  volumes:
    - ./:/var/www/html:cached
apache:
  volumes:
    - ./:/var/www/html:cached
```
