### ISSUE TITLE
Unable to connect to ClamAV TCP/IP daemon

### ISSUE THREAD

**Issue by pifagor87** [wodby/docker4drupal#439]
***OS type***
Ubuntu 19

***Drupal version***
8

***Codebase***
Drupal 8

**Describe the bug**
Unable to connect to ClamAV TCP/IP daemon on 172.31.0.6:3310

**Contents of your `docker-compose.yml`**
```
  clamav:
    image: mkodockx/docker-clamav:alpine
    container_name: "${PROJECT_NAME}_clamav"
    expose:
      - "3310"
```
