### ISSUE TITLE
Varnish 503 error

### ISSUE THREAD

**Issue by Mykola-Veryha** [wodby/docker4drupal#447]
I have configured the varnish container:

```
  varnish:
    image: wodby/varnish:$VARNISH_TAG
    container_name: "${PROJECT_NAME}_varnish"
    depends_on:
      - nginx
    environment:
      VARNISH_SECRET: bd88ecbc-513c-494a-ab39-a8ca539de515
      VARNISH_BACKEND_HOST: nginx
      VARNISH_BACKEND_PORT: 8000
      VARNISH_CONFIG_PRESET: drupal
      VARNISH_ALLOW_UNRESTRICTED_PURGE: 1
    labels:
      - "traefik.http.services.${PROJECT_NAME}_varnish.loadbalancer.server.port=6081"
      - "traefik.http.routers.${PROJECT_NAME}_varnish.rule=Host(`varnish.${PROJECT_BASE_URL}`)"
 
  nginx:
    image: wodby/nginx:$NGINX_TAG
    container_name: "${PROJECT_NAME}_nginx"
    depends_on:
      - php
    environment:
      NGINX_STATIC_OPEN_FILE_CACHE: "off"
      NGINX_ERROR_LOG_LEVEL: debug
      NGINX_BACKEND_HOST: php
      NGINX_SERVER_ROOT: /var/www/html/docroot
      NGINX_VHOST_PRESET: $NGINX_VHOST_PRESET
    #      NGINX_DRUPAL_FILE_PROXY_URL: http://example.com
    volumes:
      - ./www:/var/www/html
    # For macOS users (https://wodby.com/docs/stacks/drupal/local#docker-for-mac)
    #      - ./:/var/www/html:cached # User-guided caching
    #      - docker-sync:/var/www/html # Docker-sync
    labels:
      - "traefik.http.routers.${PROJECT_NAME}_nginx.rule=Host(`${PROJECT_BASE_URL}`)"


  traefik:
    image: traefik:v2.0
    container_name: "${PROJECT_NAME}_traefik"
    command: --api.insecure=true --providers.docker
    ports:
      - '8000:80'
      - '25:25'
    #      - '8080:8080' # Dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

```
lexis.loc - my PROJECT_BASE_URL

And when I go to the http://varnish.lexis.loc:8000

I always get the 503 error.
```

Page Unavailable

The page you requested is temporarily unavailable.
```
 AS I know that means that Varnish can't reach the backend.

The project http://lexis.loc:8000 works well but I can't get the varnish to work.
