### ISSUE TITLE
Dockerize existing Drupal 8 Multisite

### ISSUE THREAD

**Issue by webmasterpf** [wodby/docker4drupal#448]
***Codebase***
mounted codebase D8.8.6

**Describe your issue**
Hello,

I try to put my LAMP D8 multisite install (with virtualhosts) into a dockerized stack via D4D.
My tree folder looklke this:
projetcfolder:
 - docker4drupal folder contain docker-compose and env files
 - racine folder: contains drupal core and other files and folders like sites, themes...
 - .git folder
 - .gitignore file

Change for PHP7.3 cause this error error: Warning: require(/var/www/html/vendor/autoload.php): failed to open stream: No such file or directory in /var/www/html/autoload.php on line 17

**Output of `docker info`**
```
Paste hereServer:
 Containers: 9
  Running: 8
  Paused: 0
  Stopped: 1
 Images: 8
 Server Version: 19.03.8
 Storage Driver: overlay2
```

**Contents of your `docker-compose.yml`**
```
  apache:
    image: wodby/apache:$APACHE_TAG
    container_name: "${PROJECT_NAME}_apache"
    depends_on:
    - php
    environment:
      APACHE_LOG_LEVEL: debug
      APACHE_BACKEND_HOST: php
      APACHE_VHOST_PRESET: php
      APACHE_DOCUMENT_ROOT: /var/www/html
    volumes:
    - ../racine:/var/www/html:cached
#    # Alternative for macOS users: docker-sync https://wodby.com/docs/stacks/drupal/local#docker-for-mac
#    - docker-sync:/var/www/html
    labels:
    - "traefik.http.routers.${PROJECT_NAME}_apache.rule=Host(`${PROJECT_BASE_URL}`)"


php:
    image: wodby/drupal-php:$PHP_TAG
    container_name: "${PROJECT_NAME}_php"
    environment:
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
    volumes:
    - ../racine:/var/www/html:cached
```

**Contents of your `.env`**
```
PROJECT_NAME=drupal8-multiste
PROJECT_BASE_URL=drupal.docker.localhost

MARIADB_TAG=10.4-3.8.5
```
Thanks for tips and help
