### ISSUE TITLE
php:cli was not found.

### ISSUE THREAD

**Issue by sam452** [wodby/docker4drupal#450]
### Codebase
mounted codebase
  
### Host OS 
macOS Catalina

### Docker info output
```
Client:
 Debug Mode: false

Server:
 Containers: 7
  Running: 7
  Paused: 0
  Stopped: 0
 Images: 21
 Server Version: 19.03.8
 Storage Driver: overlay2
  Backing Filesystem: <unknown>
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.76-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 1.945GiB
 Name: docker-desktop
 ID: ILZC:CS4B:LZ62:4VTT:JDIH:ZASQ:S4SK:JRQ4:TAEG:SPOR:6ZKS:DKI6
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 96
  Goroutines: 96
  System Time: 2020-06-30T22:27:49.2031929Z
  EventsListeners: 4
 HTTP Proxy: gateway.docker.internal:3128
 HTTPS Proxy: gateway.docker.internal:3129
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: true
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

### Docker compose file
Make sure you remove all commented services.
```yml
version: "3"

services:
  php:
    image: wodby/drupal-php:$PHP_TAG
    container_name: "${PROJECT_NAME}_php"
    environment:
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025   
      PHP_XDEBUG: 1
      PHP_XDEBUG_DEFAULT_ENABLE: 1
      PHP_XDEBUG_REMOTE_CONNECT_BACK: 0
      PHP_IDE_CONFIG: serverName=my-ide
      PHP_XDEBUG_IDEKEY: "my-ide"
      PHP_XDEBUG_REMOTE_HOST: host.docker.internal # Docker 18.03+ Mac/Win
    volumes:
    - ./:/var/www/html:cached

  crond:
    image: wodby/drupal-php:$PHP_TAG
    container_name: "${PROJECT_NAME}_crond"
    environment:
      CRONTAB: "0 * * * * drush -r /var/www/html/web cron"
    command: sudo -E LD_PRELOAD=/usr/lib/preloadable_libiconv.so crond -f -d 0
    volumes:
    - ./:/var/www/html:cached

  mailhog:
    image: mailhog/mailhog
    container_name: "${PROJECT_NAME}_mailhog"
    labels:
    - "traefik.http.services.${PROJECT_NAME}_mailhog.loadbalancer.server.port=8025"
    - "traefik.http.routers.${PROJECT_NAME}_mailhog.rule=Host(`mailhog.${PROJECT_BASE_URL}`)"

  apache:
    image: wodby/apache:$APACHE_TAG
    container_name: "${PROJECT_NAME}_apache"
    depends_on:
    - php
    environment:
      APACHE_LOG_LEVEL: debug
      APACHE_BACKEND_HOST: ${PROJECT_NAME}_php
      APACHE_VHOST_PRESET: php
      APACHE_DOCUMENT_ROOT: /var/www/html/web
    volumes:
    - ./:/var/www/html:cached
    labels:
    - "traefik.http.routers.${PROJECT_NAME}_apache.rule=Host(`${PROJECT_BASE_URL}`)"


  portainer:
    image: portainer/portainer
    container_name: "${PROJECT_NAME}_portainer"
    command: --no-auth -H unix:///var/run/docker.sock
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    labels:
    - "traefik.http.routers.${PROJECT_NAME}_portainer.rule=Host(`portainer.${PROJECT_BASE_URL}`)"

  traefik:
    image: traefik:v2.0
    container_name: "${PROJECT_NAME}_traefik"
    command: --api.insecure=true --providers.docker
    ports:
    - '8000:80'
    - '8080:8080' # Dashboard
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
```

### .env file
```
PROJECT_NAME=d8
PROJECT_BASE_URL=drupal.docker.localhost

DB_NAME=mydb
DB_USER=root
DB_PASSWORD=mypw
DB_ROOT_PASSWORD=mypw
DB_HOST=host.docker.internal
DB_PORT=3360
DB_DRIVER=mysql
MARIADB_TAG=10.4-3.8.5
DRUPAL_TAG=9-4.20.0
PHP_TAG=7.3-dev-macos-4.17.0
NGINX_VHOST_PRESET=drupal9
SOLR_CONFIG_SET="search_api_solr_4.0"
SOLR_TAG=8-4.6.1
ELASTICSEARCH_TAG=7-5.5.1
KIBANA_TAG=7-5.5.1
REDIS_TAG=6-3.4.1
NODE_TAG=12-dev-0.36.0
VARNISH_TAG=6.0-4.4.8
POSTGRES_TAG=12-1.10.0
ADMINER_TAG=4-3.10.0
APACHE_TAG=2.4-4.3.0
ATHENAPDF_TAG=2.10.0
DRUPAL_NODE_TAG=1.0-2.0.0
MEMCACHED_TAG=1-2.6.0
OPENSMTPD_TAG=6.0-1.7.0
RSYSLOG_TAG=latest
SELENIUM_CHROME_TAG=3.141
WEBGRIND_TAG=1-1.16.0
XHPROF_TAG=2.3.0
```

### Logs output: php log. Apache log unremarkable
```
dom8_php     | 172.29.0.7 -  30/Jun/2020:21:30:00 +0000 "GET /index.php" 404
dom8_php     | 172.29.0.7 -  30/Jun/2020:21:29:57 +0000 "POST /index.php" 200

```
I'm trying to get my local install of D8.9 running but find that the drush, and drupal, are not found.

`make drush php` returns
docker exec 6e4a8ce63a0d drush -r /Users/sam/apps/D8/web php
[30-Jun-2020 22:43:17 UTC] Xdebug could not open the remote debug file '/tmp/php-xdebug.log'.
                                                                               
  Command php:cli was not found. Pass --root or a @siteAlias in order to run Drupal-specific commands.    

`make drush --root php` returns the drush info output for a malformed command.
/Applications/Xcode.app/Contents/Developer/usr/bin/make: unrecognized option `--root

`docker exec d8_apache drush php`  returns
OCI runtime exec failed: exec failed: container_linux.go:349: starting container process caused "exec: \"drush\": executable file not found in $PATH": unknown

Similar output for the drupal console.

I've never gotten traefik running, so I pulled back to keeping it in my docker-compose.yml just so I can get my Drupal app running. Drush is critical for me and my searching returns no result for this type of error. Is this an Apache config or PHP config issue?
