### ISSUE TITLE
File permission issues in Ubuntu 20.04

### ISSUE THREAD

**Issue by kevinquillen** [wodby/docker4drupal#462]
Fresh install of Ubuntu 20.04, relevant docker-compose section:

```
  php:
    image: wodby/php:$PHP_TAG
    container_name: "${PROJECT_NAME}_php"
    environment:
      WODBY_USER_ID: 1001
      WODBY_GROUP_ID: 1001
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
      COLUMNS: 80 # Set 80 columns for docker exec -it.
    volumes:
      - ./:/var/www/html:cached
```

My host uid/gid are 1001:1001. Inside the container, wodby is 1000 (from /etc/passwd):

```
wodby@php.container:/var/www/html $ id
uid=1000(wodby) gid=1000(wodby) groups=82(www-data),1000(wodby)
```

When I run a docker-compose command, I receive various issues about unable to mkdir or read json files when using composer to install. One way around that is to amend all the docker-compose commands to have a --user=root passed, but this is not required to do on Mac or Windows within the same project.

Is there a way around this without having to [build each image with a different uid/gid](https://wodby.com/docs/1.0/stacks/php/local/#different-uidgid) (node etc)?
