### ISSUE TITLE
Xdebug 3 doesn't work with PHP 7.4

### ISSUE THREAD

**Issue by Mykola-Veryha** [wodby/docker4drupal#468]
***OS type***
Linux

***Drupal version***
8

***Codebase***
Mounted codebase

**Describe the bug**
XDebug doesn't work on 
image: wodby/drupal-php:7.4-dev-4.21.0
but works fine on
image: wodby/drupal-php:7.4-dev-4.17.0

**Output of `docker info`**
```
Client:
 Debug Mode: false

Server:
 Containers: 28
  Running: 11
  Paused: 0
  Stopped: 17
 Images: 1365
 Server Version: 19.03.13-ce
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 269548fa27e0089a8b8278fc4fc781d7f65a939b.m
 runc version: ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 init version: fec3683
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.9.11-3-MANJARO
 Operating System: Manjaro Linux
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 23.18GiB
 Name: veryha-vostro5581
 ID: GSIC:HWV4:5CNU:M7QM:E6WR:XB5L:ASLE:CZ4W:Z57L:MOEP:POIA:3JRX
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Username: veriga
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

```

**Contents of your `docker-compose.yml`**
```
  php:
    image: wodby/drupal-php:7.4-dev-4.21.0
    container_name: "${PROJECT_NAME}_php"
    environment:
      SIMPLETEST_BASE_URL: "http://nginx"
      SIMPLETEST_DB: "${DB_DRIVER}://${DB_USER}:${DB_PASSWORD}@${DB_HOST}/${DB_NAME}#tests_"
      MINK_DRIVER_ARGS_WEBDRIVER: '["chrome", {"browserName":"chrome","goog:chromeOptions":{"args":["--disable-gpu","--headless"]}}, "http://chrome:9515"]'
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
      DB_HOST: $DB_HOST
      DB_PORT: $DB_PORT
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
      DB_NAME: $DB_NAME
      DB_DRIVER: $DB_DRIVER
      PHP_FPM_USER: wodby
      PHP_FPM_GROUP: wodby
      COLUMNS: 80
      PHP_XDEBUG: 1
      PHP_XDEBUG_MODE: debug
      PHP_IDE_CONFIG: serverName=default
      PHP_XDEBUG_IDEKEY: "PHPSTORM"
      PHP_XDEBUG_REMOTE_HOST: 172.17.0.1 # Linux
    volumes:
      - ./www:/var/www/html
```
