### ISSUE TITLE
Elasticsearch?

### ISSUE THREAD

**Issue by Vacilando** [wodby/docker4drupal#48]
Any plans to introduce an Elasticsearch container? Like many, we are moving all sites over from Solr to Elasticsearch, so it would be good to have in dev environment as well.

**Comment by PavelPrischepa** [comment]
@Vacilando feel free to integrate the official Elasticsearch Docker image https://hub.docker.com/_/elasticsearch/

**Comment by alesrebec** [comment]
I made it work by just adding those lines in docker-compose.yml:

```
  elasticsearch:
    image: elasticsearch:2.4.1
    ports:
     - "9200:9200"
    command: elasticsearch -Des.node.name="Elasticsearch_Connector"
```
It's not the latest version. It's suggested to go with version 5.

You then need to have Elasticsearch Connector and Search API modules enabled.
Create a cluster and index in Elasticsearch configuration (I used the IP and port from elasticsearch container that was created, in my case http://172.21.0.6:9200) and connect this server in Search API config.

Result:

![screenshot from 2017-04-26 15-13-41](https://cloud.githubusercontent.com/assets/426177/25436473/a4775448-2a93-11e7-9838-29198ab10d31.png)

**Comment by csandanov** [comment]
If someone wants to test https://github.com/wodby/elasticsearch

**Comment by tanc** [comment]
I was having stability issues with the official version where the container would start off ok but start to error after a relatively short time. Has anyone else seen that? Does it need more resources (being a large Java app)?

**Comment by james-nesbitt** [comment]
@alesrebec Inlining also worked for me.  You might want to add the traefik labels instead of the host port mapping, and you should be able to use `es:9200` as an elasticsearch host, to avoid having to research the server IP.

```
  es:
    image: elasticsearch:alpine
    # elasticsearch:2.4.1
    # image: docker.elastic.co/elasticsearch/elasticsearch:5.4.0 <-- this image didn't work for me
    labels:
      - 'traefik.backend=elasticsearch'
      - 'traefik.port=9200'
      - 'traefik.frontend.rule=Host:es.drupal.docker.localhost'
```

**Comment by csandanov** [comment]
Most likely the problem is in `max_map_count`. Look up your logs.

 try adding the services as listed below to your compose file considering you need to access elasticsearch from the php container defined in the same compose file (same network). The image `wodby/elasticsearch` (based on docker.elastic.co/elasticsearch/elasticsearch) contains a fix for es volume permissions when mounted from a host machine. Kibana will search for `elasticsearch:9200` by default. Note, kibana takes quite some time to start.

```
services:
    elasticsearch:
        image: wodby/elasticsearch:5.4-1.0.0
        environment:
            ES_JAVA_OPTS: '-Xms1g -Xmx1g'
            CLUSTER_NAME: docker4drupal
            NODE_MASTER: 'true'
            NODE_DATA: 'true'
            HTTP_ENABLE: 'true'
            NODE_INGEST: 'true'
        sysctls:
            - vm.max_map_count=262144
        volumes:
            - '/path/to/my/esdata:/usr/share/elasticsearch/data'
    kibana:
        image: wodby/kibana:5.4-1.0.0
        labels:
          - 'traefik.backend=kibana'
          - 'traefik.port=5601'
          - 'traefik.frontend.rule=Host:kibana.drupal.docker.localhost'
```

**Comment by dakkusingh** [comment]
Here is how I am running mine. Drupal 8 Elastic Search Connector module only supports up Elastic Search version 5.6.

```
version: "2"
services:
  drupal:
    image: dakku/drupal-vm-extra:1
    volumes:
      - ./:/var/www/drupalvm/drupal:rw,delegated
      - /var/lib/mysql
    privileged: true
    command: /lib/systemd/systemd
    ports:
      - 80:80
      - 443:443
      - 3306:3306
      - 8025:8025
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.4
    environment:
      - cluster.name=drupal-local-elasticsearch
      - bootstrap.memory_lock=false
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    mem_limit: 1g
    ports:
      - 9200:9200
  kibana:
    image: docker.elastic.co/kibana/kibana:5.6.4
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch      

```
