### ISSUE TITLE
Drupal9  - elasticsearch_connector

### ISSUE THREAD

**Issue by marcelohack** [wodby/docker4drupal#490]
Hi guys,

I'm not being able to install elasticsearch_connector on Drupal 9 (9-4.33.2) using composer, it used to work fine with Drupal 8 (8-4.28.14).
```
wodby@php.container:/var/www/html $ composer require drupal/elasticsearch_connector
  [InvalidArgumentException]
  Could not find a version of package drupal/elasticsearch_connector matching your minimum-stability (stable). Require it with an explicit version constraint allowing its desired stability.
```

I've also tried using the command below:
```
composer require 'drupal/elasticsearch_connector:^7.0@alpha'
./composer.json has been updated
Running composer update drupal/elasticsearch_connector
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - drupal/elasticsearch_connector[7.0.0-alpha1, ..., 7.0.0-alpha3] require nodespark/des-connector 7.x-dev -> found nodespark/des-connector[7.x-dev] but it does not match your minimum-stability.
    - Root composer.json requires drupal/elasticsearch_connector ^7.0@alpha -> satisfiable by drupal/elasticsearch_connector[7.0.0-alpha1, 7.0.0-alpha2, 7.0.0-alpha3].
```

**Contents of your `docker-compose.yml`**
```
version: "3.7"

services:
  mariadb:
    image: wodby/mariadb:$MARIADB_TAG
    container_name: "${PROJECT_NAME}_mariadb"
    stop_grace_period: 30s
    environment:
      MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
      MYSQL_DATABASE: $DB_NAME
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASSWORD
    volumes:
      - ./data/mariadb:/var/lib/mysql # Use bind mount

  elasticsearch:
    image: wodby/elasticsearch:$ELASTICSEARCH_TAG
    container_name: "${PROJECT_NAME}_elasticsearch"
    environment:
      ES_JAVA_OPTS: "-Xms500m -Xmx500m"
    volumes:
      - ./data/elasticsearch:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - '9200:9200'
    labels:
      - "traefik.http.services.${PROJECT_NAME}_elasticsearch.loadbalancer.server.port=9200"
      - "traefik.http.routers.${PROJECT_NAME}_elasticsearch.rule=Host(`elasticsearch.${PROJECT_BASE_URL}`)"
            
  kibana:
    image: wodby/kibana:$KIBANA_TAG
    container_name: "${PROJECT_NAME}_kibana"
    depends_on:
    - elasticsearch
    labels:
    - "traefik.http.services.${PROJECT_NAME}_kibana.loadbalancer.server.port=5601"
    - "traefik.http.routers.${PROJECT_NAME}_kibana.rule=Host(`kibana.${PROJECT_BASE_URL}`)"

  php:
    image: wodby/drupal-php:$PHP_TAG
    container_name: "${PROJECT_NAME}_php"
    environment:
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
#      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S opensmtpd:25
#      DB_HOST: $DB_HOST
#      DB_PORT: $DB_PORT
#      DB_USER: $DB_USER
#      DB_PASSWORD: $DB_PASSWORD
#      DB_NAME: $DB_NAME
#      DB_DRIVER: $DB_DRIVER
#      PHP_FPM_USER: wodby
#      PHP_FPM_GROUP: wodby
#      COLUMNS: 80 # Set 80 columns for docker exec -it.
#      # Read instructions at https://wodby.com/docs/stacks/php/local/#xdebug
#      PHP_XDEBUG: 1
#      PHP_XDEBUG_MODE: debug
#      PHP_IDE_CONFIG: serverName=my-ide
#      PHP_XDEBUG_IDEKEY: "my-ide"
#      PHP_XDEBUG_CLIENT_HOST: 172.17.0.1 # Linux
#      PHP_XDEBUG_CLIENT_HOST: host.docker.internal # Docker 18.03+ Mac/Win
#      PHP_XDEBUG_CLIENT_HOST: 10.0.75.1 # Windows, Docker < 18.03
#      PHP_XDEBUG_LOG: /tmp/php-xdebug.log
#      # PHPUnit Drupal testing configurations
#      SIMPLETEST_BASE_URL: "http://nginx"
#      SIMPLETEST_DB: "${DB_DRIVER}://${DB_USER}:${DB_PASSWORD}@${DB_HOST}/${DB_NAME}#tests_"
#      MINK_DRIVER_ARGS_WEBDRIVER: '["chrome", {"browserName":"chrome","goog:chromeOptions":{"args":["--disable-gpu","--headless"]}}, "http://chrome:9515"]'
    volumes:
    - ./:/var/www/html:cached
## Alternative for macOS users: Mutagen https://wodby.com/docs/stacks/drupal/local#docker-for-mac
#    - mutagen:/var/www/html
## For XHProf and Xdebug profiler traces
#    - files:/mnt/files

  crond:
    image: wodby/drupal-php:$PHP_TAG
    container_name: "${PROJECT_NAME}_crond"
    environment:
      CRONTAB: "0 * * * * drush -r /var/www/html/web cron"
    command: sudo -E LD_PRELOAD=/usr/lib/preloadable_libiconv.so crond -f -d 0
    volumes:
    - ./:/var/www/html:cached

  nginx:
    image: wodby/nginx:$NGINX_TAG
    container_name: "${PROJECT_NAME}_nginx"
    depends_on:
    - php
    environment:
      NGINX_STATIC_OPEN_FILE_CACHE: "off"
      NGINX_ERROR_LOG_LEVEL: debug
      NGINX_BACKEND_HOST: php
      NGINX_SERVER_ROOT: /var/www/html/web
      NGINX_VHOST_PRESET: $NGINX_VHOST_PRESET
    #      NGINX_DRUPAL_FILE_PROXY_URL: http://example.com
    volumes:
    - ./:/var/www/html:cached
## Alternative for macOS users: Mutagen https://wodby.com/docs/stacks/drupal/local#docker-for-mac
#    - mutagen:/var/www/html

    labels:
    - "traefik.http.routers.${PROJECT_NAME}_nginx.rule=Host(`${PROJECT_BASE_URL}`)"

  mailhog:
    image: mailhog/mailhog
    container_name: "${PROJECT_NAME}_mailhog"
    labels:
    - "traefik.http.services.${PROJECT_NAME}_mailhog.loadbalancer.server.port=8025"
    - "traefik.http.routers.${PROJECT_NAME}_mailhog.rule=Host(`mailhog.${PROJECT_BASE_URL}`)"


  traefik:
    image: traefik:v2.0
    container_name: "${PROJECT_NAME}_traefik"
    command: --api.insecure=true --providers.docker
    ports:
    - '8000:80'
#    - '8080:8080' # Dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
```

**Contents of your `.env`**
```
PROJECT_NAME=my_drupal9_project
PROJECT_BASE_URL=drupal.docker.localhost

DB_NAME=drupal
DB_USER=drupal
DB_PASSWORD=drupal
DB_ROOT_PASSWORD=password
DB_HOST=mariadb
DB_PORT=3306
DB_DRIVER=mysql

### --- MARIADB ----

MARIADB_TAG=10.5-3.13.2
#MARIADB_TAG=10.4-3.13.2
#MARIADB_TAG=10.3-3.13.2
#MARIADB_TAG=10.2-3.13.2

### --- VANILLA DRUPAL ----

DRUPAL_TAG=9-4.33.2
#DRUPAL_TAG=8-4.33.2
#DRUPAL_TAG=7-4.33.2

### --- PHP ----

# Linux (uid 1000 gid 1000)

PHP_TAG=7.4-dev-4.27.0
#PHP_TAG=8.0-dev-4.27.0
#PHP_TAG=7.3-dev-4.27.0

# macOS (uid 501 gid 20)

#PHP_TAG=8.0-dev-macos-4.27.0
#PHP_TAG=7.4-dev-macos-4.27.0
#PHP_TAG=7.3-dev-macos-4.27.0

### --- NGINX ----

NGINX_TAG=1.20-5.15.0
#NGINX_TAG=1.19-5.15.0

NGINX_VHOST_PRESET=drupal9
#NGINX_VHOST_PRESET=drupal8
#NGINX_VHOST_PRESET=drupal7

### --- SOLR ---

SOLR_CONFIG_SET="search_api_solr_4.1.6"
#SOLR_CONFIG_SET="search_api_solr_4.0.1"
#SOLR_CONFIG_SET="search_api_solr_8.x-3.9"
#SOLR_CONFIG_SET="search_api_solr_8.x-3.2"
#SOLR_CONFIG_SET="search_api_solr_8.x-2.7"
#SOLR_CONFIG_SET="search_api_solr_8.x-1.2"
#SOLR_CONFIG_SET="search_api_solr_7.x-1.14"

SOLR_TAG=8-4.11.1
#SOLR_TAG=7-4.11.1
#SOLR_TAG=6-4.11.1
#SOLR_TAG=5-4.11.1

### --- ELASTICSEARCH ---

ELASTICSEARCH_TAG=7-5.11.4
#ELASTICSEARCH_TAG=6-5.11.4

### --- KIBANA ---

KIBANA_TAG=7-5.11.4
#KIBANA_TAG=6-5.11.4

### --- REDIS ---

REDIS_TAG=6-3.9.2
#REDIS_TAG=5-3.9.2

### --- NODE ---

NODE_TAG=14-dev-0.58.0
#NODE_TAG=12-dev-0.58.0
#NODE_TAG=10-dev-0.58.0

### --- VARNISH ---

VARNISH_TAG=6.0-4.7.2
#VARNISH_TAG=4.1-4.7.2

### --- POSTGRESQL ----

POSTGRES_TAG=13-1.23.0
#POSTGRES_TAG=12-1.23.0
#POSTGRES_TAG=11-1.23.0
#POSTGRES_TAG=10-1.23.0
#POSTGRES_TAG=9.6-1.23.0

### OTHERS

ADMINER_TAG=4-3.15.1
APACHE_TAG=2.4-4.6.0
ATHENAPDF_TAG=2.16.0
DRUPAL_NODE_TAG=1.0-2.0.0
MEMCACHED_TAG=1-2.9.1
OPENSMTPD_TAG=6.0-1.10.0
RSYSLOG_TAG=latest
SELENIUM_CHROME_TAG=3.141
WEBGRIND_TAG=1-1.21.1
XHPROF_TAG=3.0.3
```
