### ISSUE TITLE
Apache Solr doesn't work with Apple M1 Chip (ARM64) 

### ISSUE THREAD

**Issue by seoplague** [wodby/docker4drupal#494]
***OS type***
macOS

***Drupal version***
9

***Codebase***
Built-in vanilla Drupal or mounted codebase

**Describe the bug**
Apache Solr doesn't work with Apple M1 Chip (ARM64) 

**Output of `docker info`**
```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Build with BuildKit (Docker Inc., v0.6.1-docker)
  compose: Docker Compose (Docker Inc., v2.0.0-rc.2)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
 Containers: 139
  Running: 11
  Paused: 0
  Stopped: 128
 Images: 72
 Server Version: 20.10.8
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: e25210fe30a0a703442421b0f60afac609f950a3
 runc version: v1.0.1-0-g4144b63
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.47-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: aarch64
 CPUs: 4
 Total Memory: 5.8GiB
 Name: docker-desktop
 ID: YUQY:66UB:UVOI:ZEJD:TAKY:2IC4:EVGM:6P3K:IOV2:SUSU:WFVB:UABA
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: true
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Contents of your `docker-compose.yml`**
```
solr:
    image: wodby/solr:$SOLR_TAG
    container_name: "${PROJECT_NAME}_solr"
    environment:
      SOLR_DEFAULT_CONFIG_SET: $SOLR_CONFIG_SET
      SOLR_HEAP: 1024m
    labels:
    - "traefik.http.services.${PROJECT_NAME}_solr.loadbalancer.server.port=8983"
    - "traefik.http.routers.${PROJECT_NAME}_solr.rule=Host(`solr.${PROJECT_BASE_URL}`)"
```

**Contents of your `.env`**
```
### --- SOLR ---
SOLR_CONFIG_SET="search_api_solr_4.1.6"

SOLR_TAG=8-4.11.1
```

**Logs output `docker-compose logs`**
```
Starting Solr 
solr_1       | neither jattach nor jstack in /opt/java/openjdk could be found, so no thread dumps are possible. Continuing.
solr_1       | OpenJDK 64-Bit Server VM warning: Failed to reserve shared memory. (error = 1)
solr_1       | OpenJDK 64-Bit Server VM warning: Failed to reserve shared memory. (error = 1)
solr_1       | OpenJDK 64-Bit Server VM warning: Failed to reserve shared memory. (error = 1)
solr_1       | OpenJDK 64-Bit Server VM warning: Failed to reserve shared memory. (error = 1)
solr_1       | OpenJDK 64-Bit Server VM warning: Failed to reserve shared memory. (error = 1)
solr_1       | OpenJDK 64-Bit Server VM warning: Failed to reserve shared memory. (error = 1)
solr_1       | qemu: uncaught target signal 11 (Segmentation fault) - core dumped
```
