### ISSUE TITLE
M1 support for Elasticsearch container.

### ISSUE THREAD

**Issue by uttkarsh-26** [wodby/docker4drupal#496]
***Codebase***
D9

**Describe your issue**
ElasticSearch container does not come up on M1 macs

**Output of `docker info`**
```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Build with BuildKit (Docker Inc., v0.6.1-docker)
  compose: Docker Compose (Docker Inc., v2.0.0-rc.3)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
 Containers: 7
  Running: 5
  Paused: 0
  Stopped: 2
 Images: 13
 Server Version: 20.10.8
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: e25210fe30a0a703442421b0f60afac609f950a3
 runc version: v1.0.1-0-g4144b63
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.47-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: aarch64
 CPUs: 4
 Total Memory: 3.841GiB
 Name: docker-desktop
 ID: RAXD:C7KS:WGYX:DFFO:CFQJ:UXIR:FCHE:FDYC:EGSD:CE6B:YFNI:LGJK
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Contents of your `docker-compose.yml`**
```
 elasticsearch:
    image: wodby/elasticsearch:7-5.13.10
    container_name: "${PROJECT_NAME}_elasticsearch"
    environment:
      ES_JAVA_OPTS: "-Xms500m -Xmx500m"
    ports:
      - "9200:9200"
    labels:
      - 'traefik.backend=${PROJECT_NAME}_elasticsearch'
      - 'traefik.port=9200'
      - 'traefik.frontend.rule=Host:elastic.php.docker.localhost'
    ulimits:
      memlock:
        soft: -1
        hard: -1
```

**Logs output `docker-compose logs`**
```
goroutine 1 [running]:
runtime.systemstack_switch()
	/home/travis/.gimme/versions/go1.6.linux.amd64/src/runtime/asm_amd64.s:245 fp=0xc820022770 sp=0xc820022768
runtime.main()
	/home/travis/.gimme/versions/go1.6.linux.amd64/src/runtime/proc.go:126 +0x62 fp=0xc8200227c0 sp=0xc820022770
runtime.goexit()
	/home/travis/.gimme/versions/go1.6.linux.amd64/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc8200227c8 sp=0xc8200227c0
runtime: failed to create new OS thread (have 2 already; errno=22)
fatal error: newosproc

runtime stack:
runtime.throw(0x6249a0, 0x9)
	/home/travis/.gimme/versions/go1.6.linux.amd64/src/runtime/panic.go:530 +0x90
runtime.newosproc(0xc820028000, 0xc820037fc0)
	/home/travis/.gimme/versions/go1.6.linux.amd64/src/runtime/os1_linux.go:149 +0x18c
runtime.newm(0x676240, 0x0)
	/home/travis/.gimme/versions/go1.6.linux.amd64/src/runtime/proc.go:1513 +0x135
runtime.main.func1()
	/home/travis/.gimme/versions/go1.6.linux.amd64/src/runtime/proc.go:125 +0x2c
runtime.systemstack(0x732c00)
	/home/travis/.gimme/versions/go1.6.linux.amd64/src/runtime/asm_amd64.s:291 +0x79
runtime.mstart()
	/home/travis/.gimme/versions/go1.6.linux.amd64/src/runtime/proc.go:1048

goroutine 1 [running]:
runtime.systemstack_switch()
	/home/travis/.gimme/versions/go1.6.linux.amd64/src/runtime/asm_amd64.s:245 fp=0xc820022770 sp=0xc820022768
runtime.main()
	/home/travis/.gimme/versions/go1.6.linux.amd64/src/runtime/proc.go:126 +0x62 fp=0xc8200227c0 sp=0xc820022770
runtime.goexit()
	/home/travis/.gimme/versions/go1.6.linux.amd64/src/runtime/asm_amd64.s:1998 +0x1 fp=0xc8200227c8 sp=0xc8200227c0
```
