### ISSUE TITLE
Node.js container is not in the list of containers

### ISSUE THREAD

**Issue by antongordon25** [wodby/docker4drupal#498]
Issue:
When I write a command `docker-compose up -d` I see : `Starting bcnews_node    ... done`
But when I write a command `docker ps` I don't see node.js in the container list.
How to fix it?

Maybe I write incorrectly something in the node.js service configurations(called a **node** in the docker-compose.yml file) in three lines `working_dir`, `volumes`, `command`?

### Host OS 
Ubuntu 20.04

### Docker info output
```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.6.3-docker)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
 Containers: 17
  Running: 8
  Paused: 0
  Stopped: 9
 Images: 8
 Server Version: 20.10.9
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runtime.v1.linux runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 5b46e404f6b9f661a205e28d59c982d3634148f8
 runc version: v1.0.2-0-g52b36a2
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.11.0-38-generic
 Operating System: Ubuntu 20.04.3 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 5.705GiB
 Name: Asus
 ID: TT5U:LEG6:OP44:5DLB:MCTG:VBAH:DXRQ:F7RZ:DTMI:WK52:TMZN:ECYB
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

### Docker compose file

```
version: "3.7"

services:
  mariadb:
    image: wodby/mariadb:$MARIADB_TAG
    container_name: "${PROJECT_NAME}_mariadb"
    stop_grace_period: 30s
    environment:
      MYSQL_ROOT_PASSWORD: $DB_ROOT_PASSWORD
      MYSQL_DATABASE: $DB_NAME
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASSWORD
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - ./db/source:/var/lib/mysql

  php:
    image: wodby/drupal-php:$PHP_TAG
    container_name: "${PROJECT_NAME}_php"
    environment:
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
      DB_HOST: $DB_HOST
      DB_PORT: $DB_PORT
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
      DB_NAME: $DB_NAME
      DB_DRIVER: $DB_DRIVER
    volumes:
    - ./:/var/www/html:cached

  crond:
    image: wodby/drupal-php:$PHP_TAG
    container_name: "${PROJECT_NAME}_crond"
    environment:
      CRONTAB: "0 * * * * drush -r /var/www/html/web cron"
    command: sudo -E LD_PRELOAD=/usr/lib/preloadable_libiconv.so crond -f -d 0
    volumes:
    - ./:/var/www/html:cached

  nginx:
    image: wodby/nginx:$NGINX_TAG
    container_name: "${PROJECT_NAME}_nginx"
    depends_on:
    - php
    environment:
      NGINX_STATIC_OPEN_FILE_CACHE: "off"
      NGINX_ERROR_LOG_LEVEL: debug
      NGINX_BACKEND_HOST: php
      NGINX_SERVER_ROOT: /var/www/html/web
      NGINX_VHOST_PRESET: $NGINX_VHOST_PRESET
    volumes:
    - ./:/var/www/html:cached

    labels:
    - "traefik.http.routers.${PROJECT_NAME}_nginx.rule=Host(`${PROJECT_BASE_URL}`)"

  mailhog:
    image: mailhog/mailhog
    container_name: "${PROJECT_NAME}_mailhog"
    labels:
    - "traefik.http.services.${PROJECT_NAME}_mailhog.loadbalancer.server.port=8025"
    - "traefik.http.routers.${PROJECT_NAME}_mailhog.rule=Host(`mailhog.${PROJECT_BASE_URL}`)"

  adminer:
    container_name: "${PROJECT_NAME}_adminer"
    image: wodby/adminer:$ADMINER_TAG
    environment:
      ADMINER_DEFAULT_DB_HOST: $DB_HOST
      ADMINER_DEFAULT_DB_NAME: $DB_NAME
    labels:
    - "traefik.http.routers.${PROJECT_NAME}_adminer.rule=Host(`adminer.${PROJECT_BASE_URL}`)"

  pma:
    image: phpmyadmin/phpmyadmin
    container_name: "${PROJECT_NAME}_pma"
    environment:
      PMA_HOST: $DB_HOST
      PMA_USER: $DB_USER
      PMA_PASSWORD: $DB_PASSWORD
      UPLOAD_LIMIT: 1G
    labels:
    - "traefik.http.routers.${PROJECT_NAME}_pma.rule=Host(`pma.${PROJECT_BASE_URL}`)"

  node:
    image: wodby/node:$NODE_TAG
    container_name: "${PROJECT_NAME}_node"
    working_dir: /var/www/html/web/themes/custom/bootstrap_sass_bcnews
    labels:
    - "traefik.http.services.${PROJECT_NAME}_node.loadbalancer.server.port=3000"
    - "traefik.http.routers.${PROJECT_NAME}_node.rule=Host(`node.${PROJECT_BASE_URL}`)"
    expose:
    - "3000"
    volumes:
    - ./var/www/html/web/themes/custom/bootstrap_sass_bcnews:/var/www/html
    command: sh -c 'apt-get install python3-software-properties gnupg2 curl wget -y && curl -fsSL https://deb.nodesource.com/setup_12.x | sudo -E bash - && sudo apt-get install -y nodejs && cd /var/www/html/web/themes/custom/bootstrap_sass_bcnews && npm install --global gulp-cli && npm install'

  traefik:
    image: traefik:v2.0
    container_name: "${PROJECT_NAME}_traefik"
    command: --api.insecure=true --providers.docker
    ports:
    - '8000:80'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
```

### .env file
```
### Documentation available at https://wodby.com/docs/stacks/drupal/local
### Changelog can be found at https://github.com/wodby/docker4drupal/releases
### Images tags format explained at https://github.com/wodby/docker4drupal#images-tags

### PROJECT SETTINGS

PROJECT_NAME=bcnews
PROJECT_BASE_URL=bcnews.localhost

DB_NAME=somename
DB_USER=somename
DB_PASSWORD=somepassword
DB_ROOT_PASSWORD=somepassword
DB_HOST=mariadb
DB_PORT=3306
DB_DRIVER=mysql

### --- MARIADB ----

MARIADB_TAG=10.5-3.13.20
#MARIADB_TAG=10.4-3.13.20
#MARIADB_TAG=10.3-3.13.20
#MARIADB_TAG=10.2-3.13.20

### --- VANILLA DRUPAL ----

DRUPAL_TAG=9-4.35.0
#DRUPAL_TAG=8-4.35.0
#DRUPAL_TAG=7-4.35.0

### --- PHP ----

# Linux (uid 1000 gid 1000)

PHP_TAG=7.4-dev-4.28.0
#PHP_TAG=8.0-dev-4.28.0
#PHP_TAG=7.3-dev-4.28.0

# macOS (uid 501 gid 20)

#PHP_TAG=8.0-dev-macos-4.28.0
#PHP_TAG=7.4-dev-macos-4.28.0
#PHP_TAG=7.3-dev-macos-4.28.0

### --- NGINX ----

NGINX_TAG=1.21-5.16.0
#NGINX_TAG=1.20-5.16.0
#NGINX_TAG=1.19-5.16.0

NGINX_VHOST_PRESET=drupal9
#NGINX_VHOST_PRESET=drupal8
#NGINX_VHOST_PRESET=drupal7

### --- SOLR ---

SOLR_CONFIG_SET="search_api_solr_4.1.6"
#SOLR_CONFIG_SET="search_api_solr_4.0.1"
#SOLR_CONFIG_SET="search_api_solr_8.x-3.9"
#SOLR_CONFIG_SET="search_api_solr_8.x-3.2"
#SOLR_CONFIG_SET="search_api_solr_8.x-2.7"
#SOLR_CONFIG_SET="search_api_solr_8.x-1.2"
#SOLR_CONFIG_SET="search_api_solr_7.x-1.14"

SOLR_TAG=8-4.12.1
#SOLR_TAG=7-4.12.1
#SOLR_TAG=6-4.12.1
#SOLR_TAG=5-4.12.1

### --- ELASTICSEARCH ---

ELASTICSEARCH_TAG=7-5.13.10
#ELASTICSEARCH_TAG=6-5.13.10

### --- KIBANA ---

KIBANA_TAG=7-5.13.10
#KIBANA_TAG=6-5.13.10

### --- REDIS ---

REDIS_TAG=6-3.9.4
#REDIS_TAG=5-3.9.4

### --- NODE ---

#NODE_TAG=16-dev-0.84.0
#NODE_TAG=14-dev-0.84.0
NODE_TAG=12-dev-0.84.0

### --- VARNISH ---

VARNISH_TAG=6.0-4.7.5
#VARNISH_TAG=4.1-4.7.5

### --- POSTGRESQL ----

POSTGRES_TAG=13-1.23.2
#POSTGRES_TAG=12-1.23.2
#POSTGRES_TAG=11-1.23.2
#POSTGRES_TAG=10-1.23.2
#POSTGRES_TAG=9.6-1.23.2

### OTHERS

ADMINER_TAG=4-3.15.1
APACHE_TAG=2.4-4.6.1
ATHENAPDF_TAG=2.16.0
DRUPAL_NODE_TAG=1.0-2.0.0
MEMCACHED_TAG=1-2.9.3
OPENSMTPD_TAG=6.0-1.10.3
RSYSLOG_TAG=latest
SELENIUM_CHROME_TAG=3.141
WEBGRIND_TAG=1-1.22.0
XHPROF_TAG=3.0.5
```

### Logs output
```
Attaching to bcnews_node
bcnews_node | sh: apt-get: not found
bcnews_node | sh: apt-get: not found
```

**Comment by antongordon25** [comment]
> maybe the command you specified for node service just completed and that's all, you can look up its startup logs by running `docker-compose up` without `-d` param

**Comment by antongordon25** [comment]
Solution:
1. Node.js image uses `apk` instead of `apt-get `to install additional packages.
2. This image already containing node.js. I don't need to write a node.js installation command in `command:` line.
Here's how the node service configuration should look like:

`
  node:
    image: wodby/node:$NODE_TAG
    container_name: "${PROJECT_NAME}_node"
    working_dir: /var/www/html/web/themes/custom/bcnews_bootstrap_sass
    labels:
    - "traefik.http.services.${PROJECT_NAME}_node.loadbalancer.server.port=3000"
    - "traefik.http.routers.${PROJECT_NAME}_node.rule=Host(`node.${PROJECT_BASE_URL}`)"
    expose:
    - "3000"
    volumes:
    - ./:/var/www/html:cached
    command: sh -c 'cd /var/www/html/web/themes/custom/bcnews_bootstrap_sass && npm init --yes && npm install --global gulp-cli && npm install --save-dev gulp && npm install && gulp'
`

**Comment by antongordon25** [comment]
> maybe the command you specified for node service just completed and that's all, you can look up its startup logs by running `docker-compose up` without `-d` param

Solution:
1. Node.js image uses `apk` instead of `apt-get `to install additional packages.
2. This image already containing node.js. I don't need to write a node.js installation command in `command:` line.
Here's how the node service configuration should look like:

```
  node:
    image: wodby/node:$NODE_TAG
    container_name: "${PROJECT_NAME}_node"
    working_dir: /var/www/html/web/themes/custom/bcnews_bootstrap_sass
    labels:
    - "traefik.http.services.${PROJECT_NAME}_node.loadbalancer.server.port=3000"
    - "traefik.http.routers.${PROJECT_NAME}_node.rule=Host(`node.${PROJECT_BASE_URL}`)"
    expose:
    - "3000"
    volumes:
    - ./:/var/www/html:cached
    command: sh -c 'cd /var/www/html/web/themes/custom/bcnews_bootstrap_sass && npm init --yes && npm install --global gulp-cli && npm install --save-dev gulp && npm install && gulp'
```
