### ISSUE TITLE
[Profiler] ERR: File '/mnt/files/xdebug/cachegrind.out.xxx' could not be opened.

### ISSUE THREAD

**Issue by superromeo** [wodby/docker4drupal#500]
***Codebase***
Built-in vanilla Drupal

**Describe your issue**
I try to launch xdebug profiler.
And in `/tmp/php-xdebug.log` I have:

> [133] Log opened at 2021-11-16 10:11:19.329862
> [133] [Profiler] ERR: File '/mnt/files/xdebug/cachegrind.out.133' could not be opened.
> [133] [Profiler] WARN: The path '/mnt/files/xdebug' has the permissions: 0755.
> [133] Log closed at 2021-11-16 10:11:19.673099

`wodby@php.container:/var/www/html $ ls -la /mnt/files`
> drwxrwxr-x    2 www-data www-data      4096 Nov 15 14:46 private
> drwxrwxr-x    2 www-data www-data      4096 Nov 15 14:46 public
> drwxrwxr-x    2 www-data www-data      4096 Nov 15 14:46 sessions
> drwxr-xr-x    4 root     root          4096 Nov 15 14:46 xdebug

But I can't change permissions:
> wodby@php.container:/var/www/html $ sudo chmod 777 /mnt/files/xdebug
> [sudo] password for wodby:

What should I do?
Thank you!

**Comment by csandanov** [comment]
What's your php image tag? Normally it should pre-create `/mnt/files/xdebug/profiler` and `/mnt/files/xdebug/traces` owned by `www-data`

**Comment by superromeo** [comment]
`image: wodby/drupal-php:$PHP_TAG`
PHP_TAG=8.0-dev-4.27.3

**Comment by superromeo** [comment]
Now I updated files to last version - `/mnt/files/xdebug` still owned by `root`.

**Comment by superromeo** [comment]
Oh, but `/mnt/files/xdebug/profiler` and `/mnt/files/xdebug/traces` owned by www-data.
You are right.

But on profiling I have `502 Bad Gateway`

In nginx log:
> 2021/11/17 10:40:35 [error] 46#46: *1 recv() failed (104: Connection reset by peer) while reading response header from upstream, client: 172.18.0.9, server: default, request: "GET /admin/config/system/cron/jobs HTTP/1.1", upstream: "fastcgi://172.18.0.7:9000", host: "ru.lom.localhost", referrer: "http://ru.lom.localhost/admin/config/system/cron/jobs"

In php log:
> [17-Nov-2021 10:40:35] WARNING: [pool www] child 125 exited on signal 11 (SIGSEGV) after 1.045025 seconds from start
> [17-Nov-2021 10:40:35] NOTICE: [pool www] child 127 started

 and in '/tmp/php-xdebug.log' I have:
> [125] Log opened at 2021-11-17 10:40:35.029428
> [125] [Config] INFO: Trigger value for 'XDEBUG_TRIGGER' not found, falling back to 'XDEBUG_PROFILE'

without 
> [125] Log closed ...

**Comment by csandanov** [comment]
try adding env var `XDEBUG_CONFIG: "output_dir=/mnt/files/xdebug/profiler"`

**Comment by csandanov** [comment]
xdebug had a major upgrade recently and some of its configuration changed and we should now just create root dir `/mnt/files/xdebug`

**Comment by csandanov** [comment]
Updates for php/drupal images have been released, `/mnt/files/xdebug` is now owned by `www-data`, see latest tags in the master branch

**Comment by superromeo** [comment]
Thank you very much!
All works now.

2. cachegrind.out.xxx files are out in `\xdebug` folder. Not in `\xdebug\profiler\` folder...

**Comment by superromeo** [comment]
3. Always creates only two files with names `cachegrind.out.126.gz` and `cachegrind.out.127.gz`. And new ones replaced old ones. No matter which url has been profiled.

**Comment by batkor** [comment]
My docker-compose.override.yml file

```
  php:
    environment:
      PHP_XDEBUG: 1
      PHP_XDEBUG_MODE: profile,debug
      PHP_XDEBUG_LOG_LEVEL: 0
      PHP_IDE_CONFIG: serverName=d4d
      PHP_XDEBUG_IDEKEY: "PHPSTORM"
      PHP_XDEBUG_START_WITH_REQUEST: trigger
      PHP_XDEBUG_TRIGGER_VALUE: "PHPSTORM"
      PHP_XDEBUG_PROFILER_OUTPUT_NAME: "cachegrind.out.%t"
#      XDEBUG_SESSION: 1 # Always run XDEBUG.
# For run xdebug from CLI XDEBUG_SESSION=PHPSTORM sh -c './vendor/bin/drush scr scripts/test.php'
    volumes:
      - ./code:/var/www/html
      - ./files:/mnt/files
```
