### ISSUE TITLE
D4D Examples: Decrease xdebug log level in php container cli

### ISSUE THREAD

**Issue by iVegas** [wodby/docker4drupal#507]
Use the following environment variable definition in docker-compose.override.yml for php container:
```
services:
  php:
    environment:
      PHP_XDEBUG_LOG_LEVEL: 0

```
