### ISSUE TITLE
D4D Examples: Xdebug session won't start

### ISSUE THREAD

**Issue by iVegas** [wodby/docker4drupal#508]
It is worth trying to set the following environment variable to force start session:
```
services:
  php:
    environment:
      PHP_XDEBUG_START_WITH_REQUEST: "yes"
```
