### ISSUE TITLE
Expose project port in .env

### ISSUE THREAD

**Issue by igorbiki** [wodby/docker4drupal#516]
**Is your feature request related to a problem? Please describe.**
By default project port is 8000, and if you want running multiple project you need to update all ports for one project. My personal preference is that I have multiproject setup (e.g. dev1, dev2, stage1, stage2, etc) and sometimes if I need to check something on one, I just bring up that env, do what needs to be done and stop it. Meanwhile other dev env is up the whole time. This applies to local development environment of course. 

**Describe the solution you'd like**
If port is exposed in .env file, and then some minor updates in docker-compose.ym to take care of port mapping. 

.env file example
```
### PROJECT SETTINGS

PROJECT_NAME=dev1_project
PROJECT_BASE_URL=dev1.docker.localhost
PROJECT_PORT=8100
```

Followed by docker-compose.yml updates
```
  php:
    image: wodby/drupal-php:$PHP_TAG
    container_name: "${PROJECT_NAME}_php"
    ..
    DRUSH_OPTIONS_URI: "http://${PROJECT_BASE_URL}:${PROJECT_PORT}"
    BROWSERTEST_OUTPUT_BASE_URL: "http://${PROJECT_BASE_URL}:${PROJECT_PORT}"


  traefik:
    image: traefik:v2.0
    container_name: "${PROJECT_NAME}_traefik"
    command: --api.insecure=true --providers.docker
    ports:
    - '${PROJECT_PORT}:80'
#    - '8080:8080' # Dashboard
```

**Additional context**
When running phpunit tests exposing BROWSERTEST_OUTPUT_BASE_URL helps with urls to be clickable. By default host is `http://nginx` and generated urls are not clickable, you need copy/paste to see snapshot (in case of functional php tests error).

You will need to keep track of ports per project, but even if you find two projects using same port, updating one spot (.env) will resolve the issue.

KUDOS on awesome project!
