### ISSUE TITLE
Mailhog does not register emails with newly defined paths

### ISSUE THREAD

**Issue by Holo96** [wodby/docker4drupal#517]
***OS type***
Linux

***Drupal version***
9

***Codebase***
Using drupal contrib module "mail system" php sender

**Describe the bug**
With newest versions of all containers mailhog does not register emails with newly defined paths

# Solution
With this config mailhog does not work:
```yml
environment:
  SSMTP_MAILHUB: mailhog:1025
#  SSMTP_MAILHUB: opensmtpd:25
  PHP_SENDMAIL_PATH: '"/usr/bin/dos2unix -u | /usr/sbin/ssmtp -f -t"'
```
But when I updated evironment variables to this it worked as expected:
```yml
environment:
  SSMTP_MAILHUB: mailhog:1025
#  SSMTP_MAILHUB: opensmtpd:25
  PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S
```
