### ISSUE TITLE
Docker4drupal, d4d - how to see/access files of the conteiner? How to edit files? How to commit files of Drupal to git?

### ISSUE THREAD

**Issue by o771e** [wodby/docker4drupal#522]
There are files in the php container, `ls -1`
````
composer.json
composer.lock
vendor
web
````

Where are they? I was expecting them in my d4d folder?
My d-c.yml
````
php:
    volumes:
    - ./:/var/www/html:cached
nginx:
    volumes:
    - ./:/var/www/html:cached
````

What do I do to be able to see files?
