### ISSUE TITLE
Full support form arm64 architecture?

### ISSUE THREAD

**Issue by arrubiu** [wodby/docker4drupal#560]
I'm working, for the first time, on a Macbook with M2Pro chip.
I need to use linux/arm64 images and I know that last release hasn't the arm64 version for MariaDB.
Could someone tell me which is the last release with full support of arm64 architecture?

I've read here (https://github.com/wodby/docker4drupal/issues/526#issuecomment-1537117431) that the last version of MariaDB with arm64 is MARIADB_TAG=10.4-3.13.21

Thanks!

**Comment by igorbiki** [comment]
This works for me (have M1), it may not be the solution you need, but it works. Without it, docker complains about architecture for mariadb service.

``` 
 mariadb:
    image: wodby/mariadb:$MARIADB_TAG
    container_name: "${PROJECT_NAME}_mariadb"
    stop_grace_period: 30s
    platform: linux/amd64
    environment:
```

Note: platform key under mariadb service.
