### ISSUE TITLE
How to use drush

### ISSUE THREAD

**Issue by AgenceMiNT** [wodby/docker4drupal#580]
Now that Global drush and drush launcher is gone, how can I still use the "drush" command ?
Is it possible to add it to the PATH or create an alias in the docker-compose.yml ?

**Comment by csandanov** [comment]
for drupal 7 you can set env var `DRUPAL7_INSTALL_GLOBAL_DRUSH` to any value to install global drush 7.x on container start up

**Comment by AgenceMiNT** [comment]
I use Drupal 10/11

**Comment by csandanov** [comment]
with drupal 10/11 you can install drush as a part of your composer project:
```
composer require drush/drush
```

**Comment by AgenceMiNT** [comment]
I have required drush/drush.
But "drush" command doesn't work inside the php container: _bash: drush: command not found_. I have to use "vendor/bin/drush" in order for it to work.

**Comment by csandanov** [comment]
I guess this is because your vendor directory isn't located in the standard path `/var/www/html`, in this case you just need to pass $PATH env var with your added path

**Comment by csandanov** [comment]
this is the default value of `$PATH` in php image:

```
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/wodby/.composer/vendor/bin:/var/www/html/vendor/bin:/var/www/html/bin
```

you can add your own path in the end, e.g. `$PATH:/your/extra/path` it in you compose.yml file:

```yml
services:
  php:
    # ....
    environment:
      PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/home/wodby/.composer/vendor/bin:/var/www/html/vendor/bin:/var/www/html/bin:/your/extra/path
```
