### ISSUE TITLE
drush Can't connect to MySQL server on '127.0.0.1'

### ISSUE THREAD

**Issue by metalvarez** [Wodby/docker4drupal#68]
Hi guys, I'm a total newbie using docker, and I wanted to set up a local development environment for drupal (also a newbie in drupal), anyway here is my docker-compose.yml

```
version: "2"

services:
  mariadb:
    image: wodby/drupal-mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
    volumes:
      - ./docker-runtime/mariadb:/var/lib/mysql
  php:
    image: wodby/drupal-php:7.0 # Allowed: 7.0, 5.6.
    environment:
      PHP_SITE_NAME: dev
      PHP_HOST_NAME: localhost:8000
      PHP_SENDMAIL_PATH: /usr/sbin/sendmail -t -i -S mailhog:1025
    volumes:
      - ./:/var/www/html
```
and here my db configuration in settings.php

$databases['default']['default'] = array (
  'database' => 'drupal',
  'username' => 'drupal',
  'password' => 'drupal',
  'host' => '127.0.0.1',
  'port' => '3306',
  'driver' => 'mysql',
  'prefix' => '',
  'collation' => 'utf8mb4_general_ci',
);
Is it somenthing missing in my docker-compose file ? by reading your docs my drush container should be able to work without any problems or maybe I'm missing other extra steps to get this up and running, because when I run `docker-compose exec --user 82 php drush cr` I get the following error
`PDOException: SQLSTATE[HY000] [2003] Can't connect to MySQL server on '127.0.0.1' (111 "Connection refused") in /var/www/html/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php:142`
