### ISSUE TITLE
multisite?

### ISSUE THREAD

**Issue by tgww** [wodby/docker4drupal#69]
I do not understand how to run multisite?

**Comment by PavelPrischepa** [comment]
Just copy paste mariadb service definition

```
  mariadb1:
    image: wodby/drupal-mariadb:1.0.0
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal

  mariadb2:
    image: wodby/drupal-mariadb:1.0.0
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal

...
```
then specify db hostname in settings.php mariadb1 for site1, mariadb2 for site2 - and so on.
