### ISSUE TITLE
Node.JS and Gulp

### ISSUE THREAD

**Issue by codeyy** [wodby/docker4drupal#73]
To work with a Zen theme you need to install all the Node.JS software you need (npm install) and you need to run a "gulp watch" to watch the SASS files while you develop.

I can't seem to find how to get this done with Docker, can anyone point me in the right direction?

**Comment by PavelPrischepa** [comment]
Hi @codeyy ,

Try to follow this way. Add services to the compose file.

```
  npm:
    image: wodby/node
    volumes_from:
      - php
    user: www-data
    command: npm install

  gulp:
    image: wodby/node
    volumes_from:
      - php
    depends_on:
      - npm
    user: www-data
    command: gulp
```

**Comment by codeyy** [comment]
Hey @PavelPrischepa , thanks a lot for your feedback!

I'm in the process of learning more about Docker, so I'm trying to understand what you are providing to be able to tweak it.

For one both commands should be executed from within the themes folder, but I can't seem to figure out how to do that. I tried something like this :
`command: bash -c "cd /var/www/html/web/sites/all/themes/ott && gulp watch"`

I was able to start my docker processes, but the .css file doesn't get regenerated when I change something in the .scss files. That brings me to a second question, is it possible to view the output from the commands to debug what I am doing wrong?

**Comment by PavelPrischepa** [comment]
Use a `working_dir` option instead of `cd ...`. 
```
  gulp:
    image: wodby/node
    volumes_from:
      - php
    depends_on:
      - npm
    user: www-data
    working_dir: /var/www/html/web/sites/all/themes/ott
    command: gulp watch
```
To view the output start containers in foreground `docker-compose up` or start gulp container only `docker-compose start gulp`.
