### ISSUE TITLE
Any plans for maintaining a PostgreSQL image?

### ISSUE THREAD

**Issue by ndobromirov** [wodby/docker4drupal#94]
Even though Drupal is being developed and most often deployed with MySQL, it supports PostgreSQL also. There are many distributions that are recommending PostgreSQL like https://www.drupal.org/project/cartaro and likely others.

I've tested the [official](https://hub.docker.com/_/postgres/) image for it and it's pretty strait forward. What I am missing is configuration tweaks that are PostgreSQL and Drupal related.

Partial docker-compose file:
```
services:
  sql:
    image: postgres:9.6-alpine
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      # Default port of PostgreSQL is 5432.
  php:
    ...
    environment:
      # Pass on connection details through environment variable.
      PHP_SQL_DSN: pgsql://user:pass@sql:5432/database
      ...
  ... (other services)
```

**Comment by csandanov** [comment]
You're welcome to try it our https://github.com/wodby/postgres

**Comment by mradcliffe** [comment]
This worked as-is for me in Linux.

```yaml
version: "2"

services:
  postgresql:
    image: wodby/postgres:9.6-1.1.0
    environment:
      POSTGRES_DB: drupal8
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass

  php:
    image: wodby/drupal8-7.1-2.4.4
    environment:
      DB_HOST: postgresql
      DB_USER: user
      DB_PASSWORD: pass
      DB_NAME: drupal8
      DB_DRIVER: pgsql
```

I didn't try to tune the database using the available environment variables.
